/**
 * KIE.ai Pricing Test Matrix
 *
 * Defines all model x config combinations for pricing verification.
 * Each entry represents one API call to test.
 *
 * Usage: imported by verify-kie-pricing.ts
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TestConfig {
  /** Our internal model key (e.g., "kling-3.0") */
  modelKey: string
  /** KIE category for display grouping */
  category:
    | "image"
    | "video"
    | "text-to-video"
    | "video-to-video"
    | "motion-transfer"
    | "video-upscale"
    | "lip-sync"
    | "music"
    | "tts"
    | "sound-effect"
    | "audio-isolation"
    | "stt"
    | "dialogue"
  /** KIE.ai model identifier sent in API request */
  kieModel: string
  /** Expected KIE credits from models.ts */
  expectedKieCredits: number
  /** Expected cost USD from models.ts */
  expectedCostUsd: number
  /** Human-readable config description */
  configDesc: string
  /** API endpoint type */
  apiType: "standard" | "veo" | "kling3" | "suno" | "kontext" | "runway" | "luma"
  /** Request input params for createTask (or top-level body for special endpoints) */
  input: Record<string, unknown>
  /** Whether this test requires an input image URL */
  requiresImage: boolean
  /** Whether this test requires an input audio URL */
  requiresAudio: boolean
  /** Whether this test requires an input video URL */
  requiresVideo: boolean
  /** Estimated time to complete (seconds) */
  estimatedTimeSec: number
  /** Whether to skip by default (expensive/slow tests) */
  skipByDefault: boolean
}

// ---------------------------------------------------------------------------
// Placeholder assets — tiny public files for minimal-cost tests
// ---------------------------------------------------------------------------

/** 1x1 red PNG (public, tiny) */
export const TEST_IMAGE_URL =
  "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png"

/** Short silence MP3 (~1s) */
export const TEST_AUDIO_URL =
  "https://upload.wikimedia.org/wikipedia/commons/8/8a/Silencio.ogg"

/** Short public domain video (~2s) */
export const TEST_VIDEO_URL =
  "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4"

// ---------------------------------------------------------------------------
// IMAGE TEST CONFIGS
// ---------------------------------------------------------------------------

export const IMAGE_TEST_CONFIGS: TestConfig[] = [
  // --- Nano Banana family ---
  {
    modelKey: "nano-banana",
    category: "image",
    kieModel: "nano-banana-pro",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Nano Banana base (image_size 1:1)",
    apiType: "standard",
    input: { prompt: "test", image_size: "1:1" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "nano-banana-pro",
    category: "image",
    kieModel: "nano-banana-pro",
    expectedKieCredits: 18,
    expectedCostUsd: 0.09,
    configDesc: "Nano Banana Pro 1K",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", resolution: "1K" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "nano-banana-pro:4K",
    category: "image",
    kieModel: "nano-banana-pro",
    expectedKieCredits: 24,
    expectedCostUsd: 0.12,
    configDesc: "Nano Banana Pro 4K (higher cost variant)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", resolution: "4K" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 30,
    skipByDefault: true,
  },
  {
    modelKey: "nano-banana-2",
    category: "image",
    kieModel: "nano-banana-2",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Nano Banana 2 (1K)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", resolution: "1K", output_format: "jpg" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "nano-banana-edit",
    category: "image",
    kieModel: "google/nano-banana-edit",
    expectedKieCredits: 6,
    expectedCostUsd: 0.03,
    configDesc: "Nano Banana Edit (I2I)",
    apiType: "standard",
    input: { prompt: "make it blue", image_urls: ["{{IMAGE}}"], image_size: "1:1" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },

  // --- Flux family ---
  {
    modelKey: "flux",
    category: "image",
    kieModel: "flux-2/pro-text-to-image",
    expectedKieCredits: 5,
    expectedCostUsd: 0.025,
    configDesc: "Flux Pro T2I (1K)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", resolution: "1K" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "flux:2K",
    category: "image",
    kieModel: "flux-2/pro-text-to-image",
    expectedKieCredits: 7,
    expectedCostUsd: 0.035,
    configDesc: "Flux Pro T2I (2K variant)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", resolution: "2K" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "flux-flex",
    category: "image",
    kieModel: "flux-2/flex-text-to-image",
    expectedKieCredits: 14,
    expectedCostUsd: 0.07,
    configDesc: "Flux Flex T2I (1K)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", resolution: "1K" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "flux-i2i",
    category: "image",
    kieModel: "flux-2/flex-image-to-image",
    expectedKieCredits: 14,
    expectedCostUsd: 0.07,
    configDesc: "Flux Flex I2I (1K)",
    apiType: "standard",
    input: { prompt: "make it blue", input_urls: ["{{IMAGE}}"], aspect_ratio: "1:1", resolution: "1K" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "flux-pro-i2i",
    category: "image",
    kieModel: "flux-2/pro-image-to-image",
    expectedKieCredits: 5,
    expectedCostUsd: 0.025,
    configDesc: "Flux Pro I2I (1K)",
    apiType: "standard",
    input: { prompt: "make it blue", input_urls: ["{{IMAGE}}"], aspect_ratio: "1:1", resolution: "1K" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },

  // --- Grok family ---
  {
    modelKey: "grok",
    category: "image",
    kieModel: "grok-imagine/text-to-image",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Grok T2I",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "grok-i2i",
    category: "image",
    kieModel: "grok-imagine/image-to-image",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Grok I2I",
    apiType: "standard",
    input: { prompt: "make it blue", image_urls: ["{{IMAGE}}"] },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },

  // --- GPT Image family ---
  {
    modelKey: "gpt-image",
    category: "image",
    kieModel: "gpt-image/1.5-text-to-image",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "GPT Image T2I (medium)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", quality: "medium" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "gpt-image:high",
    category: "image",
    kieModel: "gpt-image/1.5-text-to-image",
    expectedKieCredits: 22,
    expectedCostUsd: 0.11,
    configDesc: "GPT Image T2I (high quality variant)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", quality: "high" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 30,
    skipByDefault: true,
  },
  {
    modelKey: "gpt-image-i2i",
    category: "image",
    kieModel: "gpt-image/1.5-image-to-image",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "GPT Image I2I (medium)",
    apiType: "standard",
    input: { prompt: "make it blue", input_urls: ["{{IMAGE}}"], aspect_ratio: "1:1", quality: "medium" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },

  // --- Imagen4 family ---
  {
    modelKey: "imagen4",
    category: "image",
    kieModel: "google/imagen4",
    expectedKieCredits: 8,
    expectedCostUsd: 0.04,
    configDesc: "Imagen4",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "imagen4-fast",
    category: "image",
    kieModel: "google/imagen4-fast",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Imagen4 Fast",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 10,
    skipByDefault: false,
  },
  {
    modelKey: "imagen4-ultra",
    category: "image",
    kieModel: "google/imagen4-ultra",
    expectedKieCredits: 12,
    expectedCostUsd: 0.06,
    configDesc: "Imagen4 Ultra",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 30,
    skipByDefault: false,
  },

  // --- Ideogram family ---
  {
    modelKey: "ideogram",
    category: "image",
    kieModel: "ideogram/character",
    expectedKieCredits: 18,
    expectedCostUsd: 0.09,
    configDesc: "Ideogram Character (BALANCED)",
    apiType: "standard",
    input: { prompt: "test", image_size: "square", style: "AUTO", rendering_speed: "BALANCED" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 25,
    skipByDefault: false,
  },
  {
    modelKey: "ideogram:TURBO",
    category: "image",
    kieModel: "ideogram/character",
    expectedKieCredits: 12,
    expectedCostUsd: 0.06,
    configDesc: "Ideogram Character (TURBO variant)",
    apiType: "standard",
    input: { prompt: "test", image_size: "square", style: "AUTO", rendering_speed: "TURBO" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "ideogram:QUALITY",
    category: "image",
    kieModel: "ideogram/character",
    expectedKieCredits: 24,
    expectedCostUsd: 0.12,
    configDesc: "Ideogram Character (QUALITY variant)",
    apiType: "standard",
    input: { prompt: "test", image_size: "square", style: "AUTO", rendering_speed: "QUALITY" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 40,
    skipByDefault: true,
  },
  {
    modelKey: "ideogram-edit",
    category: "image",
    kieModel: "ideogram/character-edit",
    expectedKieCredits: 18,
    expectedCostUsd: 0.09,
    configDesc: "Ideogram Edit (BALANCED)",
    apiType: "standard",
    input: { prompt: "make it blue", image_url: "{{IMAGE}}", style: "AUTO", rendering_speed: "BALANCED" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 25,
    skipByDefault: false,
  },
  {
    modelKey: "ideogram-remix",
    category: "image",
    kieModel: "ideogram/character-remix",
    expectedKieCredits: 18,
    expectedCostUsd: 0.09,
    configDesc: "Ideogram Remix (BALANCED)",
    apiType: "standard",
    input: { prompt: "test", image_url: "{{IMAGE}}", image_size: "square", style: "AUTO", rendering_speed: "BALANCED", strength: 0.8 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 25,
    skipByDefault: false,
  },
  {
    modelKey: "ideogram-reframe",
    category: "image",
    kieModel: "ideogram/v3-reframe",
    expectedKieCredits: 18,
    expectedCostUsd: 0.09,
    configDesc: "Ideogram Reframe (BALANCED)",
    apiType: "standard",
    input: { image_url: "{{IMAGE}}", image_size: "square", rendering_speed: "BALANCED" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 25,
    skipByDefault: false,
  },

  // --- Qwen family ---
  {
    modelKey: "qwen",
    category: "image",
    kieModel: "qwen/text-to-image",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Qwen T2I",
    apiType: "standard",
    input: { prompt: "test", image_size: "square", output_format: "png" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "qwen-i2i",
    category: "image",
    kieModel: "qwen/image-to-image",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Qwen I2I",
    apiType: "standard",
    input: { prompt: "make it blue", image_url: "{{IMAGE}}", output_format: "png", strength: 0.8 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
  {
    modelKey: "qwen-edit",
    category: "image",
    kieModel: "qwen/image-edit",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Qwen Edit",
    apiType: "standard",
    input: { prompt: "make it blue", image_url: "{{IMAGE}}", image_size: "square", output_format: "png" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },

  // --- Seedream family ---
  {
    modelKey: "seedream",
    category: "image",
    kieModel: "seedream/4.5-text-to-image",
    expectedKieCredits: 6.5,
    expectedCostUsd: 0.032,
    configDesc: "Seedream 4.5 T2I (basic)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", quality: "basic" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "seedream-edit",
    category: "image",
    kieModel: "seedream/4.5-edit",
    expectedKieCredits: 6.5,
    expectedCostUsd: 0.032,
    configDesc: "Seedream 4.5 Edit (basic)",
    apiType: "standard",
    input: { prompt: "make it blue", image_urls: ["{{IMAGE}}"], aspect_ratio: "1:1", quality: "basic" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "seedream-5-lite",
    category: "image",
    kieModel: "seedream/5-lite-text-to-image",
    expectedKieCredits: 6.5,
    expectedCostUsd: 0.032,
    configDesc: "Seedream 5 Lite T2I (basic)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1", quality: "basic" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "seedream-5-lite-i2i",
    category: "image",
    kieModel: "seedream/5-lite-image-to-image",
    expectedKieCredits: 6.5,
    expectedCostUsd: 0.032,
    configDesc: "Seedream 5 Lite I2I (basic)",
    apiType: "standard",
    input: { prompt: "make it blue", image: "{{IMAGE}}", aspect_ratio: "1:1", quality: "basic" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },

  // --- Z-Image ---
  {
    modelKey: "z-image",
    category: "image",
    kieModel: "z-image",
    expectedKieCredits: 0.8,
    expectedCostUsd: 0.004,
    configDesc: "Z-Image (cheapest image model)",
    apiType: "standard",
    input: { prompt: "test", aspect_ratio: "1:1" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 10,
    skipByDefault: false,
  },

  // --- Recraft utilities ---
  {
    modelKey: "recraft-remove-bg",
    category: "image",
    kieModel: "recraft/remove-background",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Recraft Remove Background",
    apiType: "standard",
    input: { image: "{{IMAGE}}" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 10,
    skipByDefault: false,
  },
  {
    modelKey: "recraft-upscale",
    category: "image",
    kieModel: "recraft/crisp-upscale",
    expectedKieCredits: 6,
    expectedCostUsd: 0.03,
    configDesc: "Recraft Crisp Upscale",
    apiType: "standard",
    input: { image: "{{IMAGE}}" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },

  // --- Topaz image upscale ---
  {
    modelKey: "topaz-image-upscale",
    category: "image",
    kieModel: "topaz/image-upscale",
    expectedKieCredits: 6,
    expectedCostUsd: 0.03,
    configDesc: "Topaz Image Upscale (2x)",
    apiType: "standard",
    input: { image_url: "{{IMAGE}}", upscale_factor: "2" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },

  // --- Grok Upscale (requires task_id from prior grok generation, skipped by default) ---
  {
    modelKey: "grok-upscale",
    category: "image",
    kieModel: "grok-imagine/upscale",
    expectedKieCredits: 4,
    expectedCostUsd: 0.02,
    configDesc: "Grok Upscale (needs task_id, skip unless chained)",
    apiType: "standard",
    input: { task_id: "{{GROK_TASK_ID}}" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: true,
  },

  // --- Flux Kontext (special endpoint) ---
  {
    modelKey: "flux-kontext",
    category: "image",
    kieModel: "flux-kontext-pro",
    expectedKieCredits: 10,
    expectedCostUsd: 0.05,
    configDesc: "Flux Kontext Pro T2I",
    apiType: "kontext",
    input: { prompt: "test", aspectRatio: "1:1", outputFormat: "jpeg" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 20,
    skipByDefault: false,
  },
  {
    modelKey: "flux-kontext-max",
    category: "image",
    kieModel: "flux-kontext-max",
    expectedKieCredits: 20,
    expectedCostUsd: 0.10,
    configDesc: "Flux Kontext Max T2I",
    apiType: "kontext",
    input: { prompt: "test", aspectRatio: "1:1", outputFormat: "jpeg" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 30,
    skipByDefault: true,
  },
]

// ---------------------------------------------------------------------------
// VIDEO TEST CONFIGS (Image-to-Video + Text-to-Video)
// ---------------------------------------------------------------------------

export const VIDEO_TEST_CONFIGS: TestConfig[] = [
  // ==================== IMAGE-TO-VIDEO ====================

  // --- MiniMax / Hailuo ---
  {
    modelKey: "minimax",
    category: "video",
    kieModel: "hailuo/02-image-to-video-pro",
    expectedKieCredits: 80,
    expectedCostUsd: 0.40,
    configDesc: "Hailuo 02 Pro I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", prompt_optimizer: false },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- VEO family (special endpoint) ---
  {
    modelKey: "veo3",
    category: "video",
    kieModel: "veo3",
    expectedKieCredits: 400,
    expectedCostUsd: 2.00,
    configDesc: "VEO3 I2V (8s fixed, EXPENSIVE)",
    apiType: "veo",
    input: { prompt: "a gentle motion", imageUrls: ["{{IMAGE}}"], generationType: "FIRST_AND_LAST_FRAMES_2_VIDEO" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 300,
    skipByDefault: true,
  },
  {
    modelKey: "veo3.1",
    category: "video",
    kieModel: "veo3_fast",
    expectedKieCredits: 250,
    expectedCostUsd: 1.25,
    configDesc: "VEO3.1 Fast I2V (8s fixed)",
    apiType: "veo",
    input: { prompt: "a gentle motion", imageUrls: ["{{IMAGE}}"], generationType: "FIRST_AND_LAST_FRAMES_2_VIDEO" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 180,
    skipByDefault: true,
  },

  // --- Kling family (I2V) - duration variants ---
  {
    modelKey: "kling",
    category: "video",
    kieModel: "kling-2.6/image-to-video",
    expectedKieCredits: 70,
    expectedCostUsd: 0.35,
    configDesc: "Kling 2.6 I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], sound: false, duration: "5" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "kling:10s",
    category: "video",
    kieModel: "kling-2.6/image-to-video",
    expectedKieCredits: 70,
    expectedCostUsd: 0.35,
    configDesc: "Kling 2.6 I2V (10s, check if cost differs)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], sound: false, duration: "10" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 180,
    skipByDefault: true,
  },
  {
    modelKey: "kling-turbo",
    category: "video",
    kieModel: "kling/v2-5-turbo-image-to-video-pro",
    expectedKieCredits: 50,
    expectedCostUsd: 0.25,
    configDesc: "Kling Turbo I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", duration: "5", cfg_scale: 0.5 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 90,
    skipByDefault: false,
  },

  // --- Kling 3.0 (special client) - duration + mode + sound variants ---
  {
    modelKey: "kling-3.0",
    category: "video",
    kieModel: "kling-3.0/video",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Kling 3.0 I2V (5s, pro, sound)",
    apiType: "kling3",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], sound: true, duration: "5", mode: "pro", multi_shots: false },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "kling-3.0:std",
    category: "video",
    kieModel: "kling-3.0/video",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Kling 3.0 I2V (5s, std mode, check cost diff)",
    apiType: "kling3",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], sound: false, duration: "5", mode: "std", multi_shots: false },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 90,
    skipByDefault: true,
  },
  {
    modelKey: "kling-3.0:10s",
    category: "video",
    kieModel: "kling-3.0/video",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Kling 3.0 I2V (10s, check cost diff)",
    apiType: "kling3",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], sound: true, duration: "10", mode: "pro", multi_shots: false },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 180,
    skipByDefault: true,
  },
  {
    modelKey: "kling-3.0:no-sound",
    category: "video",
    kieModel: "kling-3.0/video",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Kling 3.0 I2V (5s, no sound, check cost diff)",
    apiType: "kling3",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], sound: false, duration: "5", mode: "pro", multi_shots: false },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: true,
  },

  // --- Grok I2V ---
  {
    modelKey: "grok-i2v",
    category: "video",
    kieModel: "grok-imagine/image-to-video",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Grok I2V (6s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], mode: "normal", duration: "6" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Sora2 family (I2V) ---
  {
    modelKey: "sora2-pro",
    category: "video",
    kieModel: "sora-2-pro-image-to-video",
    expectedKieCredits: 200,
    expectedCostUsd: 1.00,
    configDesc: "Sora2 Pro I2V (5s/n_frames=10)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], aspect_ratio: "landscape", n_frames: "10", size: "standard", remove_watermark: true },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 180,
    skipByDefault: true,
  },
  {
    modelKey: "sora2",
    category: "video",
    kieModel: "sora-2-image-to-video",
    expectedKieCredits: 120,
    expectedCostUsd: 0.60,
    configDesc: "Sora2 I2V (5s/n_frames=10)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], aspect_ratio: "landscape", n_frames: "10", remove_watermark: true },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 150,
    skipByDefault: true,
  },

  // --- Seedance ---
  {
    modelKey: "seedance",
    category: "video",
    kieModel: "bytedance/seedance-1.5-pro",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Seedance 1.5 Pro I2V (4s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", input_urls: ["{{IMAGE}}"], resolution: "720p", fixed_lens: false, generate_audio: false, duration: 4 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "seedance:12s",
    category: "video",
    kieModel: "bytedance/seedance-1.5-pro",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Seedance 1.5 Pro I2V (12s, check cost diff)",
    apiType: "standard",
    input: { prompt: "a gentle motion", input_urls: ["{{IMAGE}}"], resolution: "720p", fixed_lens: false, generate_audio: false, duration: 12 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 200,
    skipByDefault: true,
  },

  // --- Wan family (I2V) ---
  {
    modelKey: "wan-i2v",
    category: "video",
    kieModel: "wan/2-6-image-to-video",
    expectedKieCredits: 80,
    expectedCostUsd: 0.40,
    configDesc: "Wan 2.6 I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], resolution: "720p", duration: 5 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "wan-i2v:15s",
    category: "video",
    kieModel: "wan/2-6-image-to-video",
    expectedKieCredits: 80,
    expectedCostUsd: 0.40,
    configDesc: "Wan 2.6 I2V (15s, check cost diff)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_urls: ["{{IMAGE}}"], resolution: "720p", duration: 15 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 240,
    skipByDefault: true,
  },
  {
    modelKey: "wan-turbo",
    category: "video",
    kieModel: "wan/2-2-a14b-image-to-video-turbo",
    expectedKieCredits: 40,
    expectedCostUsd: 0.20,
    configDesc: "Wan Turbo I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", resolution: "480p" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 60,
    skipByDefault: false,
  },

  // --- Hailuo 2.3 family ---
  {
    modelKey: "hailuo-2.3-pro",
    category: "video",
    kieModel: "hailuo/2-3-image-to-video-pro",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Hailuo 2.3 Pro I2V (6s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", resolution: "768P", duration: 6 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "hailuo-2.3",
    category: "video",
    kieModel: "hailuo/2-3-image-to-video-standard",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Hailuo 2.3 Standard I2V (6s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", resolution: "768P", duration: 6 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "hailuo-standard",
    category: "video",
    kieModel: "hailuo/02-image-to-video-standard",
    expectedKieCredits: 50,
    expectedCostUsd: 0.25,
    configDesc: "Hailuo 02 Standard I2V (6s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", prompt_optimizer: false, resolution: "768P", duration: 6 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Bytedance family (I2V) ---
  {
    modelKey: "bytedance-lite",
    category: "video",
    kieModel: "bytedance/v1-lite-image-to-video",
    expectedKieCredits: 50,
    expectedCostUsd: 0.25,
    configDesc: "Bytedance Lite I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", resolution: "480p", duration: 5 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 90,
    skipByDefault: false,
  },
  {
    modelKey: "bytedance-pro",
    category: "video",
    kieModel: "bytedance/v1-pro-image-to-video",
    expectedKieCredits: 70,
    expectedCostUsd: 0.35,
    configDesc: "Bytedance Pro I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", resolution: "480p", duration: 5 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "bytedance-pro-fast",
    category: "video",
    kieModel: "bytedance/v1-pro-fast-image-to-video",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Bytedance Pro Fast I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", resolution: "720p", duration: 5 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 90,
    skipByDefault: false,
  },

  // --- Kling Master ---
  {
    modelKey: "kling-master",
    category: "video",
    kieModel: "kling/v2-1-master-image-to-video",
    expectedKieCredits: 70,
    expectedCostUsd: 0.35,
    configDesc: "Kling Master I2V (5s)",
    apiType: "standard",
    input: { prompt: "a gentle motion", image_url: "{{IMAGE}}", duration: "5", cfg_scale: 0.5 },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Runway KIE (special endpoint) ---
  {
    modelKey: "runway-kie",
    category: "video",
    kieModel: "runway",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Runway KIE I2V (5s)",
    apiType: "runway",
    input: { prompt: "a gentle motion", imageUrl: "{{IMAGE}}", duration: 5, quality: "720p" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // ==================== TEXT-TO-VIDEO ====================

  // --- Hailuo T2V ---
  {
    modelKey: "minimax-t2v",
    category: "text-to-video",
    kieModel: "hailuo/02-text-to-video-pro",
    expectedKieCredits: 80,
    expectedCostUsd: 0.40,
    configDesc: "Hailuo 02 Pro T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", prompt_optimizer: false },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- VEO T2V ---
  {
    modelKey: "veo3-t2v",
    category: "text-to-video",
    kieModel: "veo3",
    expectedKieCredits: 400,
    expectedCostUsd: 2.00,
    configDesc: "VEO3 T2V (8s fixed, EXPENSIVE)",
    apiType: "veo",
    input: { prompt: "a red ball bouncing", generationType: "TEXT_2_VIDEO" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 300,
    skipByDefault: true,
  },

  // --- Kling T2V family ---
  {
    modelKey: "kling-t2v",
    category: "text-to-video",
    kieModel: "kling-2.6/text-to-video",
    expectedKieCredits: 70,
    expectedCostUsd: 0.35,
    configDesc: "Kling 2.6 T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", sound: false, aspect_ratio: "16:9", duration: "5" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "kling-turbo-t2v",
    category: "text-to-video",
    kieModel: "kling/v2-5-turbo-text-to-video-pro",
    expectedKieCredits: 50,
    expectedCostUsd: 0.25,
    configDesc: "Kling Turbo T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", duration: "5", cfg_scale: 0.5 },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 90,
    skipByDefault: false,
  },

  // --- Grok T2V ---
  {
    modelKey: "grok-t2v",
    category: "text-to-video",
    kieModel: "grok-imagine/text-to-video",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Grok T2V (6s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", aspect_ratio: "16:9", mode: "normal", duration: "6", resolution: "720p" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Sora2 Pro T2V ---
  {
    modelKey: "sora2-pro-t2v",
    category: "text-to-video",
    kieModel: "sora-2-pro-text-to-video",
    expectedKieCredits: 200,
    expectedCostUsd: 1.00,
    configDesc: "Sora2 Pro T2V (5s/n_frames=10)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", aspect_ratio: "landscape", n_frames: "10", remove_watermark: true },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 180,
    skipByDefault: true,
  },

  // --- Kling 3.0 T2V ---
  {
    modelKey: "kling-3.0-t2v",
    category: "text-to-video",
    kieModel: "kling-3.0/video",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Kling 3.0 T2V (5s, pro, sound)",
    apiType: "kling3",
    input: { prompt: "a red ball bouncing", sound: true, duration: "5", mode: "pro", multi_shots: false },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Seedance T2V ---
  {
    modelKey: "seedance-t2v",
    category: "text-to-video",
    kieModel: "bytedance/seedance-1.5-pro",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Seedance 1.5 Pro T2V (4s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", resolution: "720p", fixed_lens: false, generate_audio: false, duration: 4 },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Wan T2V ---
  {
    modelKey: "wan-t2v",
    category: "text-to-video",
    kieModel: "wan/2-6-text-to-video",
    expectedKieCredits: 80,
    expectedCostUsd: 0.40,
    configDesc: "Wan 2.6 T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", resolution: "1080p", duration: 5 },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Sora2 T2V ---
  {
    modelKey: "sora2-t2v",
    category: "text-to-video",
    kieModel: "sora-2-text-to-video",
    expectedKieCredits: 120,
    expectedCostUsd: 0.60,
    configDesc: "Sora2 T2V (5s/n_frames=10)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", aspect_ratio: "landscape", n_frames: "10", remove_watermark: true },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 150,
    skipByDefault: true,
  },

  // --- Hailuo Standard T2V ---
  {
    modelKey: "hailuo-standard-t2v",
    category: "text-to-video",
    kieModel: "hailuo/02-text-to-video-standard",
    expectedKieCredits: 50,
    expectedCostUsd: 0.25,
    configDesc: "Hailuo 02 Standard T2V",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", prompt_optimizer: false },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Bytedance family T2V ---
  {
    modelKey: "bytedance-lite-t2v",
    category: "text-to-video",
    kieModel: "bytedance/v1-lite-text-to-video",
    expectedKieCredits: 50,
    expectedCostUsd: 0.25,
    configDesc: "Bytedance Lite T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", aspect_ratio: "16:9", resolution: "720p", duration: 5 },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 90,
    skipByDefault: false,
  },
  {
    modelKey: "bytedance-pro-t2v",
    category: "text-to-video",
    kieModel: "bytedance/v1-pro-text-to-video",
    expectedKieCredits: 70,
    expectedCostUsd: 0.35,
    configDesc: "Bytedance Pro T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", aspect_ratio: "16:9", resolution: "720p", duration: 5 },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Wan Turbo T2V ---
  {
    modelKey: "wan-turbo-t2v",
    category: "text-to-video",
    kieModel: "wan/2-2-a14b-text-to-video-turbo",
    expectedKieCredits: 40,
    expectedCostUsd: 0.20,
    configDesc: "Wan Turbo T2V (5s)",
    apiType: "standard",
    input: { prompt: "a red ball bouncing", aspect_ratio: "16:9", resolution: "720p" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 60,
    skipByDefault: false,
  },

  // --- Runway KIE T2V (special endpoint) ---
  {
    modelKey: "runway-kie-t2v",
    category: "text-to-video",
    kieModel: "runway",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Runway KIE T2V (5s)",
    apiType: "runway",
    input: { prompt: "a red ball bouncing", duration: 5, quality: "720p", aspectRatio: "16:9" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
]

// ---------------------------------------------------------------------------
// AUDIO TEST CONFIGS
// ---------------------------------------------------------------------------

export const AUDIO_TEST_CONFIGS: TestConfig[] = [
  // --- TTS ---
  {
    modelKey: "elevenlabs-turbo",
    category: "tts",
    kieModel: "elevenlabs/text-to-speech-turbo-2-5",
    expectedKieCredits: 10,
    expectedCostUsd: 0.03,
    configDesc: "ElevenLabs Turbo TTS",
    apiType: "standard",
    input: { text: "Hello world.", voice_id: "21m00Tcm4TlvDq8ikWAM" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 10,
    skipByDefault: false,
  },
  {
    modelKey: "elevenlabs-multilingual",
    category: "tts",
    kieModel: "elevenlabs/text-to-speech-multilingual-v2",
    expectedKieCredits: 10,
    expectedCostUsd: 0.06,
    configDesc: "ElevenLabs Multilingual TTS",
    apiType: "standard",
    input: { text: "Hello world.", voice_id: "21m00Tcm4TlvDq8ikWAM" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 10,
    skipByDefault: false,
  },

  // --- Music (Suno - special endpoint) ---
  {
    modelKey: "suno",
    category: "music",
    kieModel: "suno/v4",
    expectedKieCredits: 20,
    expectedCostUsd: 0.10,
    configDesc: "Suno V4 Music Generation",
    apiType: "suno",
    input: { prompt: "upbeat pop song about testing", model: "V4", customMode: false, instrumental: false },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "suno-v5",
    category: "music",
    kieModel: "suno/v5",
    expectedKieCredits: 40,
    expectedCostUsd: 0.20,
    configDesc: "Suno V5 Music Generation",
    apiType: "suno",
    input: { prompt: "upbeat pop song about testing", model: "V5", customMode: false, instrumental: false },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },

  // --- Sound Effects ---
  {
    modelKey: "elevenlabs-sfx",
    category: "sound-effect",
    kieModel: "elevenlabs/sound-effect-v2",
    expectedKieCredits: 10,
    expectedCostUsd: 0.0012,
    configDesc: "ElevenLabs SFX V2",
    apiType: "standard",
    input: { text: "a short beep", duration_seconds: 1 },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },

  // --- Audio Isolation ---
  {
    modelKey: "elevenlabs-isolation",
    category: "audio-isolation",
    kieModel: "elevenlabs/audio-isolation",
    expectedKieCredits: 1,
    expectedCostUsd: 0.01,
    configDesc: "ElevenLabs Audio Isolation",
    apiType: "standard",
    input: { audio_url: "{{AUDIO}}" },
    requiresImage: false,
    requiresAudio: true,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },

  // --- STT ---
  {
    modelKey: "elevenlabs-stt",
    category: "stt",
    kieModel: "elevenlabs/speech-to-text",
    expectedKieCredits: 10,
    expectedCostUsd: 0.05,
    configDesc: "ElevenLabs Speech-to-Text",
    apiType: "standard",
    input: { audio_url: "{{AUDIO}}" },
    requiresImage: false,
    requiresAudio: true,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },

  // --- Dialogue ---
  {
    modelKey: "elevenlabs-dialogue",
    category: "dialogue",
    kieModel: "elevenlabs/text-to-dialogue-v3",
    expectedKieCredits: 10,
    expectedCostUsd: 0.05,
    configDesc: "ElevenLabs Text-to-Dialogue V3",
    apiType: "standard",
    input: { script: [{ voice_id: "21m00Tcm4TlvDq8ikWAM", text: "Hello world." }] },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: false,
    estimatedTimeSec: 15,
    skipByDefault: false,
  },
]

// ---------------------------------------------------------------------------
// OTHER TEST CONFIGS (V2V, motion transfer, video upscale, lip sync)
// ---------------------------------------------------------------------------

export const OTHER_TEST_CONFIGS: TestConfig[] = [
  // --- Video-to-Video ---
  {
    modelKey: "wan-v2v",
    category: "video-to-video",
    kieModel: "wan/2-6-video-to-video",
    expectedKieCredits: 80,
    expectedCostUsd: 0.40,
    configDesc: "Wan 2.6 Video-to-Video",
    apiType: "standard",
    input: { prompt: "make it look like anime", video_urls: ["{{VIDEO}}"] },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: true,
    estimatedTimeSec: 180,
    skipByDefault: false,
  },
  {
    modelKey: "luma-modify",
    category: "video-to-video",
    kieModel: "luma-modify",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Luma Modify V2V",
    apiType: "luma",
    input: { prompt: "make it look like anime", videoUrl: "{{VIDEO}}" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: true,
    estimatedTimeSec: 180,
    skipByDefault: false,
  },

  // --- Motion Transfer ---
  {
    modelKey: "kling-motion",
    category: "motion-transfer",
    kieModel: "kling-2.6/motion-control",
    expectedKieCredits: 100,
    expectedCostUsd: 0.50,
    configDesc: "Kling 2.6 Motion Control",
    apiType: "standard",
    input: { prompt: "a person dancing", input_urls: ["{{IMAGE}}"], video_urls: ["{{VIDEO}}"], character_orientation: "image", resolution: "720p" },
    requiresImage: true,
    requiresAudio: false,
    requiresVideo: true,
    estimatedTimeSec: 180,
    skipByDefault: false,
  },

  // --- Video Upscale ---
  {
    modelKey: "topaz-video",
    category: "video-upscale",
    kieModel: "topaz/video-upscale",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Topaz Video Upscale (2x)",
    apiType: "standard",
    input: { video_url: "{{VIDEO}}", upscale_factor: "2" },
    requiresImage: false,
    requiresAudio: false,
    requiresVideo: true,
    estimatedTimeSec: 300,
    skipByDefault: false,
  },

  // --- Lip Sync ---
  {
    modelKey: "kling-avatar",
    category: "lip-sync",
    kieModel: "kling/ai-avatar-standard",
    expectedKieCredits: 40,
    expectedCostUsd: 0.20,
    configDesc: "Kling Avatar Standard (lip sync)",
    apiType: "standard",
    input: { image_url: "{{IMAGE}}", audio_url: "{{AUDIO}}" },
    requiresImage: true,
    requiresAudio: true,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "kling-avatar-pro",
    category: "lip-sync",
    kieModel: "kling/ai-avatar-pro",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Kling Avatar Pro (lip sync)",
    apiType: "standard",
    input: { image_url: "{{IMAGE}}", audio_url: "{{AUDIO}}" },
    requiresImage: true,
    requiresAudio: true,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
  {
    modelKey: "infinitalk",
    category: "lip-sync",
    kieModel: "infinitalk/from-audio",
    expectedKieCredits: 60,
    expectedCostUsd: 0.30,
    configDesc: "Infinitalk Lip Sync",
    apiType: "standard",
    input: { image_url: "{{IMAGE}}", audio_url: "{{AUDIO}}", resolution: "720p" },
    requiresImage: true,
    requiresAudio: true,
    requiresVideo: false,
    estimatedTimeSec: 120,
    skipByDefault: false,
  },
]

// ---------------------------------------------------------------------------
// Combined export
// ---------------------------------------------------------------------------

export const ALL_TEST_CONFIGS: TestConfig[] = [
  ...IMAGE_TEST_CONFIGS,
  ...VIDEO_TEST_CONFIGS,
  ...AUDIO_TEST_CONFIGS,
  ...OTHER_TEST_CONFIGS,
]
