"use client"

import { ArrowUpCircle } from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import type { UpdateInfo } from "@/hooks/use-update-check"

/**
 * The popup behind the sidebar's red dot (founder design, versioning spec
 * 2026-08-19): names the new version, shows the release highlights, and gives
 * the exact upgrade commands — with "back up first" ahead of them, because
 * migrations are forward-only and the backup IS the downgrade path.
 */

/** Release-notes markdown, rendered as plain lines — headings bolded,
 *  bullets kept. Deliberately not a markdown engine: the notes are ours
 *  (generated by the release pipeline), links live behind the full-notes
 *  button, and a renderer would be surface area for nothing. */
function NotesLines({ text }: { readonly text: string }) {
  return (
    <div className="max-h-64 space-y-1 overflow-y-auto rounded-md border bg-muted/30 p-3 text-xs">
      {text.split("\n").map((line, i) => {
        const t = line.trim()
        if (!t) return null
        if (t.startsWith("##")) {
          return (
            <p key={i} className="pt-1 font-semibold">
              {t.replace(/^#+\s*/, "")}
            </p>
          )
        }
        return (
          <p key={i} className="text-muted-foreground">
            {t}
          </p>
        )
      })}
    </div>
  )
}

export function UpdateDialog({
  open,
  onOpenChange,
  info,
}: {
  readonly open: boolean
  readonly onOpenChange: (open: boolean) => void
  readonly info: UpdateInfo
}) {
  if (!info.latest) return null
  const isMajor =
    info.latest.version.replace(/^v/, "").split(".")[0] !==
    info.current.replace(/^v/, "").split(".")[0]

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ArrowUpCircle className="h-5 w-5 text-red-500" />
            {info.latest.version} is available
          </DialogTitle>
          <DialogDescription>
            You are running v{info.current.replace(/^v/, "")}.
            {isMajor && (
              <span className="mt-1 block font-medium text-red-500">
                This is a major release — read the notes before upgrading.
              </span>
            )}
          </DialogDescription>
        </DialogHeader>

        <NotesLines text={info.latest.highlights} />

        <div className="flex flex-col gap-1.5">
          <span className="text-xs font-medium">To update</span>
          <pre className="overflow-x-auto rounded-md bg-muted p-2.5 text-[11px] leading-relaxed">
            {"docker compose -f docker-compose.community.yml pull nodaro\ndocker compose -f docker-compose.community.yml up -d nodaro"}
          </pre>
          <p className="text-xs text-muted-foreground">
            Back up first — migrations are forward-only, so the backup is the
            only road back. See the deployment guide&apos;s Backups section.
          </p>
        </div>

        <div className="flex justify-end gap-2">
          <Button size="sm" variant="ghost" onClick={() => onOpenChange(false)}>
            Later
          </Button>
          <Button
            size="sm"
            className="bg-[#ff0073] text-white hover:bg-[#e0005f]"
            onClick={() => window.open(info.latest!.url, "_blank", "noopener")}
          >
            Full release notes
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
