"use client"

import { useState } from "react"
import { ArrowUp, Check, X } from "lucide-react"
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog"
import type { UpdateInfo } from "@/hooks/use-update-check"

/**
 * The release dialog behind the sidebar's version indicator — founder design
 * (comp: "Update Dialog.dc.html", 2026-08-19). Three modes, one component:
 *
 * - "upgrade" (self-host): two columns — the changelog + release/compare
 *   links on the left; the two numbered steps on the right (BACK UP first,
 *   with a link to the published backup-&-restore guide, then pull+restart)
 *   and an "I have a backup from today" acknowledgment.
 * - "whats-new" (cloud): the changelog + release link only — cloud users
 *   never upgrade anything, they just see what shipped.
 * - "current" (self-host, on the newest release): the same changelog-only
 *   body, framed as "this is what you are running" — the answer to "what is
 *   in my version?" that the sidebar used to withhold once you were up to
 *   date (#869).
 */

const GUIDE_URL = "https://nodaroai.github.io/app.nodaro.ai/backup-restore"
const PUBLIC_REPO = "https://github.com/nodaroai/app.nodaro.ai"

const V = (v: string) => v.replace(/^v/, "")
/** A vX.Y.Z we can build GitHub links from — dev builds ("1.23.0-dev.abc") can't. */
const isRelease = (v: string) => /^v?\d+\.\d+\.\d+$/.test(v)

/** Release-notes markdown as plain lines — headings bolded, bullets kept.
 *  Deliberately not a markdown engine: the notes are ours (generated by the
 *  release pipeline) and links live behind the explicit buttons. */
function NotesLines({ text }: { readonly text: string }) {
  return (
    <div className="space-y-1 text-sm">
      {text.split("\n").map((line, i) => {
        const t = line.trim()
        if (!t) return null
        if (t.startsWith("##")) {
          return (
            <p key={i} className="pt-3 font-bold">
              {t.replace(/^#+\s*/, "")}
            </p>
          )
        }
        return (
          <p key={i} className="leading-relaxed text-muted-foreground">
            {t.replace(/^-\s*/, "– ")}
          </p>
        )
      })}
    </div>
  )
}

function StepCard({
  n,
  title,
  accent,
  done,
  children,
}: {
  readonly n: number
  readonly title: string
  readonly accent?: boolean
  readonly done?: boolean
  readonly children: React.ReactNode
}) {
  return (
    <div
      className={
        accent && !done
          ? "rounded-xl border border-[#ff0073]/40 bg-[#ff0073]/5 p-4"
          : "rounded-xl border p-4"
      }
    >
      <div className="flex items-start gap-3.5">
        <span
          className={
            accent && !done
              ? "flex h-6 w-6 flex-none items-center justify-center rounded-full bg-[#ff0073] text-[13px] font-bold text-white"
              : "flex h-6 w-6 flex-none items-center justify-center rounded-full border text-[13px] font-bold text-muted-foreground"
          }
        >
          {done ? <Check className="h-3.5 w-3.5" /> : n}
        </span>
        <div className="min-w-0 flex-1">
          <p className="font-bold">{title}</p>
          {children}
        </div>
      </div>
    </div>
  )
}

export function UpdateDialog({
  open,
  onOpenChange,
  info,
  mode = "upgrade",
}: {
  readonly open: boolean
  readonly onOpenChange: (open: boolean) => void
  readonly info: UpdateInfo
  readonly mode?: "upgrade" | "whats-new" | "current"
}) {
  const [backedUp, setBackedUp] = useState(false)
  if (!info.latest) return null
  const latest = info.latest
  const upgrade = mode === "upgrade"
  const isMajor = upgrade && V(latest.version).split(".")[0] !== V(info.current).split(".")[0]
  const compareUrl =
    upgrade && isRelease(info.current)
      ? `${PUBLIC_REPO}/compare/v${V(info.current)}...v${V(latest.version)}`
      : null

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className={upgrade ? "gap-0 p-0 sm:max-w-[860px]" : "gap-0 p-0 sm:max-w-lg"}
        showCloseButton={false}
      >
        {/* Header */}
        <div className="flex items-start gap-3.5 border-b px-7 py-5">
          <span className="mt-0.5 flex h-7 w-7 flex-none items-center justify-center rounded-full border-2 border-[#ff0073] text-[#ff0073]">
            <ArrowUp className="h-4 w-4" strokeWidth={3} />
          </span>
          <div className="min-w-0 flex-1">
            <DialogTitle className="text-xl font-bold tracking-tight">
              {upgrade
                ? `Upgrade to ${latest.version}`
                : mode === "current"
                  ? `What's in ${latest.version}`
                  : `What's new in ${latest.version}`}
            </DialogTitle>
            <p className="mt-0.5 text-sm text-muted-foreground">
              {upgrade
                ? `You are running v${V(info.current)} · two steps, about five minutes.`
                : mode === "current"
                  ? V(info.current) === V(latest.version)
                    ? "You are on the latest release — nothing to do."
                    : `You are running v${V(info.current)} · newest release is ${latest.version}.`
                  : "Just shipped to nodaro.ai — already live for you."}
              {isMajor && (
                <span className="mt-1 block font-medium text-red-500">
                  This is a major release — read the notes before upgrading.
                </span>
              )}
            </p>
          </div>
          <button
            type="button"
            aria-label="Close"
            onClick={() => onOpenChange(false)}
            className="flex-none text-muted-foreground transition-colors hover:text-foreground"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className={upgrade ? "grid sm:grid-cols-[1fr_1.2fr]" : ""}>
          {/* Changes */}
          <div className={upgrade ? "border-b px-7 py-5 sm:border-b-0 sm:border-r" : "px-7 py-5"}>
            <p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">
              Changes
            </p>
            <div className="mt-1 max-h-72 overflow-y-auto pr-1">
              <NotesLines text={latest.highlights} />
            </div>
            <div className="mt-5 grid gap-2 border-t pt-4 text-sm">
              <a
                href={latest.url}
                target="_blank"
                rel="noreferrer"
                className="text-[#ff0073] hover:underline"
              >
                Release {latest.version} on GitHub ↗
              </a>
              {compareUrl && (
                <a
                  href={compareUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="text-[#ff0073] hover:underline"
                >
                  Compare v{V(info.current)} → v{V(latest.version)} ↗
                </a>
              )}
            </div>
          </div>

          {/* Steps — upgrade mode only */}
          {upgrade && (
            <div className="grid content-start gap-3 bg-muted/30 px-6 py-5">
              <StepCard n={1} title="Back up your data" accent done={backedUp}>
                <p className="mt-1 text-sm leading-relaxed text-muted-foreground">
                  Migrations are forward-only — that backup is your only way
                  back to v{V(info.current)}.
                </p>
                <a
                  href={GUIDE_URL}
                  target="_blank"
                  rel="noreferrer"
                  className="mt-2 inline-block text-sm text-[#ff0073] hover:underline"
                >
                  Backup &amp; restore guide →
                </a>
              </StepCard>

              <StepCard n={2} title="Pull and restart">
                <pre className="mt-2.5 overflow-x-auto rounded-lg border bg-muted p-3 font-mono text-[12px] leading-relaxed">
                  {"docker compose -f docker-compose.community.yml pull nodaro\ndocker compose -f docker-compose.community.yml up -d nodaro"}
                </pre>
              </StepCard>

              <label className="flex cursor-pointer items-center gap-2.5 pl-1 text-sm text-muted-foreground">
                <input
                  type="checkbox"
                  checked={backedUp}
                  onChange={(e) => setBackedUp(e.target.checked)}
                  className="h-4 w-4 accent-[#ff0073]"
                />
                I have a backup from today
              </label>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-5 border-t px-7 py-4">
          <button
            type="button"
            onClick={() => onOpenChange(false)}
            className="text-sm font-semibold text-muted-foreground transition-colors hover:text-foreground"
          >
            {upgrade ? "Later" : "Close"}
          </button>
          <button
            type="button"
            onClick={() => window.open(latest.url, "_blank", "noopener")}
            className="rounded-full bg-[#ff0073] px-5 py-2.5 text-sm font-bold text-white transition-colors hover:bg-[#e0005f]"
          >
            Full release notes
          </button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
