const CREDIT_COSTS: Record<string, number> = {
  "generate-script": 2,
  "generate-image": 5,
  "image-to-video": 20,
  "video-to-video": 25,
  "text-to-video": 25,
  "text-to-speech": 3,
  "qa-check": 1,
  "combine-videos": 3,
  "merge-video-audio": 2,
  "add-captions": 3,
  "resize-video": 2,
  "trim-audio": 1,
  "mix-audio": 2,
  "adjust-volume": 1,
  "trim-video": 1,
  "speed-ramp": 2,
  "loop-video": 1,
  "fade-video": 1,
  "transcode-video": 1,
  "image-to-text": 1,
  "speech-to-video": 4,
  "sora-character": 5,
  "sub-workflow": 0,
  "social-media-format": 2,
  "instagram-post": 1,
  "tiktok-post": 1,
  "youtube-upload": 1,
  "linkedin-post": 1,
  "x-post": 1,
  "facebook-post": 1,
  "telegram-post": 1,
  "router": 0,
}

export function estimateWorkflowCredits(
  nodes: ReadonlyArray<{ type: string }>,
): number {
  return nodes.reduce((sum, node) => sum + (CREDIT_COSTS[node.type] ?? 0), 0)
}
