// Display labels for the studios' quick-preset chips. A preset id ("front",
// "fighting stance", "rotate-360") is DATA: it is sent to the backend variant
// generator and persisted as the asset's name, so it is never translated itself —
// only its caption is. The English caption IS the id (the English chip row reads
// exactly as it always did); other locales translate it. Missing id → the id
// renders verbatim (never blank);
// studio-shell/__tests__/preset-labels.test.ts fails when a *_PRESETS array gains
// an id with no label here.
import type { MessageKey, TFunction } from "@/lib/i18n"

const PRESET_LABEL_KEYS: Readonly<Record<string, MessageKey>> = {
  "neutral": "studioPreset.neutral",
  "smile": "studioPreset.smile",
  "angry": "studioPreset.angry",
  "surprised": "studioPreset.surprised",
  "sad": "studioPreset.sad",
  "talking": "studioPreset.talking",
  "laughing": "studioPreset.laughing",
  "disgusted": "studioPreset.disgusted",
  "fearful": "studioPreset.fearful",
  "smirk": "studioPreset.smirk",
  "crying": "studioPreset.crying",
  "walking": "studioPreset.walking",
  "running": "studioPreset.running",
  "waving": "studioPreset.waving",
  "sitting down": "studioPreset.sittingDown",
  "fighting stance": "studioPreset.fightingStance",
  "jumping": "studioPreset.jumping",
  "turning around": "studioPreset.turningAround",
  "dancing": "studioPreset.dancing",
  "talking gesture": "studioPreset.talkingGesture",
  "standing": "studioPreset.standing",
  "sitting": "studioPreset.sitting",
  "crouching": "studioPreset.crouching",
  "pointing": "studioPreset.pointing",
  "turning": "studioPreset.turning",
  "front": "studioPreset.front",
  "3/4 left": "studioPreset.threeQuarterLeft",
  "left profile": "studioPreset.leftProfile",
  "right profile": "studioPreset.rightProfile",
  "3/4 right": "studioPreset.threeQuarterRight",
  "back": "studioPreset.back",
  "side": "studioPreset.side",
  "top": "studioPreset.top",
  "three-quarter": "studioPreset.threeQuarter",
  "detail": "studioPreset.detail",
  "in-context": "studioPreset.inContext",
  "low-angle": "studioPreset.lowAngle",
  "high-angle": "studioPreset.highAngle",
  "wide": "studioPreset.wide",
  "medium": "studioPreset.medium",
  "closeup": "studioPreset.closeup",
  "aerial": "studioPreset.aerial",
  "eye-level": "studioPreset.eyeLevel",
  "bird's-eye": "studioPreset.birdsEye",
  "dutch tilt": "studioPreset.dutchTilt",
  "daylight": "studioPreset.daylight",
  "night": "studioPreset.night",
  "dramatic": "studioPreset.dramatic",
  "lying-down": "studioPreset.lyingDown",
  "alert": "studioPreset.alert",
  "playful": "studioPreset.playful",
  "aggressive": "studioPreset.aggressive",
  "idle-breathing": "studioPreset.idleBreathing",
  "walk-cycle": "studioPreset.walkCycle",
  "run-cycle": "studioPreset.runCycle",
  "head-turn": "studioPreset.headTurn",
  "tail-wag": "studioPreset.tailWag",
  "pounce": "studioPreset.pounce",
  "stretch": "studioPreset.stretch",
  "roar": "studioPreset.roar",
  "fly-loop": "studioPreset.flyLoop",
  "juvenile": "studioPreset.juvenile",
  "adult": "studioPreset.adult",
  "elder": "studioPreset.elder",
  "albino": "studioPreset.albino",
  "melanistic": "studioPreset.melanistic",
  "battle-scarred": "studioPreset.battleScarred",
  "majestic": "studioPreset.majestic",
  "fluffy": "studioPreset.fluffy",
  "sleek": "studioPreset.sleek",
  "soft natural": "studioPreset.softNatural",
  "harsh sunlight": "studioPreset.harshSunlight",
  "golden": "studioPreset.golden",
  "blue hour": "studioPreset.blueHour",
  "neon": "studioPreset.neon",
  "candlelit": "studioPreset.candlelit",
  "cinematic": "studioPreset.cinematic",
  "dramatic chiaroscuro": "studioPreset.dramaticChiaroscuro",
  "slow dolly-in": "studioPreset.slowDollyIn",
  "slow pan-left": "studioPreset.slowPanLeft",
  "slow pan-right": "studioPreset.slowPanRight",
  "push up": "studioPreset.pushUp",
  "drone fly-over": "studioPreset.droneFlyOver",
  "gentle drift": "studioPreset.gentleDrift",
  "parallax": "studioPreset.parallax",
  "static atmospheric": "studioPreset.staticAtmospheric",
  "spring": "studioPreset.spring",
  "summer": "studioPreset.summer",
  "autumn": "studioPreset.autumn",
  "winter": "studioPreset.winter",
  "dawn": "studioPreset.dawn",
  "morning": "studioPreset.morning",
  "noon": "studioPreset.noon",
  "afternoon": "studioPreset.afternoon",
  "golden hour": "studioPreset.goldenHour",
  "dusk": "studioPreset.dusk",
  "midnight": "studioPreset.midnight",
  "clear": "studioPreset.clear",
  "cloudy": "studioPreset.cloudy",
  "light rain": "studioPreset.lightRain",
  "heavy rain": "studioPreset.heavyRain",
  "storm": "studioPreset.storm",
  "snow": "studioPreset.snow",
  "blizzard": "studioPreset.blizzard",
  "fog": "studioPreset.fog",
  "mist": "studioPreset.mist",
  "rotate-360": "studioPreset.rotate360",
  "hover": "studioPreset.hover",
  "spin-slow": "studioPreset.spinSlow",
  "pulse": "studioPreset.pulse",
  "drift": "studioPreset.drift",
  "dolly-around": "studioPreset.dollyAround",
  "push-in": "studioPreset.pushIn",
  "drone-orbit": "studioPreset.droneOrbit",
  // Object Studio (ids come from @nodaro/prompts OBJECT_ASSET_PRESETS)
  "exploded": "studioPreset.exploded",
  "perspective": "studioPreset.perspective",
  "wood": "studioPreset.wood",
  "metal": "studioPreset.metal",
  "glass": "studioPreset.glass",
  "plastic": "studioPreset.plastic",
  "fabric": "studioPreset.fabric",
  "stone": "studioPreset.stone",
  "ceramic": "studioPreset.ceramic",
  "leather": "studioPreset.leather",
  "paper": "studioPreset.paper",
  "gold": "studioPreset.gold",
  "silver": "studioPreset.silver",
  "copper": "studioPreset.copper",
  "marble": "studioPreset.marble",
  "clean": "studioPreset.clean",
  "weathered": "studioPreset.weathered",
  "damaged": "studioPreset.damaged",
  "ornate": "studioPreset.ornate",
  "minimal": "studioPreset.minimal",
  "broken": "studioPreset.broken",
  "antique": "studioPreset.antique",
  "futuristic": "studioPreset.futuristic",
  "holographic": "studioPreset.holographic",
  "dirty": "studioPreset.dirty",
  "polished": "studioPreset.polished",
}

export function hasPresetLabel(id: string): boolean {
  return id in PRESET_LABEL_KEYS
}

/** The caption for a preset chip in the current language; the id itself when it has no label. */
export function presetLabel(t: TFunction, id: string): string {
  const key = PRESET_LABEL_KEYS[id]
  return key ? t(key) : id
}
