import { describe, it, expect } from "vitest"
import {
  NODARO_LOAD_VIDEO,
  NODARO_LOAD_TIMELINE,
  NODARO_IMPORT_FILES,
  NODARO_RESET_PROJECT,
  FREECUT_READY,
  FREECUT_EXPORT_COMPLETE,
  FREECUT_EXPORT_PROGRESS,
  FREECUT_REQUEST_IMPORT,
} from "../freecut-protocol.js"

describe("freecut protocol constants", () => {
  it("pins the wire strings the fork mirrors", () => {
    expect({
      NODARO_LOAD_VIDEO,
      NODARO_LOAD_TIMELINE,
      NODARO_IMPORT_FILES,
      NODARO_RESET_PROJECT,
      FREECUT_READY,
      FREECUT_EXPORT_COMPLETE,
      FREECUT_EXPORT_PROGRESS,
      FREECUT_REQUEST_IMPORT,
    }).toEqual({
      NODARO_LOAD_VIDEO: "NODARO_LOAD_VIDEO",
      NODARO_LOAD_TIMELINE: "NODARO_LOAD_TIMELINE",
      NODARO_IMPORT_FILES: "NODARO_IMPORT_FILES",
      NODARO_RESET_PROJECT: "NODARO_RESET_PROJECT",
      FREECUT_READY: "FREECUT_READY",
      FREECUT_EXPORT_COMPLETE: "FREECUT_EXPORT_COMPLETE",
      FREECUT_EXPORT_PROGRESS: "FREECUT_EXPORT_PROGRESS",
      FREECUT_REQUEST_IMPORT: "FREECUT_REQUEST_IMPORT",
    })
  })
})
