/**
 * Per-node-type list of field names eligible for fieldMappings resolution.
 * Text fields also participate in {} injection when the resolver sees a
 * string value containing {} markers; non-text fields just receive the
 * mapped source's value verbatim.
 */
export const NODE_MAPPABLE_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "generate-image":      ["prompt", "style", "negativePrompt", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "edit-image":          ["prompt", "style", "negativePrompt", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "image-to-image":      ["prompt", "style", "negativePrompt", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "modify-image":        ["prompt", "style", "negativePrompt", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "text-to-video":       ["prompt", "negativePrompt", "cameraMotion", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "image-to-video":      ["prompt", "cameraMotion", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "video-to-video":      ["prompt", "cameraMotion", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "text-to-speech":      ["directText"],
  "lip-sync":            ["prompt"],
  "generate-music":      ["prompt", "lyrics", "genre", "mood"],
  "text-to-audio":       ["prompt"],
  "suno-generate":       ["prompt", "lyrics", "style", "title", "negativeStyle"],
  "suno-cover":          ["prompt", "lyrics", "style", "title", "negativeStyle"],
  "suno-extend":         ["prompt", "style", "title"],
  "suno-lyrics":         ["prompt"],
  "suno-replace-section":["prompt", "tags", "title"],
  "suno-style-boost":    ["content"],
  "suno-upload-extend":  ["prompt", "style", "title"],
  "suno-mashup":         ["style", "title", "negativeStyle"],
  "voice-remix":         ["voiceDescription", "text"],
  "voice-design":        ["voiceDescription", "text"],
  "forced-alignment":    ["transcript"],
  "ai-writer":           ["systemPrompt", "userInput"],
  "llm-chat":            ["systemPrompt", "userInput"],
  "video-composer":      ["compositionPrompt"],
  "after-effects":       ["effectPrompt"],
  "lottie-overlay":      ["overlayPrompt"],
  "3d-title":            ["titlePrompt"],
  "motion-graphics":     ["motionPrompt"],
  "generate-script":     ["styleGuide"],
  "speech-to-video":     ["prompt", "negativePrompt", "cameraMotion", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "extend-video":        ["prompt", "cameraMotion", "lens", "cameraFormat", "colorLook", "atmosphere"],
  "motion-transfer":     ["prompt"],
  "image-to-text":       ["customPrompt"],
  "instagram-post":      ["caption", "title"],
  "tiktok-post":         ["caption", "title"],
  "youtube-upload":      ["caption", "title"],
  "linkedin-post":       ["caption", "title"],
  "x-post":              ["caption", "title"],
  "facebook-post":       ["caption", "title"],
  "telegram-post":       ["caption", "title"],
  "save-to-storage":     ["filename"],
  "webhook-output":      ["url"],
  "character":           ["characterName", "description", "baseOutfit"],
  "face":                ["faceName", "description"],
  "object":              ["objectName", "description"],
  "location":            ["locationName", "description"],
  "web-scrape":          ["query", "url", "target"],
}
