import type { SupabaseClient } from "@supabase/supabase-js"
import type { SceneNodeData } from "@nodaro/shared"
import { ensureStageRow, failStage } from "../stage-utils.js"
import { pipelineEvents } from "../events.js"
import { transitionStageEntityNodesAndEmit } from "../depends-on.js"
import { settledWithLimit } from "../../../lib/settled-with-limit.js"
import { runSceneInternalPipeline } from "../scene-internal-pipeline.js"

export interface RunAnimateAudioEditStageArgs {
  supabase: SupabaseClient
  pipelineId: string
  userId: string
  userTier: string
}

/**
 * Cross-scene fan-out concurrency caps for Stage 7.
 *
 *   sequential — one scene at a time (per §5.13.4: continuity gating runs the
 *                Image Critic between shots within each scene, which needs the
 *                prior scene's last_frame chain to be complete before the next
 *                scene starts).
 *   parallel   — up to 3 scenes in flight. Matches the rate-limit headroom we
 *                have for KIE/Replicate tier-1 image+video calls when each
 *                scene already fans out its shots in parallel (×4 per scene).
 */
const SCENE_CONCURRENCY_SEQUENTIAL = 1
const SCENE_CONCURRENCY_PARALLEL = 3

/**
 * Stage 7 (`animate_audio_edit`). For every approved scene entity from Stage 6,
 * drive the SceneNode internal pipeline (`runSceneInternalPipeline`) which:
 *   1. Reads each shot's keyframe (generated by Stage 6)
 *   2. Animates each shot via the configured i2v provider
 *   3. (sequential mode) extracts last_frame + runs the Image Critic
 *      continuity_break gate between shots
 *   4. Synthesizes dialogue audio for shots with `dialogue_line`
 *   5. (when lipsync_enabled) lipsyncs audio onto the animated clip
 *   6. Combines per-shot clips into the scene's composite_video
 *
 * The mode + lipsync flags live on `pipelines.config` (migration 134 makes
 * the column NOT NULL DEFAULT '{}'):
 *   shot_generation_mode: "parallel" (default) | "sequential"
 *   lipsync_enabled:      true (default) | false
 *
 * `runImageCritic = mode === "sequential"` — parallel mode skips the Stage 7b
 * pre-gate entirely (per §5.13.4 — parallel shots have no last_frame chain to
 * continuity-check against).
 *
 * On success: per-scene `composite_video_asset_id` + `composite_video_url`
 * are written to `pipeline_entities.metadata.scene_node_data`, the canvas
 * SceneNodes flip to `pipeline_owned_awaiting_approval`, and the stage is
 * marked `awaiting_approval`. Stage 8 (post_merge) runs after the user
 * approves the assembled scene composites.
 *
 * On any scene failure: the stage is failed with a structured count. The
 * runner already returns `{ ok: false, reason }` for known failure modes
 * (animate, combine, continuity_break) — we surface the count, not the
 * per-scene reasons, so the failure row stays compact.
 */
export async function runAnimateAudioEditStage(
  args: RunAnimateAudioEditStageArgs,
): Promise<void> {
  const { supabase, pipelineId, userId } = args

  const stageId = await ensureStageRow(supabase, pipelineId, "animate_audio_edit", 7)

  // Re-entrancy guard — same pattern as Stage 6. The engine driver won't
  // re-invoke us when the stage is awaiting_approval/approved/completed/failed,
  // but defend against partial retries landing here anyway.
  const { data: existingStage } = await supabase
    .from("pipeline_stages")
    .select("status")
    .eq("id", stageId)
    .maybeSingle()
  if (
    existingStage?.status === "awaiting_approval" ||
    existingStage?.status === "approved" ||
    existingStage?.status === "completed"
  ) {
    return
  }

  // 1. Read mode + lipsync flags off pipelines.config (migration 134 sets the
  //    default to '{}' so the row is never null). Default to parallel +
  //    lipsync enabled when the keys are missing.
  const { data: pipelineRow } = await supabase
    .from("pipelines")
    .select("config")
    .eq("id", pipelineId)
    .single()
  const config = (pipelineRow?.config ?? {}) as {
    shot_generation_mode?: "parallel" | "sequential"
    lipsync_enabled?: boolean
  }
  const mode: "parallel" | "sequential" = config.shot_generation_mode ?? "parallel"
  const lipSyncEnabled = config.lipsync_enabled ?? true
  const runImageCritic = mode === "sequential"

  // 2. Load scene entities in canvas order.
  const { data: scenes, error: scenesErr } = await supabase
    .from("pipeline_entities")
    .select("id, entity_key, metadata")
    .eq("pipeline_id", pipelineId)
    .eq("entity_type", "scene")
    .order("entity_key", { ascending: true })
  if (scenesErr) {
    await failStage(supabase, stageId, `load_scenes: ${scenesErr.message}`)
    return
  }
  if (!scenes || scenes.length === 0) {
    await failStage(supabase, stageId, "no_scenes")
    return
  }

  // 3. Mark every materialized SceneNode `pipeline_owned_running` — UI hint
  //    that animation is in flight.
  await transitionStageEntityNodesAndEmit(
    supabase,
    pipelineId,
    "scene",
    "pipeline_owned_running",
    "animate_audio_edit",
  )

  // 4. Fan out scenes. Per-scene work happens inside runSceneInternalPipeline
  //    which itself fans shots out (parallel mode) or sequentially chains
  //    them (sequential mode).
  const sceneConcurrency =
    mode === "sequential" ? SCENE_CONCURRENCY_SEQUENTIAL : SCENE_CONCURRENCY_PARALLEL
  const ctx = { supabase, pipelineId, userId }
  const tasks = scenes.map((scene) => async () => {
    const sceneEntity = scene as {
      id: string
      entity_key: string
      metadata: Record<string, unknown> | null
    }
    const result = await runSceneInternalPipeline(ctx, sceneEntity, {
      mode,
      lipSyncEnabled,
      runImageCritic,
    })

    // On success, persist composite_video_* + per-shot fields
    // (video_url/asset_id, last_frame_url/asset_id) back to the scene
    // entity's metadata.scene_node_data so Stage 8, the canvas SceneNode
    // renderer, AND helpers like `fix_continuity` (which reads
    // `prior.last_frame_url`) can read them without a join.
    if (result.ok && result.composite_video_url) {
      const prevSceneNodeData =
        (sceneEntity.metadata as Record<string, unknown> | null)?.scene_node_data as
          | SceneNodeData
          | undefined
      const nextShots = (prevSceneNodeData?.shots ?? []).map((s) => {
        const r = result.per_shot_results?.find((x) => x.shot_id === s.shot_id)
        if (!r) return s
        return {
          ...s,
          video_asset_id: r.video_asset_id ?? s.video_asset_id,
          video_url: r.video_url ?? s.video_url,
          last_frame_asset_id: r.last_frame_asset_id ?? s.last_frame_asset_id,
          last_frame_url: r.last_frame_url ?? s.last_frame_url,
        }
      })
      const nextSceneNodeData = {
        ...(prevSceneNodeData ?? {}),
        shots: nextShots,
        composite_video_asset_id: result.composite_video_asset_id,
        composite_video_url: result.composite_video_url,
      }
      await supabase
        .from("pipeline_entities")
        .update({
          metadata: {
            ...(sceneEntity.metadata ?? {}),
            scene_node_data: nextSceneNodeData,
          },
        })
        .eq("id", sceneEntity.id)
    }

    return result
  })

  // Disable failFast — we want to see how many scenes failed, not bail on the
  // first one. Each scene's failures are caught inside the runner and
  // surfaced as `{ ok: false, reason }`.
  const results = await settledWithLimit(tasks, sceneConcurrency, undefined, false)

  const failed = results.filter(
    (r) =>
      r.status === "rejected" ||
      (r.status === "fulfilled" && r.value.ok === false),
  )
  if (failed.length > 0) {
    await failStage(
      supabase,
      stageId,
      `${failed.length} scenes failed`,
    )
    return
  }

  // 5. Transition canvas SceneNodes to awaiting_approval + flip stage status.
  await transitionStageEntityNodesAndEmit(
    supabase,
    pipelineId,
    "scene",
    "pipeline_owned_awaiting_approval",
    "animate_audio_edit",
  )
  await supabase
    .from("pipeline_stages")
    .update({ status: "awaiting_approval" })
    .eq("id", stageId)
  pipelineEvents.publish({
    type: "stage:status",
    pipelineId,
    stageName: "animate_audio_edit",
    status: "awaiting_approval",
  })
}
