/**
 * Render the backend-internal table of the sliders each node type can expose
 * in a published app, from NODE_DEFINITIONS `exposableFields`.
 *
 * The descriptors live in `frontend/src/types/nodes.ts`; the backend has no
 * typed view of them, so the app-input schema `get_app_inputs` and SDK flat
 * inputs read (lib/mcp/extract-app-inputs.ts) described every exposed slider
 * as free text. This module is regenerated by `gen-skills` and drift-checked in
 * CI like `node-handles.ts`. Only slider keys and their UI bounds are emitted —
 * never `creditCost` or any pricing-adjacent field.
 *
 * Output is sorted and carries no timestamp, so a run that changes nothing
 * writes nothing.
 */
import type { ExposableSliderDef, NodeDef } from "./parse-node-definitions.js"

function renderSlider(s: ExposableSliderDef): string {
  const bounds = (["min", "max", "step"] as const)
    .filter((b) => s[b] !== undefined)
    .map((b) => `${b}: ${s[b]}`)
  return `${JSON.stringify(s.key)}: { ${bounds.join(", ")} }`
}

export function renderExposableSlidersModule(defs: ReadonlyArray<NodeDef>): string {
  const rows = [...defs]
    .filter((d) => d.sliders.length > 0)
    .sort((a, b) => a.type.localeCompare(b.type))
    .map((d) => `  ${JSON.stringify(d.type)}: { ${d.sliders.map(renderSlider).join(", ")} },`)
  return [
    "// GENERATED by `npm run gen:skills` (backend/scripts/gen-skills.ts) from",
    "// frontend/src/types/nodes.ts NODE_DEFINITIONS exposableFields — do NOT hand-edit.",
    "// `gen:skills:check` fails CI on drift. Slider keys and UI bounds only; no pricing fields.",
    "",
    "export interface ExposableSliderSpec {",
    "  readonly min?: number",
    "  readonly max?: number",
    "  readonly step?: number",
    "}",
    "",
    "/** Node type → exposed field key (the descriptor's current key) → slider bounds. */",
    "export const EXPOSABLE_SLIDERS: Readonly<Record<string, Readonly<Record<string, ExposableSliderSpec>>>> = {",
    ...rows,
    "}",
    "",
  ].join("\n")
}
