/**
 * Render the backend-internal node-handles map from NODE_DEFINITIONS.
 *
 * Handle names live in `frontend/src/types/nodes.ts`; the backend has no
 * typed view of them, so a server-side writer (the Workflow Copilot's
 * `edit_workflow`) could not tell a real handle from a hallucinated one. This
 * module is regenerated by `gen-skills` and drift-checked in CI like every
 * other generated artifact. Only `inputs`/`outputs` are emitted — never
 * `creditCost` or any pricing-adjacent field.
 *
 * Output is sorted and carries no timestamp, so a run that changes nothing
 * writes nothing.
 */
import type { NodeDef } from "./parse-node-definitions.js"

export function renderNodeHandlesModule(defs: ReadonlyArray<NodeDef>): string {
  const sorted = [...defs].sort((a, b) => a.type.localeCompare(b.type))
  const rows = sorted.map((d) => {
    const inputs = d.inputs.map((h) => JSON.stringify(h)).join(", ")
    const outputs = d.outputs.map((h) => JSON.stringify(h)).join(", ")
    return `  ${JSON.stringify(d.type)}: { inputs: [${inputs}], outputs: [${outputs}] },`
  })
  return [
    "// GENERATED by `npm run gen:skills` (backend/scripts/gen-skills.ts) from",
    "// frontend/src/types/nodes.ts NODE_DEFINITIONS — do NOT hand-edit.",
    "// `gen:skills:check` fails CI on drift. Handle ids only; no pricing fields.",
    "",
    "export interface NodeHandleSpec {",
    "  readonly inputs: ReadonlyArray<string>",
    "  readonly outputs: ReadonlyArray<string>",
    "}",
    "",
    "export const NODE_HANDLES: Readonly<Record<string, NodeHandleSpec>> = {",
    ...rows,
    "}",
    "",
  ].join("\n")
}
