***REDACTED-OSS-SCRUB***
--
***REDACTED-OSS-SCRUB***
-- the true 0%-base (ceil(rawProviderUSD / 0.02)). The markup is now applied
-- exactly once, at reserve, by getModelCreditCostFromDB. Combined with the
-- commit-reserved change in workers/shared.ts (commit charges the reserved tier
-- unless meteredCost=true), this makes reserved == committed for every fixed/
-- composite provider — eliminating the double-markup-then-refund masking and the
-- composite/Replicate-flat under-charge leaks.
--
-- MUST ship atomically with the STATIC_CREDIT_COSTS edits + the commit-reserved
-- code (else markup-baked rows double-charge during the window). Only the 175
-- markup-baked / double-rounded ids change; already-0%-base rows (seedance-2
-- matrix, MMAudio, kling-avatar ladder) are untouched. The 156 "unclear"
-- LLM/FFmpeg/voice rows already commit-reserved and are a separate pricing pass.
--
***REDACTED-OSS-SCRUB***
***REDACTED-OSS-SCRUB***
--
-- Idempotent: pure UPDATEs to absolute values.

UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'elevenlabs-dialogue';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'elevenlabs-multilingual';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'elevenlabs-v3';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'flux-2-max';
UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'flux-2-max:1ref';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'flux-2-max:2ref';
UPDATE model_pricing SET credit_cost = 7 WHERE model_identifier = 'flux-2-max:3ref';
UPDATE model_pricing SET credit_cost = 8 WHERE model_identifier = 'flux-2-max:4ref';
UPDATE model_pricing SET credit_cost = 10 WHERE model_identifier = 'flux-2-max:5ref';
UPDATE model_pricing SET credit_cost = 11 WHERE model_identifier = 'flux-2-max:6ref';
UPDATE model_pricing SET credit_cost = 13 WHERE model_identifier = 'flux-2-max:7ref';
UPDATE model_pricing SET credit_cost = 14 WHERE model_identifier = 'flux-2-max:8ref';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'flux-2-pro';
UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'flux-flex';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'flux-flex:2K';
UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'flux-i2i';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'flux-i2i:2K';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'flux-lora-character';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'flux-pro-i2i:2K';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'flux:2K';
UPDATE model_pricing SET credit_cost = 23 WHERE model_identifier = 'gemini-omni-video';
UPDATE model_pricing SET credit_cost = 45 WHERE model_identifier = 'gemini-omni-video:10';
UPDATE model_pricing SET credit_cost = 23 WHERE model_identifier = 'gemini-omni-video:4';
UPDATE model_pricing SET credit_cost = 75 WHERE model_identifier = 'gemini-omni-video:4k:10';
UPDATE model_pricing SET credit_cost = 53 WHERE model_identifier = 'gemini-omni-video:4k:4';
UPDATE model_pricing SET credit_cost = 60 WHERE model_identifier = 'gemini-omni-video:4k:6';
UPDATE model_pricing SET credit_cost = 68 WHERE model_identifier = 'gemini-omni-video:4k:8';
UPDATE model_pricing SET credit_cost = 90 WHERE model_identifier = 'gemini-omni-video:4k:vref';
UPDATE model_pricing SET credit_cost = 30 WHERE model_identifier = 'gemini-omni-video:6';
UPDATE model_pricing SET credit_cost = 38 WHERE model_identifier = 'gemini-omni-video:8';
UPDATE model_pricing SET credit_cost = 60 WHERE model_identifier = 'gemini-omni-video:vref';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'generate-music';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'gpt-image-2';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'gpt-image-2-i2i';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'gpt-image-2-i2i:2K';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'gpt-image-2-i2i:4K';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'gpt-image-2:2K';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'gpt-image-2:4K';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'gpt-image-i2i:high';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'gpt-image:high';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'grok';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'grok-i2i';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'grok-i2v';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'grok-upscale';
UPDATE model_pricing SET credit_cost = 8 WHERE model_identifier = 'hailuo-2.3';
UPDATE model_pricing SET credit_cost = 8 WHERE model_identifier = 'hailuo-standard';
UPDATE model_pricing SET credit_cost = 13 WHERE model_identifier = 'happyhorse';
UPDATE model_pricing SET credit_cost = 20 WHERE model_identifier = 'happyhorse-edit';
UPDATE model_pricing SET credit_cost = 13 WHERE model_identifier = 'happyhorse-i2v';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'happyhorse-ref2v';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'ideogram-edit';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'ideogram-edit:QUALITY';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'ideogram-edit:TURBO';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'ideogram-reframe';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'ideogram-reframe:QUALITY';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'ideogram-reframe:TURBO';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'ideogram-remix';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'ideogram-remix:QUALITY';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'ideogram-remix:TURBO';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'imagen4';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'imagen4-fast';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'imagen4-ultra';
UPDATE model_pricing SET credit_cost = 25 WHERE model_identifier = 'kling-3-omni';
UPDATE model_pricing SET credit_cost = 50 WHERE model_identifier = 'kling-3-omni:10s';
UPDATE model_pricing SET credit_cost = 75 WHERE model_identifier = 'kling-3-omni:15s';
UPDATE model_pricing SET credit_cost = 25 WHERE model_identifier = 'kling-3-omni:5s';
UPDATE model_pricing SET credit_cost = 50 WHERE model_identifier = 'kling-3.0';
UPDATE model_pricing SET credit_cost = 30 WHERE model_identifier = 'kling-3.0-motion';
UPDATE model_pricing SET credit_cost = 50 WHERE model_identifier = 'kling-3.0-motion:1080p';
UPDATE model_pricing SET credit_cost = 50 WHERE model_identifier = 'kling-3.0-motion:1080p:10s';
UPDATE model_pricing SET credit_cost = 75 WHERE model_identifier = 'kling-3.0-motion:1080p:15s';
UPDATE model_pricing SET credit_cost = 150 WHERE model_identifier = 'kling-3.0-motion:1080p:30s';
UPDATE model_pricing SET credit_cost = 25 WHERE model_identifier = 'kling-3.0-motion:1080p:5s';
UPDATE model_pricing SET credit_cost = 30 WHERE model_identifier = 'kling-3.0-motion:10s';
UPDATE model_pricing SET credit_cost = 45 WHERE model_identifier = 'kling-3.0-motion:15s';
UPDATE model_pricing SET credit_cost = 90 WHERE model_identifier = 'kling-3.0-motion:30s';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'kling-3.0-motion:5s';
UPDATE model_pricing SET credit_cost = 68 WHERE model_identifier = 'kling-3.0:10s';
UPDATE model_pricing SET credit_cost = 100 WHERE model_identifier = 'kling-3.0:10s:audio';
UPDATE model_pricing SET credit_cost = 102 WHERE model_identifier = 'kling-3.0:15s';
UPDATE model_pricing SET credit_cost = 150 WHERE model_identifier = 'kling-3.0:15s:audio';
UPDATE model_pricing SET credit_cost = 34 WHERE model_identifier = 'kling-3.0:5s';
UPDATE model_pricing SET credit_cost = 50 WHERE model_identifier = 'kling-3.0:5s:audio';
UPDATE model_pricing SET credit_cost = 40 WHERE model_identifier = 'kling-master';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'kling-motion';
UPDATE model_pricing SET credit_cost = 11 WHERE model_identifier = 'kling-turbo';
UPDATE model_pricing SET credit_cost = 55 WHERE model_identifier = 'kling:10s:audio';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'kontext-multi';
UPDATE model_pricing SET credit_cost = 18 WHERE model_identifier = 'ltx-2.3-fast';
UPDATE model_pricing SET credit_cost = 30 WHERE model_identifier = 'ltx-2.3-fast:1080p:10s';
UPDATE model_pricing SET credit_cost = 36 WHERE model_identifier = 'ltx-2.3-fast:1080p:12s';
UPDATE model_pricing SET credit_cost = 42 WHERE model_identifier = 'ltx-2.3-fast:1080p:14s';
UPDATE model_pricing SET credit_cost = 48 WHERE model_identifier = 'ltx-2.3-fast:1080p:16s';
UPDATE model_pricing SET credit_cost = 54 WHERE model_identifier = 'ltx-2.3-fast:1080p:18s';
UPDATE model_pricing SET credit_cost = 60 WHERE model_identifier = 'ltx-2.3-fast:1080p:20s';
UPDATE model_pricing SET credit_cost = 18 WHERE model_identifier = 'ltx-2.3-fast:1080p:6s';
UPDATE model_pricing SET credit_cost = 24 WHERE model_identifier = 'ltx-2.3-fast:1080p:8s';
UPDATE model_pricing SET credit_cost = 60 WHERE model_identifier = 'ltx-2.3-fast:2k:10s';
UPDATE model_pricing SET credit_cost = 36 WHERE model_identifier = 'ltx-2.3-fast:2k:6s';
UPDATE model_pricing SET credit_cost = 48 WHERE model_identifier = 'ltx-2.3-fast:2k:8s';
UPDATE model_pricing SET credit_cost = 120 WHERE model_identifier = 'ltx-2.3-fast:4k:10s';
UPDATE model_pricing SET credit_cost = 72 WHERE model_identifier = 'ltx-2.3-fast:4k:6s';
UPDATE model_pricing SET credit_cost = 96 WHERE model_identifier = 'ltx-2.3-fast:4k:8s';
UPDATE model_pricing SET credit_cost = 24 WHERE model_identifier = 'ltx-2.3-pro';
UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'ltx-2.3-pro-extend:per-second';
UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'ltx-2.3-pro-retake:per-second';
UPDATE model_pricing SET credit_cost = 40 WHERE model_identifier = 'ltx-2.3-pro:1080p:10s';
UPDATE model_pricing SET credit_cost = 24 WHERE model_identifier = 'ltx-2.3-pro:1080p:6s';
UPDATE model_pricing SET credit_cost = 32 WHERE model_identifier = 'ltx-2.3-pro:1080p:8s';
UPDATE model_pricing SET credit_cost = 80 WHERE model_identifier = 'ltx-2.3-pro:2k:10s';
UPDATE model_pricing SET credit_cost = 48 WHERE model_identifier = 'ltx-2.3-pro:2k:6s';
UPDATE model_pricing SET credit_cost = 64 WHERE model_identifier = 'ltx-2.3-pro:2k:8s';
UPDATE model_pricing SET credit_cost = 160 WHERE model_identifier = 'ltx-2.3-pro:4k:10s';
UPDATE model_pricing SET credit_cost = 96 WHERE model_identifier = 'ltx-2.3-pro:4k:6s';
UPDATE model_pricing SET credit_cost = 128 WHERE model_identifier = 'ltx-2.3-pro:4k:8s';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'minimax';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'motion-transfer';
UPDATE model_pricing SET credit_cost = 23 WHERE model_identifier = 'motion-transfer:1080p';
UPDATE model_pricing SET credit_cost = 23 WHERE model_identifier = 'motion-transfer:1080p:10s';
UPDATE model_pricing SET credit_cost = 34 WHERE model_identifier = 'motion-transfer:1080p:15s';
UPDATE model_pricing SET credit_cost = 68 WHERE model_identifier = 'motion-transfer:1080p:30s';
UPDATE model_pricing SET credit_cost = 12 WHERE model_identifier = 'motion-transfer:1080p:5s';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'motion-transfer:10s';
UPDATE model_pricing SET credit_cost = 23 WHERE model_identifier = 'motion-transfer:15s';
UPDATE model_pricing SET credit_cost = 45 WHERE model_identifier = 'motion-transfer:30s';
UPDATE model_pricing SET credit_cost = 8 WHERE model_identifier = 'motion-transfer:5s';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'nano-banana';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'nano-banana-2:4K';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'nano-banana-pro';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'nano-banana-pro:4K';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'qwen-i2i';
UPDATE model_pricing SET credit_cost = 13 WHERE model_identifier = 'roop-face-swap';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'runway-kie';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'seedream';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'seedream-edit';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'speech-to-video';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'speech-to-video:580p';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'speech-to-video:720p';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-add-instrumental';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-add-vocals';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-cover';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-extend';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-generate';
UPDATE model_pricing SET credit_cost = 1 WHERE model_identifier = 'suno-lyrics';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-mashup';
UPDATE model_pricing SET credit_cost = 13 WHERE model_identifier = 'suno-separate-stem';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-upload-extend';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-v5';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'suno-v5_5';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'text-to-audio';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'text-to-speech';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'topaz-image-upscale';
UPDATE model_pricing SET credit_cost = 5 WHERE model_identifier = 'topaz-image-upscale:4K';
UPDATE model_pricing SET credit_cost = 10 WHERE model_identifier = 'topaz-image-upscale:8K';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'transcribe';
UPDATE model_pricing SET credit_cost = 63 WHERE model_identifier = 'veo3';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'veo3.1';
UPDATE model_pricing SET credit_cost = 17 WHERE model_identifier = 'veo3.1:1080p';
UPDATE model_pricing SET credit_cost = 8 WHERE model_identifier = 'veo3_lite';
UPDATE model_pricing SET credit_cost = 9 WHERE model_identifier = 'veo3_lite:1080p';
UPDATE model_pricing SET credit_cost = 15 WHERE model_identifier = 'video-upscale';
UPDATE model_pricing SET credit_cost = 18 WHERE model_identifier = 'wan';
UPDATE model_pricing SET credit_cost = 2 WHERE model_identifier = 'wan-2.7';
UPDATE model_pricing SET credit_cost = 19 WHERE model_identifier = 'wan-2.7-i2v';
UPDATE model_pricing SET credit_cost = 3 WHERE model_identifier = 'wan-2.7-pro';
UPDATE model_pricing SET credit_cost = 6 WHERE model_identifier = 'wan-2.7-pro:2K';
UPDATE model_pricing SET credit_cost = 12 WHERE model_identifier = 'wan-2.7-pro:4K';
UPDATE model_pricing SET credit_cost = 19 WHERE model_identifier = 'wan-2.7-t2v';
UPDATE model_pricing SET credit_cost = 4 WHERE model_identifier = 'wan-2.7:2K';
UPDATE model_pricing SET credit_cost = 8 WHERE model_identifier = 'wan-2.7:4K';
UPDATE model_pricing SET credit_cost = 18 WHERE model_identifier = 'wan-i2v';
UPDATE model_pricing SET credit_cost = 27 WHERE model_identifier = 'wan-t2v';
UPDATE model_pricing SET credit_cost = 10 WHERE model_identifier = 'wan-turbo';
UPDATE model_pricing SET credit_cost = 20 WHERE model_identifier = 'wan-turbo-t2v';
