-- Named boards for the remaining entity kinds — locations + objects — mirroring
-- characters.boards (migration 212); numbered 214 because dev holds 213_motion_graphics_lottie_pricing: dense reference sheets generated by Studio
-- via the location-board / product-board factory presets, one per variant/mood,
-- shaped [{ "name": "...", "url": "https://..." }]. First-class buckets so the
-- community pipeline carries them: publish snapshots them (R2-copied via the
-- adapter assetFields) and clone hands every consumer their own set to extend.
ALTER TABLE locations
  ADD COLUMN IF NOT EXISTS boards JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE objects
  ADD COLUMN IF NOT EXISTS boards JSONB NOT NULL DEFAULT '[]'::jsonb;
