-- Creature section completion (Studio): boards + voice.
--
-- boards — named Creature Boards, mirroring characters.boards (212) and
-- locations/objects.boards (214): dense reference sheets generated by Studio
-- via the generate-image/creature-board factory preset, one per variant/mood,
-- shaped [{ "name": "...", "url": "https://..." }]. First-class bucket so the
-- community pipeline carries it: publish snapshots it (R2-copied via the
-- adapter assetFields) and clone hands every consumer their own set to extend.
ALTER TABLE creatures
  ADD COLUMN IF NOT EXISTS boards JSONB NOT NULL DEFAULT '[]'::jsonb;

-- voice — the "talking creature" stack. IDENTICAL shape + semantics to
-- characters.voice (migration 110): { voiceId, voiceName, traits, voiceType?,
-- previewUrl?, ttsProvider? }. The speech/lip-sync routes are already generic
-- (text-to-speech reads voiceId/ttsProvider/voiceType; lip-sync targets the
-- creature's main image), so the column is the only platform state needed.
-- Community publish carries it by KIND exactly like characters (premade +
-- library voices fully; custom clones reduce to display name + sample —
-- never a usable voiceId cross-user).
ALTER TABLE creatures
  ADD COLUMN IF NOT EXISTS voice JSONB DEFAULT NULL;
