import type { FactoryPreset } from "./types.js"

export const GENERATE_VIDEO_PRESETS: readonly FactoryPreset[] = [
  // ── Camera Moves (composable cinematography fragments) ───────────────────
  {
    id: "generate-video/slow-push-in",
    name: "Slow Push-In",
    description: "Gradual dolly toward the subject.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "slow cinematic push-in toward {subject}, gradual forward dolly, shallow depth of field, smooth steady motion",
    },
  },
  {
    id: "generate-video/dolly-out",
    name: "Dolly Out (reveal)",
    description: "Pull back to reveal the scene.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "smooth dolly-out pulling back from {subject}, revealing the surrounding {environment}, cinematic reveal",
    },
  },
  {
    id: "generate-video/orbit-360",
    name: "360° Orbit",
    description: "Camera circles the subject.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "camera orbits 360 degrees around {subject}, smooth circular tracking shot, dynamic parallax reveal, cinematic",
    },
  },
  {
    id: "generate-video/arc-shot",
    name: "Arc Shot",
    description: "Sweeping lateral arc.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "sweeping arc shot moving laterally around {subject}, smooth parallax, cinematic",
    },
  },
  {
    id: "generate-video/crane-up",
    name: "Crane Up",
    description: "Rise up and over to reveal scale.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "cinematic crane shot rising up and over {subject}, revealing the wider {scene}, smooth vertical motion",
    },
  },
  {
    id: "generate-video/tracking-follow",
    name: "Tracking Follow",
    description: "Follow the subject from behind.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "tracking shot following {subject} from behind, steady gimbal motion, immersive",
    },
  },
  {
    id: "generate-video/slow-pan",
    name: "Slow Pan",
    description: "Horizontal sweep across the scene.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "slow cinematic pan across {scene}, smooth horizontal sweep, gradually revealing detail",
    },
  },
  {
    id: "generate-video/tilt-reveal",
    name: "Tilt-Up Reveal",
    description: "Vertical reveal from base to top.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "vertical tilt-up reveal of {subject}, from base to top, dramatic sense of scale, cinematic",
    },
  },
  {
    id: "generate-video/whip-pan",
    name: "Whip Pan",
    description: "Fast energetic transition.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "fast whip pan revealing {subject}, heavy motion blur, energetic transition",
    },
  },
  {
    id: "generate-video/dolly-zoom",
    name: "Dolly Zoom (Vertigo)",
    description: "Background warps, subject fixed.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "dolly zoom Vertigo effect on {subject}, background warps while the subject stays fixed, unsettling cinematic tension",
    },
  },

  // ── Shot Types & Angles ──────────────────────────────────────────────────
  {
    id: "generate-video/establishing-wide",
    name: "Establishing Wide",
    description: "Vast opening shot with scale.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "establishing wide shot of {location}, vast sense of scale, slow gentle camera drift, cinematic",
    },
  },
  {
    id: "generate-video/medium-shot",
    name: "Medium Shot",
    description: "Balanced waist-up framing.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "medium shot of {subject}, balanced framing, natural subtle movement, cinematic",
    },
  },
  {
    id: "generate-video/close-up",
    name: "Close-Up",
    description: "Intimate, shallow focus.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "intimate close-up of {subject}, shallow depth of field, subtle motion, emotional",
    },
  },
  {
    id: "generate-video/macro-detail",
    name: "Macro Detail",
    description: "Extreme close-up reveal.",
    group: "Shot Types & Angles",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "extreme macro shot of {subject}, ultra-close detail, slow reveal, shallow focus",
    },
  },
  {
    id: "generate-video/low-angle-hero",
    name: "Low-Angle Hero",
    description: "Looking up — powerful, imposing.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "dramatic low-angle hero shot of {subject}, camera looking up, powerful and imposing, cinematic",
    },
  },
  {
    id: "generate-video/overhead-topdown",
    name: "Overhead Top-Down",
    description: "Bird's-eye with slow rotation.",
    group: "Shot Types & Angles",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "overhead top-down shot of {scene}, bird's-eye perspective, slow rotation",
    },
  },
  {
    id: "generate-video/fpv-drone",
    name: "FPV Drone Flythrough",
    description: "Immersive first-person flight.",
    group: "Shot Types & Angles",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "fast FPV drone flythrough of {location}, immersive first-person flight, dynamic and smooth",
    },
  },

  // ── Cinematic & Specialty ────────────────────────────────────────────────
  {
    id: "generate-video/handheld-doc",
    name: "Handheld Documentary",
    description: "Raw, realistic camera shake.",
    group: "Cinematic & Specialty",
    data: {
      provider: "wan-2.7-t2v",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "handheld documentary shot of {subject}, natural camera shake, realistic and raw, available light",
    },
  },
  {
    id: "generate-video/slow-motion",
    name: "Slow Motion",
    description: "High-frame-rate dramatic movement.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "epic slow-motion shot of {subject}, high frame rate, fluid dramatic movement",
    },
  },
  {
    id: "generate-video/timelapse",
    name: "Timelapse",
    description: "Fast passage of time.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "timelapse of {scene}, fast-moving clouds and shifting light, dynamic passage of time",
    },
  },
  {
    id: "generate-video/hyperlapse",
    name: "Hyperlapse",
    description: "Moving timelapse through space.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "hyperlapse moving through {location}, fast smooth motion, dynamic perspective shift",
    },
  },
  {
    id: "generate-video/bullet-time",
    name: "Bullet Time",
    description: "Frozen moment, camera rotates.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "bullet-time effect, frozen moment around {subject} while the camera rotates, action suspended in mid-air",
    },
  },
  {
    id: "generate-video/rack-focus",
    name: "Rack Focus",
    description: "Shift focus between planes.",
    group: "Cinematic & Specialty",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "rack focus shifting from a foreground {subject} to the background {target}, cinematic depth, shallow focus",
    },
  },

  // ── Social & Reels (9:16) ────────────────────────────────────────────────
  {
    id: "generate-video/vertical-hero",
    name: "Vertical Hero",
    description: "Punchy 9:16 hero clip.",
    group: "Social & Reels",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "cinematic hero shot of {subject}, dynamic motion, punchy and eye-catching, optimized for social reels",
    },
  },
  {
    id: "generate-video/talking-head",
    name: "Talking Head",
    description: "Vertical creator-to-camera.",
    group: "Social & Reels",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "talking-head shot of {subject} speaking to the camera, clean background, natural movement and expression",
    },
  },
  {
    id: "generate-video/product-reveal-vertical",
    name: "Product Reveal (vertical)",
    description: "9:16 product show-off.",
    group: "Social & Reels",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "product reveal of {product}, dynamic rotation and pop, eye-catching, social-ready",
    },
  },
  {
    id: "generate-video/trend-quickcut",
    name: "Trend Quick-Cut",
    description: "Energetic vertical clip.",
    group: "Social & Reels",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "energetic clip of {subject}, fast dynamic motion, trendy and high-energy social video",
    },
  },
  {
    id: "generate-video/pov-vertical",
    name: "POV Walk (vertical)",
    description: "Immersive first-person reel.",
    group: "Social & Reels",
    data: {
      provider: "kling-3.0",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "POV shot walking through {location}, immersive first-person, handheld feel",
    },
  },

  // ── Product & Ads ────────────────────────────────────────────────────────
  {
    id: "generate-video/product-hero",
    name: "Product Hero",
    description: "Filmic handheld ad close-up.",
    group: "Product & Ads",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "slow handheld close-up of {product} on {surface}, soft window light, shallow depth of field, soft filmic grade, subtle motion — product hero shot for an ad",
    },
  },
  {
    id: "generate-video/product-spin",
    name: "Product 360 Spin",
    description: "Clean rotating studio loop.",
    group: "Product & Ads",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "1:1",
      duration: 5,
      prompt: "{product} slowly rotating 360 degrees on a clean studio surface, even lighting, seamless spin",
    },
  },
  {
    id: "generate-video/liquid-splash",
    name: "Liquid Splash",
    description: "Slow-mo commercial splash.",
    group: "Product & Ads",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "dramatic slow-motion liquid splash around {product}, dynamic droplets frozen in motion, premium commercial look",
    },
  },
  {
    id: "generate-video/unboxing",
    name: "Unboxing",
    description: "Cinematic reveal of the package.",
    group: "Product & Ads",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "cinematic unboxing of {product}, hands opening the package, soft light, sense of anticipation",
    },
  },
  {
    id: "generate-video/lifestyle-ad",
    name: "Lifestyle Ad",
    description: "Aspirational product-in-use.",
    group: "Product & Ads",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "lifestyle ad clip: {subject} using {product} in {setting}, natural light, aspirational and warm, social-ready",
    },
  },

  // ── Motion Graphics & Logo ───────────────────────────────────────────────
  {
    id: "generate-video/logo-sting",
    name: "Logo Sting",
    description: "Short punchy brand reveal.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "animated logo sting: {BRAND} logo assembles with light streaks and a clean reveal, short and punchy, on a solid background",
    },
  },
  {
    id: "generate-video/title-reveal",
    name: "Title Reveal",
    description: "Cinematic text reveal.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "cinematic title reveal: the text '{TITLE}' emerges with dramatic lighting, particles and depth",
    },
  },
  {
    id: "generate-video/particle-bg",
    name: "Particle Background",
    description: "Abstract drifting overlay.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "abstract flowing particle background, {color} gradient, gentle drifting motion, seamless, for overlays",
    },
  },
  {
    id: "generate-video/loop-background",
    name: "Loop Background",
    description: "Seamless looping motion bg.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "seamless looping abstract background, {color} gradient waves, slow hypnotic motion that returns to the start",
    },
  },

  // ── B-Roll & Nature ──────────────────────────────────────────────────────
  {
    id: "generate-video/clouds-timelapse",
    name: "Clouds Timelapse",
    description: "Dramatic rolling sky.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "timelapse of dramatic clouds rolling over {landscape}, golden light, dynamic sky",
    },
  },
  {
    id: "generate-video/water-slowmo",
    name: "Water Slow-Mo",
    description: "Glistening water in slow motion.",
    group: "B-Roll & Nature",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "slow-motion close-up of {water}, glistening droplets, serene and mesmerizing",
    },
  },
  {
    id: "generate-video/forest-drift",
    name: "Forest Drift",
    description: "Peaceful sunlit drift.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "gentle drift through a sunlit forest, light rays streaming through the trees, peaceful b-roll",
    },
  },
  {
    id: "generate-video/aerial-landscape",
    name: "Aerial Landscape",
    description: "Sweeping drone vista.",
    group: "B-Roll & Nature",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "sweeping aerial shot over {landscape}, vast cinematic vista, smooth drone motion",
    },
  },
  {
    id: "generate-video/ocean-loop",
    name: "Ocean Loop",
    description: "Calm seamless waves.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "calm ocean waves rolling gently toward shore, seamless loop, serene ambient b-roll",
    },
  },

  // ── Animation & Style ────────────────────────────────────────────────────
  {
    id: "generate-video/anime-motion",
    name: "Anime Motion",
    description: "Cel-shaded animated scene.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "anime-style animated scene of {subject}, cel-shaded, dynamic motion, vibrant colors",
    },
  },
  {
    id: "generate-video/cartoon-3d",
    name: "3D Cartoon",
    description: "Playful Pixar-like motion.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "3D animated cartoon scene of {subject}, polished Pixar-like rendering, playful motion",
    },
  },
  {
    id: "generate-video/claymation-move",
    name: "Claymation",
    description: "Tactile stop-motion feel.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "claymation stop-motion style animation of {subject}, tactile clay texture, charming handcrafted motion",
    },
  },
  {
    id: "generate-video/watercolor-motion",
    name: "Living Watercolor",
    description: "Flowing painterly motion.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "living watercolor painting of {scene}, flowing painterly motion, soft bleeding colors",
    },
  },

  // ── Looping & Backgrounds ────────────────────────────────────────────────
  {
    id: "generate-video/subtle-motion",
    name: "Subtle Motion",
    description: "Gentle, natural movement (great for animating a still).",
    group: "Looping & Backgrounds",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "subtle natural motion, gentle camera drift, cinematic",
    },
  },
  {
    id: "generate-video/living-wallpaper",
    name: "Living Wallpaper",
    description: "Ambient looping scene.",
    group: "Looping & Backgrounds",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "living wallpaper: {scene} with subtle ambient motion, calm and hypnotic, seamless loop",
    },
  },
  {
    id: "generate-video/parallax",
    name: "Parallax (2.5D)",
    description: "Depth move over a still.",
    group: "Looping & Backgrounds",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "2.5D parallax camera move over {scene}, layered depth, subtle motion bringing a still image to life" },
  },
  {
    id: "generate-video/cinemagraph",
    name: "Cinemagraph",
    description: "Mostly still, one moving element.",
    group: "Looping & Backgrounds",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "cinemagraph of {scene}, mostly frozen with one element in subtle motion ({moving element}), seamless loop" },
  },
  {
    id: "generate-video/fire-smoke-loop",
    name: "Fire & Smoke FX",
    description: "Looping embers and smoke.",
    group: "Looping & Backgrounds",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "looping fire and smoke FX over a dark background, drifting embers, slow rolling smoke, seamless" },
  },
  // additional Camera Moves / Cinematic / Social / Product / Motion-graphics / B-roll
  {
    id: "generate-video/crash-zoom",
    name: "Crash Zoom",
    description: "Sudden energetic punch-in.",
    group: "Camera Moves",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "rapid crash zoom punching in toward {subject}, sudden energetic push-in, motion blur" },
  },
  {
    id: "generate-video/slowmo-reveal",
    name: "Slow-Mo Reveal",
    description: "Speed-ramped hero slowdown.",
    group: "Cinematic & Specialty",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "dramatic slow-motion hero reveal of {subject}, speed ramp into smooth slow motion, cinematic" },
  },
  {
    id: "generate-video/match-cut",
    name: "Match Cut / Morph",
    description: "Object A morphs into B.",
    group: "Cinematic & Specialty",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "seamless match cut morphing {subject A} into {subject B}, smooth transformation transition" },
  },
  {
    id: "generate-video/before-after",
    name: "Before / After Reveal",
    description: "Wipe between two states.",
    group: "Product & Ads",
    data: { provider: "kling-3.0", aspectRatio: "16:9", duration: 5, prompt: "before and after reveal of {subject}, smooth wipe transition from the 'before' state to the 'after' state" },
  },
  {
    id: "generate-video/kinetic-typography",
    name: "Kinetic Typography",
    description: "Words animate in with rhythm.",
    group: "Motion Graphics & Logo",
    data: { provider: "veo3.1", aspectRatio: "16:9", duration: 8, prompt: "kinetic typography animation: the words '{TEXT}' animate in dynamically with motion, rhythm and depth on a clean background" },
  },
  {
    id: "generate-video/fashion-walk",
    name: "Fashion Walk",
    description: "Runway stride, fabric in motion.",
    group: "Social & Reels",
    data: { provider: "kling-3.0", aspectRatio: "9:16", duration: 5, prompt: "fashion runway walk, {model} striding confidently toward camera, fabric flowing in motion, editorial lighting" },
  },
  {
    id: "generate-video/weather-atmosphere",
    name: "Weather Atmosphere",
    description: "Rain / snow / fog rolling in.",
    group: "B-Roll & Nature",
    data: { provider: "runway-kie", aspectRatio: "16:9", duration: 5, prompt: "atmospheric weather rolling into {scene}: {weather}, moody and cinematic" },
  },

  // ── Viral & Effects (transformation / POV effects — best with an input image) ──
  {
    id: "generate-video/frozen-in-ice",
    name: "Frozen in Ice",
    description: "Subject freezes into solid ice.",
    group: "Viral & Effects",
    data: { provider: "veo3.1", aspectRatio: "9:16", duration: 8, prompt: "{subject} slowly freezes into solid ice — frost spreads across the skin, crystals form, then a final shimmer as the figure becomes a glassy ice sculpture; cold blue light, drifting frost, cinematic" },
  },
  {
    id: "generate-video/superhero-transformation",
    name: "Superhero Transformation",
    description: "Ordinary subject → superhero reveal.",
    group: "Viral & Effects",
    data: { provider: "kling-3.0", aspectRatio: "9:16", duration: 5, prompt: "{subject} transforms into a superhero — a swirl of energy spirals around them, a cape and suit form, then a confident heroic reveal; dynamic light streaks, dramatic, cinematic" },
  },
  {
    id: "generate-video/elevator-doors-reveal",
    name: "Elevator Doors Reveal",
    description: "Doors open, objects cascade out.",
    group: "Viral & Effects",
    data: { provider: "kling-3.0", aspectRatio: "9:16", duration: 5, prompt: "locked static camera: {subject} stands perfectly still inside a luxury mirrored elevator; the doors slowly slide open and {objects, e.g. roses, balloons, butterflies} cascade out and fill the space, soft cinematic light, the subject stays completely frozen, editorial" },
  },
  {
    id: "generate-video/pov-skydive",
    name: "POV Skydive",
    description: "First-person freefall over a place.",
    group: "Viral & Effects",
    data: { provider: "kling-3.0", aspectRatio: "9:16", duration: 5, prompt: "first-person POV skydiving freefall over {location}, the ground far below rushing closer, clouds and wind streaking past, wide action-cam lens, exhilarating" },
  },
  {
    id: "generate-video/underwater-pov",
    name: "Underwater POV",
    description: "First-person dive, sunbeams + bubbles.",
    group: "Viral & Effects",
    data: { provider: "veo3.1", aspectRatio: "9:16", duration: 8, prompt: "first-person POV diving underwater toward {subject}, shafts of sunlight piercing the deep blue, drifting bubbles and gentle currents, serene and immersive" },
  },
]
