import type { FactoryPreset } from "./types.js"

export const GENERATE_VIDEO_PRESETS: readonly FactoryPreset[] = [
  // ── Camera Moves (composable cinematography fragments) ───────────────────
  {
    id: "generate-video/slow-push-in",
    name: "Slow Push-In",
    description: "Gradual dolly toward the subject.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "slow cinematic push-in toward {subject || a lone figure at a rain-streaked window}, gradual forward dolly on a smooth gimbal, shallow depth of field with soft bokeh, motivated low-key lighting, deliberate and steady pacing with subtle parallax, filmic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, speed changes, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/dolly-out",
    name: "Dolly Out (reveal)",
    description: "Pull back to reveal the scene.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "smooth dolly-out pulling back from {subject || a lone figure standing in an empty hall}, gradually revealing the surrounding {environment || a vast cathedral interior at dusk}, wide reveal on a steadicam, expanding sense of scale and depth, soft volumetric light, deliberate and graceful pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/orbit-360",
    name: "360° Orbit",
    description: "Camera circles the subject.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "camera orbits a full 360 degrees around {subject || a hero standing on a rooftop at sunset}, smooth circular tracking on a gimbal, medium shot with shallow depth of field, dynamic parallax as the background sweeps past, golden-hour rim light, continuous and even orbital pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, duplicate subject, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/arc-shot",
    name: "Arc Shot",
    description: "Sweeping lateral arc.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "sweeping arc shot gliding laterally around {subject || a vintage sports car on a coastal road}, smooth curved dolly on a steadicam, medium-wide shot with subtle depth, layered parallax between foreground and background, warm directional light, fluid and continuous pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/crane-up",
    name: "Crane Up",
    description: "Rise up and over to reveal scale.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "cinematic crane shot rising up and over {subject || a lone traveler on a desert dune}, craning into a high wide angle to reveal the larger {scene || an endless dune sea at golden hour}, smooth vertical boom on a crane, dramatic sense of scale, warm low-angle sun, slow and majestic pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/tracking-follow",
    name: "Tracking Follow",
    description: "Follow the subject from behind.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "tracking shot following {subject || a runner sprinting down a forest trail} from behind, steady gimbal glide matching their pace, medium shot with the background streaming past, immersive sense of momentum, dappled natural light, energetic but smooth pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/slow-pan",
    name: "Slow Pan",
    description: "Horizontal sweep across the scene.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "slow cinematic pan across {scene || a misty mountain valley at dawn}, smooth horizontal sweep on a locked tripod head, wide establishing shot, gradually revealing layered detail across the frame, soft atmospheric light, unhurried and graceful pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/tilt-reveal",
    name: "Tilt-Up Reveal",
    description: "Vertical reveal from base to top.",
    group: "Camera Moves",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "vertical tilt-up reveal of {subject || a towering skyscraper of glass and steel}, camera tilts smoothly from base to top on a locked head, low-angle wide shot, dramatic sense of scale and height, crisp directional daylight, slow and deliberate pacing, cinematic motion",
      negativePrompt: "jitter, camera shake, warping, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/whip-pan",
    name: "Whip Pan",
    description: "Fast energetic transition.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "fast whip pan snapping across to reveal {subject || a dancer mid-pose in a neon studio}, rapid horizontal swish with directional motion blur, medium shot that lands and settles, punchy energetic transition, bold neon practical light, quick whip-then-hold pacing, cinematic motion",
      negativePrompt: "warping, morphing, stutter, ghosting, distorted features, extra limbs, duplicate subject, low quality, blurry mush, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/dolly-zoom",
    name: "Dolly Zoom (Vertigo)",
    description: "Background warps, subject fixed.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "dolly zoom Vertigo effect on {subject || a man frozen at the end of a long corridor}, camera dollies back while zooming in so the background stretches and the subject stays the same size, medium shot locked on the subject, unsettling spatial distortion, moody low-key light, slow building dread, cinematic motion",
      negativePrompt: "wrong vertigo direction, reversed perspective, subject changing size, subject drift, jitter, camera shake, morphing, stutter, distorted features, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },

  // ── Shot Types & Angles ──────────────────────────────────────────────────
  {
    id: "generate-video/establishing-wide",
    name: "Establishing Wide",
    description: "Vast opening shot with scale.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "sweeping establishing wide shot of {location || a snow-capped mountain range at sunrise}, slow gentle camera drift on a locked tripod, ultra-wide framing with deep focus, vast cinematic sense of place and scale, soft golden-hour light raking across the landscape, unhurried and majestic pacing with subtle atmospheric movement, filmic motion",
      negativePrompt: "warping, morphing, flickering, jitter, camera shake, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/medium-shot",
    name: "Medium Shot",
    description: "Balanced waist-up framing.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "medium shot of {subject || a person in conversation in a sunlit cafe}, locked steady framing on a tripod with a faint breathing handheld feel, waist-up composition with a natural 50mm look and gentle depth of field, soft motivated daylight, relaxed natural movement and subtle gestures at an even, lifelike pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/close-up",
    name: "Close-Up",
    description: "Intimate, shallow focus.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "intimate close-up of {subject || a face lit by warm window light}, slow micro push-in on a smooth gimbal, tight framing with a long lens and very shallow depth of field and creamy bokeh, soft motivated key light, delicate emotional micro-expressions and breathing at a slow, tender pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, distorted anatomy, deformed face, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/macro-detail",
    name: "Macro Detail",
    description: "Extreme close-up reveal.",
    group: "Shot Types & Angles",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "extreme macro shot of {subject || a dewdrop trembling on a leaf}, slow creeping slider move on a macro rail, ultra-close framing with a true macro lens and razor-thin depth of field, soft diffused light catching fine texture, mesmerizing slow reveal of tactile micro-detail at a hypnotic, deliberate pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, focus hunting, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/low-angle-hero",
    name: "Low-Angle Hero",
    description: "Looking up — powerful, imposing.",
    group: "Shot Types & Angles",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "dramatic low-angle hero shot of {subject || a confident figure against a stormy sky}, camera looking steeply up with a slow rising push on a steadicam, wide angle that exaggerates height and stature, powerful and imposing framing, bold backlit rim light against dark clouds, commanding presence with slow, weighty motion, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/overhead-topdown",
    name: "Overhead Top-Down",
    description: "Bird's-eye with slow rotation.",
    group: "Shot Types & Angles",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "overhead top-down shot of {scene || a beautifully plated meal on a wooden table}, perfectly flat bird's-eye perspective with a slow even rotation on an overhead rig, wide framing with deep focus across the surface, soft directional light defining shape and texture, graceful continuous turning motion at a calm, steady pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, wobble, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/fpv-drone",
    name: "FPV Drone Flythrough",
    description: "Immersive first-person flight.",
    group: "Shot Types & Angles",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "fast FPV drone flythrough of {location || a narrow canyon carved by a rushing river}, aggressive first-person racing-drone flight diving and banking through the space, ultra-wide action-cam lens with deep focus, immersive sense of speed and momentum, bright natural daylight streaking past, exhilarating fast yet fluid pacing, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, motion sickness wobble, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },

  // ── Cinematic & Specialty ────────────────────────────────────────────────
  {
    id: "generate-video/handheld-doc",
    name: "Handheld Documentary",
    description: "Raw, realistic camera shake.",
    group: "Cinematic & Specialty",
    data: {
      provider: "wan-2.7-t2v",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "handheld documentary shot of {subject || a street vendor at work in a busy market}, organic handheld energy with natural micro-shake and subtle reframing, loose medium shot on a documentary lens, realistic and raw available light, candid spontaneous movement at a lively, observational pace, gritty cinema-verite motion",
      negativePrompt: "warping, morphing, flickering, violent jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/slow-motion",
    name: "Slow Motion",
    description: "High-frame-rate dramatic movement.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "epic high-speed slow-motion shot of {subject || a sprinter exploding off the blocks}, smooth gliding gimbal move tracking the action, medium shot with shallow depth of field, silky high-frame-rate slow motion rendering every detail, dramatic motivated light, fluid weighty movement stretched into graceful slow-mo, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, choppy frames, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/timelapse",
    name: "Timelapse",
    description: "Fast passage of time.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "timelapse of {scene || a city skyline from day into night}, locked tripod with a slow subtle creep, wide deep-focus framing, fast-moving clouds streaking overhead and light shifting across the scene, dramatic changing sky, accelerated dynamic passage of time at a smooth, steady cadence, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, strobing, flicker, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/hyperlapse",
    name: "Hyperlapse",
    description: "Moving timelapse through space.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "hyperlapse traveling through {location || a neon-lit city street at night}, stabilized moving timelapse gliding forward with the world rushing past, wide deep-focus framing, motion locked to a vanishing point for a dynamic perspective shift, vivid practical light streaking by, fast yet smooth accelerated pacing, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, strobing, flicker, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/bullet-time",
    name: "Bullet Time",
    description: "Frozen moment, camera rotates.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "bullet-time effect around {subject || a person leaping in mid-air}, the moment frozen in time while the camera sweeps in a smooth arc on a circular rig, medium shot with shallow depth of field, action suspended motionless in mid-air, dramatic rim light catching the frozen pose, only the camera moves at a continuous, gliding orbital pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, subject moving during freeze, distorted anatomy, extra limbs, duplicate subject, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/rack-focus",
    name: "Rack Focus",
    description: "Shift focus between planes.",
    group: "Cinematic & Specialty",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "rack focus pulling from a foreground {subject || a hand resting on a windowsill} to a background {target || a figure approaching in the distance}, locked tripod with a deliberate focus pull between planes, medium shot on a long lens with very shallow depth of field, soft motivated light, cinematic depth as attention shifts at a slow, intentional pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, focus hunting, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },

  // ── Social & Reels (9:16) ────────────────────────────────────────────────
  {
    id: "generate-video/vertical-hero",
    name: "Vertical Hero",
    description: "Punchy 9:16 hero clip.",
    group: "Social & Reels",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "cinematic vertical hero shot of {subject || a confident athlete poised against a bold backdrop}, snappy push-in on a smooth gimbal, tight vertical medium framing with a punchy wide-aperture look and shallow depth of field, bold high-contrast lighting with a glowing rim, dynamic and energetic movement at a punchy, scroll-stopping pace built for social reels, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },
  {
    id: "generate-video/talking-head",
    name: "Talking Head",
    description: "Vertical creator-to-camera.",
    group: "Social & Reels",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "vertical talking-head shot of {subject || a friendly creator addressing the camera} speaking directly to the lens with steady eye contact, locked steady framing with a faint breathing handheld feel, vertical waist-up composition with a flattering 50mm look and gently blurred clean background, soft motivated key light on the face, natural expressive gestures and lifelike micro-expressions at an even, conversational pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, distorted anatomy, deformed face, wandering eyes, extra limbs, low quality, blurry, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },
  {
    id: "generate-video/product-reveal-vertical",
    name: "Product Reveal (vertical)",
    description: "9:16 product show-off.",
    group: "Social & Reels",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "vertical product reveal of {product || a sleek matte-black smartwatch}, dynamic snap-rotation and a satisfying hero pop on a smooth turntable move, tight vertical close-up framing with crisp focus and shallow depth of field, bright punchy studio lighting with a clean glowing highlight, eye-catching energetic motion at a quick, scroll-stopping social pace, the product staying perfectly crisp and intact, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, warping, morphing, flickering, jitter, stutter, low quality, blurry, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },
  {
    id: "generate-video/trend-quickcut",
    name: "Trend Quick-Cut",
    description: "Energetic vertical clip.",
    group: "Social & Reels",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "high-energy vertical clip of {subject || a dancer mid-move in a neon-lit room}, snappy quick-cut energy with fast whip moves and punchy reframes, tight vertical framing with a dynamic wide look and shallow depth of field, vibrant bold practical lighting, fast trendy movement at a rapid, beat-driven social pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, ghosting, distorted anatomy, extra limbs, low quality, blurry mush, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },
  {
    id: "generate-video/pov-vertical",
    name: "POV Walk (vertical)",
    description: "Immersive first-person reel.",
    group: "Social & Reels",
    data: {
      provider: "kling-3.0",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "immersive first-person POV walking through {location || a sunlit city street market}, the camera bobbing naturally with each step as the world moves toward the viewer, vertical wide action-cam framing with deep focus, bright natural daylight, energetic yet smooth handheld momentum at a brisk, immersive walking pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, violent shake, stutter, motion sickness wobble, distorted anatomy, extra limbs, visible body or hands, low quality, blurry, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },

  // ── Product & Ads ────────────────────────────────────────────────────────
  {
    id: "generate-video/product-hero",
    name: "Product Hero",
    description: "Filmic handheld ad close-up.",
    group: "Product & Ads",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "premium product hero shot of {product || a matte-black smartwatch} resting on {surface || a polished dark stone slab}, slow handheld micro push-in with a gentle organic drift, tight close-up on a macro lens with shallow depth of field and creamy bokeh, soft window key light with a warm hero glow catching the edges, subtle elegant motion at a slow, luxurious advertising pace, the product staying perfectly crisp and undistorted, soft filmic grade, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/product-spin",
    name: "Product 360 Spin",
    description: "Clean rotating studio loop.",
    group: "Product & Ads",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "1:1",
      duration: 5,
      prompt: "{product || a sleek glass perfume bottle} rotating a smooth full turn on a clean studio turntable, locked centered framing with crisp focus and a softly blurred seamless backdrop, even diffused studio lighting with a clean glowing highlight, continuous silky turntable motion at a steady, even spin that loops seamlessly with no visible seam, the product staying perfectly crisp and undistorted, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, visible seam, jump cut, warping, morphing, flickering, jitter, stutter, wobble, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/liquid-splash",
    name: "Liquid Splash",
    description: "Slow-mo commercial splash.",
    group: "Product & Ads",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "dramatic slow-motion liquid splash erupting around {product || a frosted beverage can}, smooth locked-off framing on a macro lens with shallow depth of field, crisp studio lighting catching every droplet, dynamic crowns and ribbons of liquid suspended in silky high-frame-rate slow motion at a graceful, weighty pace, premium commercial look with the product staying perfectly crisp and undistorted, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, warping, morphing, flickering, jitter, stutter, choppy frames, smeared droplets, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/unboxing",
    name: "Unboxing",
    description: "Cinematic reveal of the package.",
    group: "Product & Ads",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "cinematic unboxing of {product || a premium pair of wireless headphones}, hands lifting the lid and easing the product from its packaging, slow handheld push-in on a smooth gimbal, tight close-up on a 50mm lens with shallow depth of field, soft warm window light with a gentle hero glow, deliberate motion building a sense of anticipation at a slow, premium reveal pace, the product staying perfectly crisp and undistorted, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, warping, morphing, flickering, jitter, stutter, distorted anatomy, deformed hands, extra fingers, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/lifestyle-ad",
    name: "Lifestyle Ad",
    description: "Aspirational product-in-use.",
    group: "Product & Ads",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "vertical lifestyle ad clip of {subject || a smiling young woman} naturally using {product || a sleek stainless-steel water bottle} in {setting || a bright sunlit kitchen}, gentle handheld follow on a smooth gimbal, vertical medium framing with a warm wide-aperture look and shallow depth of field, soft natural window light, relaxed authentic movement at an easy, aspirational pace, the product staying perfectly crisp and undistorted, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, warping, morphing, flickering, jitter, stutter, distorted anatomy, deformed hands, extra limbs, low quality, blurry, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },

  // ── Motion Graphics & Logo ───────────────────────────────────────────────
  {
    id: "generate-video/logo-sting",
    name: "Logo Sting",
    description: "Short punchy brand reveal.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "premium animated logo sting for {BRAND || a modern minimalist brand}, the crisp logo mark assembling and animating in cleanly with sweeping light streaks and a polished glint, centered hero composition on a solid background with subtle depth, sleek motivated studio light, short and punchy with a confident snap-into-place reveal, the logo staying crisp, legible and correctly proportioned, premium motion-graphics polish, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, low quality, blurry, artifacts, watermark, misspelled text, garbled letters, jumbled type, distorted logo, deformed mark, extra elements",
    },
  },
  {
    id: "generate-video/title-reveal",
    name: "Title Reveal",
    description: "Cinematic text reveal.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "cinematic title reveal of the text '{TITLE}', the letters resolving into focus with a dynamic animated title build, slow push-in on a smooth virtual camera, centered hero framing with shallow depth and soft bokeh, dramatic motivated key light with drifting particles and atmospheric haze, deliberate and majestic pacing that settles into a clean hold, the title staying legible, correctly-spelled and crisp with sharp typography, premium motion-graphics polish, cinematic motion",
      negativePrompt: "misspelled text, garbled letters, jumbled type, gibberish characters, warping, morphing, flickering, jitter, stutter, low quality, blurry, artifacts, watermark, distorted text, deformed letters",
    },
  },
  {
    id: "generate-video/particle-bg",
    name: "Particle Background",
    description: "Abstract drifting overlay.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "abstract flowing particle background in a {color || deep indigo and teal} gradient, soft glowing motes and fine bokeh particles drifting gently across the frame, full-frame ambient field with layered depth and a soft falloff, dreamy diffused light with a gentle glow, slow hypnotic drifting motion at a calm, even pace, seamless loop with no visible seam, ideal for overlays and backgrounds, premium motion-graphics polish, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, warping, morphing, flickering, jitter, stutter, low quality, blurry, artifacts, watermark, text, harsh strobing, banding",
    },
  },
  {
    id: "generate-video/loop-background",
    name: "Loop Background",
    description: "Seamless looping motion bg.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "seamless looping abstract background of smooth flowing {color || violet and magenta} gradient waves, soft liquid ribbons undulating gently across the full frame with layered depth, dreamy diffused light with a subtle inner glow, slow hypnotic motion that drifts and returns smoothly to the start, seamless loop with no visible seam, ideal as a motion backdrop, premium motion-graphics polish, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, warping, morphing, flickering, jitter, stutter, low quality, blurry, artifacts, watermark, text, harsh strobing, banding",
    },
  },

  // ── B-Roll & Nature ──────────────────────────────────────────────────────
  {
    id: "generate-video/clouds-timelapse",
    name: "Clouds Timelapse",
    description: "Dramatic rolling sky.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "dramatic timelapse of billowing clouds rolling and churning over {landscape || a rugged mountain ridgeline}, locked tripod with a slow subtle creep, wide deep-focus establishing framing, towering cloud banks streaking across a vast dynamic sky as golden light rakes the terrain, accelerated yet smooth passage of time at a steady cadence, serene cinematic b-roll, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, strobing, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/water-slowmo",
    name: "Water Slow-Mo",
    description: "Glistening water in slow motion.",
    group: "B-Roll & Nature",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "slow-motion close-up of {water || a clear mountain stream cascading over rocks}, smooth locked-off framing on a macro lens with shallow depth of field, glistening droplets and silvery ribbons of water suspended in silky high-frame-rate slow motion, soft natural light catching every bead, serene and mesmerizing flow at a graceful, weighty pace, serene cinematic b-roll, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, choppy frames, smeared droplets, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/forest-drift",
    name: "Forest Drift",
    description: "Peaceful sunlit drift.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "gentle forward drift through a lush sunlit forest, slow steadicam glide weaving between mossy trunks, wide framing with soft depth and natural bokeh, golden light rays streaming through the canopy in drifting volumetric beams with floating dust motes, calm and unhurried movement at a peaceful, meditative pace, serene cinematic b-roll, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, camera shake, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/aerial-landscape",
    name: "Aerial Landscape",
    description: "Sweeping drone vista.",
    group: "B-Roll & Nature",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "sweeping aerial drone shot soaring over {landscape || a snow-capped mountain range at sunrise}, smooth high-altitude glide on a stabilized gimbal, ultra-wide framing with deep focus and layered atmospheric haze, vast cinematic vista with a powerful sense of scale, warm golden-hour light raking across the terrain, graceful and majestic forward motion at an unhurried pace, serene cinematic b-roll, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, camera shake, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/ocean-loop",
    name: "Ocean Loop",
    description: "Calm seamless waves.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "calm ocean waves rolling gently toward a quiet shore, locked-off wide framing with deep focus across the water, soft natural light glinting off the swell with gentle foam and ripples, slow soothing rhythmic motion at a serene, even pace that returns smoothly to the start, seamless loop with no visible seam, serene ambient cinematic b-roll, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },

  // ── Animation & Style ────────────────────────────────────────────────────
  {
    id: "generate-video/anime-motion",
    name: "Anime Motion",
    description: "Cel-shaded animated scene.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "2D anime cel-animation scene of {subject || a determined young hero on a windswept rooftop}, hand-drawn anime style with bold cel-shading, clean ink linework and flat vibrant color, smooth dynamic anime motion with expressive action and speed lines, medium shot with a gentle camera push and subtle parallax, dramatic anime lighting with crisp highlights and saturated skies, lively energetic pacing true to the animated look",
      negativePrompt: "photorealistic, live-action, 3D render, off-model, inconsistent style, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/cartoon-3d",
    name: "3D Cartoon",
    description: "Playful Pixar-like motion.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "polished 3D-cartoon animated scene of {subject || a cheerful round-faced character on a colorful adventure}, glossy Pixar-style rendering with soft subsurface skin, big expressive eyes and squash-and-stretch appeal, smooth bouncy character animation with playful exaggerated motion, medium shot with a gentle dynamic camera move, warm cinematic 3D lighting with soft shadows and a bright color palette, lively upbeat pacing true to a feature-animation look",
      negativePrompt: "photorealistic, live-action, 2D flat, off-model, inconsistent style, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/claymation-move",
    name: "Claymation",
    description: "Tactile stop-motion feel.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "claymation stop-motion animation of {subject || a quirky little clay character in a handmade diorama}, sculpted modeling-clay with visible fingerprints, seams and tactile matte texture, charming handcrafted stop-motion movement with a slightly stepped frame-by-frame cadence, medium shot with a gentle deliberate camera move, warm soft studio lighting on a miniature set, cozy whimsical pacing true to a tactile stop-motion look",
      negativePrompt: "photorealistic, live-action, smooth CG, off-model, inconsistent style, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/watercolor-motion",
    name: "Living Watercolor",
    description: "Flowing painterly motion.",
    group: "Animation & Style",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "living watercolor painting of {scene || a misty riverside village in spring}, flowing hand-painted watercolor style with visible paper texture and soft feathered edges, pigments blooming and bleeding gently as wet washes drift and diffuse, slow graceful camera drift across the artwork, luminous translucent layers with soft natural light, calm dreamlike pacing true to a flowing watercolor look",
      negativePrompt: "photorealistic, live-action, 3D render, hard digital edges, off-model, inconsistent style, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },

  // ── Looping & Backgrounds ────────────────────────────────────────────────
  {
    id: "generate-video/subtle-motion",
    name: "Subtle Motion",
    description: "Gentle, natural movement (great for animating a still).",
    group: "Looping & Backgrounds",
    data: {
      provider: "seedance-2-fast",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "subtle natural ambient motion bringing a still image to life, gentle slow camera drift on a smooth gimbal with delicate parallax, soft micro-movement in the scene that stays understated and lifelike, soft motivated light, calm unhurried pacing, seamless loop with no visible seam, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, flicker, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/living-wallpaper",
    name: "Living Wallpaper",
    description: "Ambient looping scene.",
    group: "Looping & Backgrounds",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "living wallpaper of {scene || a tranquil moonlit lake beneath drifting clouds}, soft ambient motion gently animating the scene with delicate parallax and layered depth, slow hypnotic camera drift, dreamy diffused light with a calm glow, soothing meditative pacing that returns smoothly to the start, seamless loop with no visible seam, ideal as an ambient motion backdrop, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, flicker, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/parallax",
    name: "Parallax (2.5D)",
    description: "Depth move over a still.",
    group: "Looping & Backgrounds",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "2.5D parallax camera move over {scene || a foggy forest valley at dawn}, foreground, midground and background separated into layered planes that slide at different speeds for true depth, smooth slow dolly on a virtual gimbal bringing the still image to life, soft atmospheric light with gentle haze between the layers, calm deliberate pacing, seamless loop with no visible seam, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, flicker, flat single plane, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/cinemagraph",
    name: "Cinemagraph",
    description: "Mostly still, one moving element.",
    group: "Looping & Backgrounds",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "cinemagraph of {scene || a quiet cafe table by a rainy window}, the entire frame held perfectly still and frozen except for one single element in gentle, subtle motion ({moving element || rain trickling down the glass}), locked-off framing with no camera movement, soft natural light, hypnotic minimal motion at a calm, even pace, seamless loop with no visible seam, cinematic",
      negativePrompt: "visible seam, jump cut, pop, flicker, whole scene moving, multiple moving elements, camera movement, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/fire-smoke-loop",
    name: "Fire & Smoke FX",
    description: "Looping embers and smoke.",
    group: "Looping & Backgrounds",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "looping fire and smoke FX over a deep black background, glowing embers drifting upward and slow rolling volumetric smoke curling through the frame, locked-off framing with fine particle detail and soft depth, warm fiery glow against the darkness, hypnotic slow drifting motion at a steady pace that returns smoothly to the start, seamless loop with no visible seam, ideal as an FX overlay, cinematic motion",
      negativePrompt: "visible seam, jump cut, pop, flicker, warping, morphing, flickering, jitter, stutter, harsh strobing, low quality, blurry, artifacts, watermark, text",
    },
  },
  // additional Camera Moves / Cinematic / Social / Product / Motion-graphics / B-roll
  {
    id: "generate-video/crash-zoom",
    name: "Crash Zoom",
    description: "Sudden energetic punch-in.",
    group: "Camera Moves",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "rapid crash zoom punching in toward {subject || a startled face reacting to bad news}, sudden aggressive snap-zoom from wide to tight close-up, directional motion blur on the push, high-impact dramatic emphasis, hard contrasty light, explosive quick-in then hold pacing, cinematic motion",
      negativePrompt: "warping, morphing, stutter, ghosting, distorted features, extra limbs, duplicate subject, low quality, blurry mush, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/slowmo-reveal",
    name: "Slow-Mo Reveal",
    description: "Speed-ramped hero slowdown.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "dramatic hero reveal of {subject || a warrior turning to face the camera}, smooth push-in on a gimbal that speed-ramps from real-time into silky slow motion at the moment of reveal, medium shot with shallow depth of field, bold dramatic rim light, the action stretches into majestic slow-mo at the peak beat, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, abrupt speed jump, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/match-cut",
    name: "Match Cut / Morph",
    description: "Object A morphs into B.",
    group: "Cinematic & Specialty",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "seamless match cut morphing {subject A || a blooming flower} into {subject B || a spinning galaxy}, matched framing and motion so the first subject flows directly into the second, medium shot with shallow depth of field, soft even light through the transition, one continuous fluid transformation at a smooth, hypnotic pace, cinematic motion",
      negativePrompt: "warping, morphing artifacts, flickering, jitter, stutter, abrupt jump cut, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/before-after",
    name: "Before / After Reveal",
    description: "Wipe between two states.",
    group: "Product & Ads",
    data: {
      provider: "kling-3.0",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "before and after reveal of {subject || a freshly renovated living room}, a smooth wipe sweeping across the frame to transition cleanly from the 'before' state to the polished 'after' state, locked steady framing with crisp focus and matched composition on both sides, even flattering lighting, one continuous fluid wipe-reveal at a satisfying, deliberate pace, the subject staying crisp and undistorted through the transition, cinematic motion",
      negativePrompt: "distorted product, melting edges, warped logo, deformed packaging, misaligned wipe, double exposure, ghosting, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/kinetic-typography",
    name: "Kinetic Typography",
    description: "Words animate in with rhythm.",
    group: "Motion Graphics & Logo",
    data: {
      provider: "veo3.1",
      aspectRatio: "16:9",
      duration: 8,
      prompt: "kinetic typography animation of the words '{TEXT}', the words flying and snapping into place in time with a driving rhythm, words scaling and sliding through layered 3D depth with a virtual camera weaving between them, centered dynamic composition on a clean background with soft shadows, punchy motivated light, energetic beat-synced pacing with confident accents, the words staying legible, correctly-spelled and crisp with sharp typography, premium motion-graphics polish, cinematic motion",
      negativePrompt: "misspelled text, garbled letters, jumbled type, gibberish characters, warping, morphing, flickering, jitter, stutter, low quality, blurry, artifacts, watermark, distorted text, deformed letters",
    },
  },
  {
    id: "generate-video/fashion-walk",
    name: "Fashion Walk",
    description: "Runway stride, fabric in motion.",
    group: "Social & Reels",
    data: {
      provider: "kling-3.0",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "vertical fashion runway walk, {model || a striking high-fashion model in a flowing couture gown} striding confidently toward the camera with a poised runway strut, slow tracking pull-back on a smooth gimbal, vertical full-body framing with an editorial wide-aperture look and shallow depth of field, dramatic editorial lighting with a crisp rim, fabric billowing and rippling in motion at a steady, commanding catwalk pace, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, stutter, distorted anatomy, deformed face, extra limbs, mangled fabric, low quality, blurry, artifacts, watermark, text, letterboxing, horizontal bars",
    },
  },
  {
    id: "generate-video/weather-atmosphere",
    name: "Weather Atmosphere",
    description: "Rain / snow / fog rolling in.",
    group: "B-Roll & Nature",
    data: {
      provider: "runway-kie",
      aspectRatio: "16:9",
      duration: 5,
      prompt: "atmospheric weather rolling into {scene || a quiet forest clearing at dusk}: {weather || e.g. drifting fog, soft rain, or falling snow} sweeping across the frame, slow gentle camera drift on a locked head, wide deep-focus framing, moody motivated light filtering through the atmosphere with rich depth and haze, calm and immersive movement at an unhurried, brooding pace, serene cinematic b-roll, cinematic motion",
      negativePrompt: "warping, morphing, flickering, jitter, camera shake, stutter, strobing, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },

  // ── Viral & Effects (transformation / POV effects — best with an input image) ──
  {
    id: "generate-video/frozen-in-ice",
    name: "Frozen in Ice",
    description: "Subject freezes into solid ice.",
    group: "Viral & Effects",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "{subject || a standing person} slowly freezes into solid ice — frost spreads across the skin, crystals form, then a final shimmer as the figure becomes a glassy ice sculpture; cold blue light, drifting frost, cinematic",
      negativePrompt: "identity change, distorted face, deformed features, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/superhero-transformation",
    name: "Superhero Transformation",
    description: "Ordinary subject → superhero reveal.",
    group: "Viral & Effects",
    data: {
      provider: "kling-3.0",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "{subject || an ordinary person} transforms into a superhero — a swirl of energy spirals around them, a cape and suit form, then a confident heroic reveal; dynamic light streaks, dramatic, cinematic",
      negativePrompt: "identity change, distorted face, deformed features, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/elevator-doors-reveal",
    name: "Elevator Doors Reveal",
    description: "Doors open, objects cascade out.",
    group: "Viral & Effects",
    data: {
      provider: "kling-3.0",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "locked static camera: {subject || a stylish person} stands perfectly still inside a luxury mirrored elevator; the doors slowly slide open and {objects, e.g. roses, balloons, butterflies || roses, balloons, butterflies} cascade out and fill the space, soft cinematic light, the subject stays completely frozen, editorial",
      negativePrompt: "subject moving, identity change, distorted face, deformed features, camera movement, warping, morphing, flickering, jitter, stutter, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/pov-skydive",
    name: "POV Skydive",
    description: "First-person freefall over a place.",
    group: "Viral & Effects",
    data: {
      provider: "kling-3.0",
      aspectRatio: "9:16",
      duration: 5,
      prompt: "first-person POV skydiving freefall over {location || a sweeping tropical coastline}, the ground far below rushing closer, clouds and wind streaking past, wide action-cam lens, exhilarating",
      negativePrompt: "warping, morphing, flickering, jitter, violent shake, stutter, motion sickness wobble, visible body or hands, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
  {
    id: "generate-video/underwater-pov",
    name: "Underwater POV",
    description: "First-person dive, sunbeams + bubbles.",
    group: "Viral & Effects",
    data: {
      provider: "veo3.1",
      aspectRatio: "9:16",
      duration: 8,
      prompt: "first-person POV diving underwater toward {subject || a sunken coral reef teeming with fish}, shafts of sunlight piercing the deep blue, drifting bubbles and gentle currents, serene and immersive",
      negativePrompt: "warping, morphing, flickering, jitter, violent shake, stutter, motion sickness wobble, visible body or hands, murky muddy water, distorted anatomy, extra limbs, low quality, blurry, artifacts, watermark, text",
    },
  },
]
