import type { FactoryPreset } from "./types.js"

export const GENERATE_MUSIC_PRESETS: readonly FactoryPreset[] = [
  // ── By Use-Case ──────────────────────────────────────────────────────────
  {
    id: "generate-music/lofi-study",
    name: "Lo-fi Study Beat",
    description: "Mellow focus beat.",
    group: "By Use-Case",
    data: {
      genre: "lofi",
      mood: "chill, relaxed, nostalgic",
      instrumental: true,
      duration: 30,
      prompt: "lo-fi hip-hop study beat, mellow Rhodes piano, vinyl crackle, soft boom-bap drums, around 75 BPM",
    },
  },
  {
    id: "generate-music/podcast-intro",
    name: "Podcast Intro",
    description: "Short energetic opener.",
    group: "By Use-Case",
    data: {
      genre: "electronic",
      mood: "upbeat, confident",
      instrumental: true,
      duration: 15,
      prompt: "short energetic podcast intro, modern and catchy synth hook, clean punchy beat",
    },
  },
  {
    id: "generate-music/cinematic-trailer",
    name: "Cinematic Trailer",
    description: "Epic orchestral build.",
    group: "By Use-Case",
    data: {
      genre: "cinematic",
      mood: "epic, dramatic, intense",
      instrumental: true,
      duration: 30,
      prompt: "epic cinematic trailer cue, full orchestra, taiko drums, brass swells, rising tension into a powerful hit",
    },
  },
  {
    id: "generate-music/corporate-upbeat",
    name: "Corporate Upbeat",
    description: "Bright, motivational bed.",
    group: "By Use-Case",
    data: {
      genre: "pop",
      mood: "uplifting, optimistic, motivational",
      instrumental: true,
      duration: 30,
      prompt: "upbeat corporate background music, bright piano, claps, positive and clean, around 120 BPM",
    },
  },
  {
    id: "generate-music/vlog-background",
    name: "Vlog Background",
    description: "Feel-good, unobtrusive.",
    group: "By Use-Case",
    data: {
      genre: "pop",
      mood: "happy, light, breezy",
      instrumental: true,
      duration: 30,
      prompt: "light feel-good vlog background, acoustic guitar, claps, warm and unobtrusive",
    },
  },
  {
    id: "generate-music/ambient-loop",
    name: "Ambient Loop",
    description: "Calm evolving soundscape.",
    group: "By Use-Case",
    data: {
      genre: "ambient-genre",
      mood: "calm, peaceful, serene",
      instrumental: true,
      duration: 30,
      prompt: "ambient soundscape, soft evolving synth pads, gentle textures, meditative and seamless",
    },
  },
  {
    id: "generate-music/edm-drop",
    name: "EDM Drop",
    description: "Festival build and drop.",
    group: "By Use-Case",
    data: {
      genre: "electronic",
      mood: "euphoric, energetic",
      instrumental: true,
      duration: 30,
      prompt: "festival EDM, big synth leads, sidechain bass, build-up and a powerful drop, around 128 BPM",
    },
  },
  {
    id: "generate-music/game-loop",
    name: "Game Loop",
    description: "Catchy adventurous loop.",
    group: "By Use-Case",
    data: {
      genre: "video-game",
      mood: "playful, adventurous",
      instrumental: true,
      duration: 30,
      prompt: "looping video game background music, chiptune-inspired, catchy melody, energetic",
    },
  },

  // ── By Mood / Score (instrumental scoring beds) ──────────────────────────
  {
    id: "generate-music/score-uplifting",
    name: "Uplifting",
    description: "Hopeful, building score.",
    group: "By Mood / Score",
    data: {
      genre: "cinematic",
      mood: "uplifting, hopeful, inspiring",
      instrumental: true,
      duration: 30,
      prompt: "uplifting inspirational orchestral score, building piano and strings, hopeful crescendo",
    },
  },
  {
    id: "generate-music/score-emotional",
    name: "Emotional",
    description: "Tender, moving piano.",
    group: "By Mood / Score",
    data: {
      genre: "cinematic",
      mood: "emotional, melancholic, tender",
      instrumental: true,
      duration: 30,
      prompt: "emotional piano score, soft strings, intimate and moving, slow tempo",
    },
  },
  {
    id: "generate-music/score-tense",
    name: "Tense / Suspense",
    description: "Pulsing underscore.",
    group: "By Mood / Score",
    data: {
      genre: "cinematic",
      mood: "tense, suspenseful, dark",
      instrumental: true,
      duration: 30,
      prompt: "suspenseful underscore, pulsing low strings, ticking tension, ominous and building",
    },
  },
  {
    id: "generate-music/score-epic",
    name: "Epic / Heroic",
    description: "Triumphant, powerful.",
    group: "By Mood / Score",
    data: {
      genre: "cinematic",
      mood: "epic, heroic, powerful",
      instrumental: true,
      duration: 30,
      prompt: "epic heroic orchestral score, soaring brass, pounding drums, triumphant",
    },
  },
  {
    id: "generate-music/score-happy",
    name: "Happy / Playful",
    description: "Cheerful and light.",
    group: "By Mood / Score",
    data: {
      genre: "pop",
      mood: "happy, playful, quirky",
      instrumental: true,
      duration: 30,
      prompt: "happy playful tune, ukulele, whistling, claps, cheerful and bouncy",
    },
  },
  {
    id: "generate-music/score-dark",
    name: "Dark / Brooding",
    description: "Ominous atmosphere.",
    group: "By Mood / Score",
    data: {
      genre: "electronic",
      mood: "dark, brooding, ominous",
      instrumental: true,
      duration: 30,
      prompt: "dark brooding atmosphere, deep drones, distant percussion, cinematic dread",
    },
  },
  {
    id: "generate-music/score-romantic",
    name: "Romantic",
    description: "Warm, heartfelt.",
    group: "By Mood / Score",
    data: {
      genre: "classical",
      mood: "romantic, warm, tender",
      instrumental: true,
      duration: 30,
      prompt: "romantic score, warm strings and piano, gentle and heartfelt",
    },
  },

  // ── By Genre (starting points) ───────────────────────────────────────────
  {
    id: "generate-music/ambient-cinematic",
    name: "Ambient Cinematic",
    description: "Atmospheric instrumental bed.",
    group: "By Genre",
    data: {
      genre: "cinematic",
      mood: "atmospheric",
      instrumental: true,
      duration: 30,
      prompt: "atmospheric cinematic ambient bed, evolving pads, subtle swells",
    },
  },
  {
    id: "generate-music/genre-lofi",
    name: "Lo-fi Hip-Hop",
    description: "Laid-back jazzy beat.",
    group: "By Genre",
    data: {
      genre: "lofi",
      mood: "chill, mellow",
      instrumental: true,
      duration: 30,
      prompt: "lo-fi hip-hop, jazzy chords, vinyl warmth, laid-back groove",
    },
  },
  {
    id: "generate-music/genre-edm",
    name: "EDM / House",
    description: "Club-energy four-on-the-floor.",
    group: "By Genre",
    data: {
      genre: "electronic",
      mood: "energetic, euphoric",
      instrumental: true,
      duration: 30,
      prompt: "house / EDM, four-on-the-floor beat, catchy plucky synths, club energy",
    },
  },
  {
    id: "generate-music/genre-rock",
    name: "Rock",
    description: "Driving electric guitars.",
    group: "By Genre",
    data: {
      genre: "rock",
      mood: "energetic, driving",
      instrumental: true,
      duration: 30,
      prompt: "energetic rock instrumental, distorted electric guitars, driving drums, powerful",
    },
  },
  {
    id: "generate-music/genre-jazz",
    name: "Smooth Jazz",
    description: "Late-night sax and brushes.",
    group: "By Genre",
    data: {
      genre: "jazz",
      mood: "smooth, relaxed, sophisticated",
      instrumental: true,
      duration: 30,
      prompt: "smooth jazz, warm saxophone, brushed drums, walking bass, late-night mood",
    },
  },
  {
    id: "generate-music/genre-orchestral",
    name: "Orchestral",
    description: "Grand cinematic ensemble.",
    group: "By Genre",
    data: {
      genre: "classical",
      mood: "grand, cinematic",
      instrumental: true,
      duration: 30,
      prompt: "full orchestral piece, sweeping strings, brass and woodwinds, dramatic and rich",
    },
  },
  {
    id: "generate-music/genre-synthwave",
    name: "Synthwave / Retro",
    description: "80s neon nostalgia.",
    group: "By Genre",
    data: {
      genre: "electronic",
      mood: "nostalgic, retro, cool",
      instrumental: true,
      duration: 30,
      prompt: "80s synthwave, retro analog synths, pulsing bass, neon nostalgia, around 110 BPM",
    },
  },
  {
    id: "generate-music/genre-funk",
    name: "Funk / Soul",
    description: "Groovy, danceable.",
    group: "By Genre",
    data: {
      genre: "funk",
      mood: "groovy, fun",
      instrumental: true,
      duration: 30,
      prompt: "funky groove, slap bass, wah guitar, tight horns, danceable",
    },
  },
  // ── More By Use-Case ─────────────────────────────────────────────────────
  {
    id: "generate-music/trailer-riser",
    name: "Trailer Riser / Braam",
    description: "Pure rising tension hit.",
    group: "By Use-Case",
    data: { genre: "cinematic", mood: "tense, building", instrumental: true, duration: 15, prompt: "cinematic trailer riser and braam hit, rising tension whoosh into a deep impact, no melody" },
  },
  {
    id: "generate-music/calm-corporate",
    name: "Calm Corporate / Tech",
    description: "Soft, professional bed.",
    group: "By Use-Case",
    data: { genre: "electronic", mood: "calm, professional", instrumental: true, duration: 30, prompt: "calm corporate tech bed, soft synth pads, gentle pulse, steady and unobtrusive" },
  },
  {
    id: "generate-music/holiday",
    name: "Holiday / Festive",
    description: "Warm seasonal cheer.",
    group: "By Use-Case",
    data: { genre: "holiday", mood: "festive, warm, cheerful", instrumental: true, duration: 30, prompt: "festive holiday music, sleigh bells, warm orchestration, cheerful and cozy" },
  },
  {
    id: "generate-music/kids",
    name: "Kids / Children's",
    description: "Playful and simple.",
    group: "By Use-Case",
    data: { genre: "children", mood: "playful, happy", instrumental: true, duration: 30, prompt: "playful children's music, simple cheerful melody, xylophone and ukulele, bouncy and friendly" },
  },
  {
    id: "generate-music/meditation-spa",
    name: "Meditation / Spa",
    description: "Healing singing bowls.",
    group: "By Use-Case",
    data: { genre: "ambient-genre", mood: "serene, healing", instrumental: true, duration: 30, prompt: "meditation and spa music, singing bowls, soft drones, gentle and calming, very slow" },
  },
  {
    id: "generate-music/workout",
    name: "Workout / Gym",
    description: "High-energy motivation.",
    group: "By Use-Case",
    data: { genre: "electronic", mood: "energetic, motivational", instrumental: true, duration: 30, prompt: "high-energy workout music, driving beat, motivational synths, around 140 BPM" },
  },
  // ── More By Genre ────────────────────────────────────────────────────────
  {
    id: "generate-music/trap",
    name: "Trap Beat",
    description: "Booming 808s, dark.",
    group: "By Genre",
    data: { genre: "hip-hop", mood: "dark, hard", instrumental: true, duration: 30, prompt: "trap beat, booming 808s, crisp rapid hi-hats, dark and moody" },
  },
  {
    id: "generate-music/dnb",
    name: "Drum & Bass",
    description: "Fast breakbeats, deep bass.",
    group: "By Genre",
    data: { genre: "electronic", mood: "fast, energetic", instrumental: true, duration: 30, prompt: "drum and bass, fast breakbeats, deep rolling bassline, energetic, around 174 BPM" },
  },
  {
    id: "generate-music/afrobeats",
    name: "Afrobeats",
    description: "Warm syncopated groove.",
    group: "By Genre",
    data: { genre: "afrobeats", mood: "groovy, warm", instrumental: true, duration: 30, prompt: "afrobeats, syncopated percussion, warm bass groove, bright melodies, danceable" },
  },
  {
    id: "generate-music/country",
    name: "Country / Americana",
    description: "Acoustic, heartfelt.",
    group: "By Genre",
    data: { genre: "country", mood: "warm, heartfelt", instrumental: true, duration: 30, prompt: "country americana, acoustic and slide guitar, warm storytelling feel" },
  },
  {
    id: "generate-music/phonk",
    name: "Phonk",
    description: "Dark drift-phonk for reels.",
    group: "By Genre",
    data: { genre: "hip-hop", mood: "dark, aggressive", instrumental: true, duration: 30, prompt: "drift phonk, distorted 808 cowbell, dark menacing beat, lo-fi grit" },
  },
  {
    id: "generate-music/reggae",
    name: "Reggae / Dub",
    description: "Laid-back island groove.",
    group: "By Genre",
    data: { genre: "reggae", mood: "laid-back, sunny", instrumental: true, duration: 30, prompt: "reggae dub, off-beat skank guitar, deep dub bassline, relaxed island groove" },
  },
]

export const SUNO_GENERATE_PRESETS: readonly FactoryPreset[] = [
  // ── By Use-Case ──────────────────────────────────────────────────────────
  {
    id: "suno-generate/lofi-study",
    name: "Lo-fi Study",
    description: "Mellow focus beat.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "lo-fi hip-hop, chill and mellow, jazzy Rhodes chords, vinyl crackle, soft boom-bap drums, Andante 80 BPM, instrumental",
    },
  },
  {
    id: "suno-generate/podcast-intro",
    name: "Podcast Intro",
    description: "Short confident opener.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "modern podcast intro, upbeat and confident, catchy synth hook, punchy beat, Allegro, instrumental",
    },
  },
  {
    id: "suno-generate/cinematic-trailer",
    name: "Cinematic Trailer",
    description: "Epic orchestral build.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "epic cinematic trailer, dramatic and intense, full orchestra, taiko drums, brass swells, crescendo into a powerful hit, instrumental",
    },
  },
  {
    id: "suno-generate/corporate-upbeat",
    name: "Corporate Upbeat",
    description: "Bright, motivational.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "upbeat corporate, optimistic and motivational, bright piano, claps, clean electronic beat, Allegro 120 BPM, instrumental",
    },
  },
  {
    id: "suno-generate/vlog-background",
    name: "Vlog Background",
    description: "Feel-good acoustic bed.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "feel-good vlog background, light and breezy, acoustic guitar, claps, warm and unobtrusive, Andante, instrumental",
    },
  },
  {
    id: "suno-generate/ambient-loop",
    name: "Ambient Loop",
    description: "Calm meditative pads.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "ambient soundscape, calm and meditative, soft evolving synth pads, gentle textures, reverb-heavy, Adagio, instrumental",
    },
  },
  {
    id: "suno-generate/edm-drop",
    name: "EDM Drop",
    description: "Festival build and drop.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "festival EDM, euphoric and energetic, big supersaw leads, sidechain bass, build-up and powerful drop, Allegro 128 BPM, instrumental",
    },
  },
  {
    id: "suno-generate/game-chiptune",
    name: "Game Chiptune",
    description: "Playful 8-bit loop.",
    group: "By Use-Case",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "video game chiptune, playful and adventurous, 8-bit synths, catchy melody, energetic, instrumental",
    },
  },

  // ── By Genre ─────────────────────────────────────────────────────────────
  {
    id: "suno-generate/genre-lofi",
    name: "Lo-fi Hip-Hop",
    description: "Dusty laid-back groove.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "lo-fi hip-hop, jazzy and mellow, dusty Rhodes chords, vinyl warmth, laid-back boom-bap groove, instrumental",
    },
  },
  {
    id: "suno-generate/genre-house",
    name: "EDM / House",
    description: "Club-energy four-on-the-floor.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "house EDM, energetic and euphoric, four-on-the-floor beat, catchy plucky synths, club energy, Allegro 124 BPM, instrumental",
    },
  },
  {
    id: "suno-generate/genre-rock",
    name: "Rock",
    description: "Driving anthemic guitars.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "rock anthem, energetic and driving, distorted electric guitars, pounding drums, anthemic, instrumental",
    },
  },
  {
    id: "suno-generate/genre-jazz",
    name: "Smooth Jazz",
    description: "Late-night sophistication.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "smooth jazz, relaxed and sophisticated, warm saxophone, brushed drums, walking bass, late-night, instrumental",
    },
  },
  {
    id: "suno-generate/genre-ambient",
    name: "Ambient",
    description: "Spacious and serene.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "ambient, serene and spacious, lush synth pads, field-recording textures, slow and meditative, instrumental",
    },
  },
  {
    id: "suno-generate/genre-orchestral",
    name: "Orchestral",
    description: "Grand cinematic ensemble.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "epic orchestral, grand and cinematic, sweeping strings, brass, woodwinds, timpani, dramatic, instrumental",
    },
  },
  {
    id: "suno-generate/genre-synthwave",
    name: "Synthwave / Retro",
    description: "80s neon nostalgia.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "80s synthwave, nostalgic and cool, retro analog synths, pulsing bass, gated drums, neon, Andante 110 BPM, instrumental",
    },
  },
  {
    id: "suno-generate/genre-funk",
    name: "Funk / Soul",
    description: "Groovy and danceable.",
    group: "By Genre",
    data: {
      model: "V5_5",
      instrumental: true,
      style: "funk and soul, groovy and fun, slap bass, wah guitar, tight horn section, danceable, instrumental",
    },
  },

  // ── Vocals & Songs (add your lyrics) ─────────────────────────────────────
  {
    id: "suno-generate/song-pop",
    name: "Pop Song",
    description: "Catchy vocal pop — add lyrics.",
    group: "Vocals & Songs",
    data: {
      model: "V5_5",
      instrumental: false,
      style: "upbeat pop, catchy and bright, shimmering synths, four-on-the-floor, female vocals, Allegro 120 BPM, verse-chorus-verse with bridge",
    },
  },
  {
    id: "suno-generate/song-rap",
    name: "Rap / Hip-Hop",
    description: "Hard-hitting verses — add bars.",
    group: "Vocals & Songs",
    data: {
      model: "V5_5",
      instrumental: false,
      style: "modern hip-hop, confident, hard-hitting 808s, trap hi-hats, male rap vocals, verse-hook-verse",
    },
  },
  {
    id: "suno-generate/song-ballad",
    name: "Emotional Ballad",
    description: "Heartfelt vocals — add lyrics.",
    group: "Vocals & Songs",
    data: {
      model: "V5_5",
      instrumental: false,
      style: "emotional ballad, tender and heartfelt, piano and strings, soulful vocals, Adagio, verse-chorus with a big bridge",
    },
  },
  {
    id: "suno-generate/song-rock",
    name: "Rock Anthem (vocal)",
    description: "Soaring chorus — add lyrics.",
    group: "Vocals & Songs",
    data: {
      model: "V5_5",
      instrumental: false,
      style: "anthemic rock, powerful, driving guitars, big drums, male vocals, soaring chorus, verse-pre-chorus-chorus",
    },
  },
  {
    id: "suno-generate/song-acoustic",
    name: "Acoustic Singer-Songwriter",
    description: "Warm and intimate — add lyrics.",
    group: "Vocals & Songs",
    data: {
      model: "V5_5",
      instrumental: false,
      style: "acoustic singer-songwriter, warm and intimate, fingerpicked guitar, soft vocals, Andante, verse-chorus",
    },
  },
  // ── More By Use-Case ─────────────────────────────────────────────────────
  {
    id: "suno-generate/trailer-riser",
    name: "Trailer Riser / Braam",
    description: "Pure rising tension hit.",
    group: "By Use-Case",
    data: { model: "V5_5", instrumental: true, style: "cinematic trailer riser and braam, tense and building, rising whoosh into a deep brass impact, no melody, instrumental" },
  },
  {
    id: "suno-generate/calm-corporate",
    name: "Calm Corporate / Tech",
    description: "Soft, professional bed.",
    group: "By Use-Case",
    data: { model: "V5_5", instrumental: true, style: "calm corporate tech, professional and clean, soft synth pads, gentle pulse, Andante, instrumental" },
  },
  {
    id: "suno-generate/holiday",
    name: "Holiday / Festive",
    description: "Warm seasonal cheer.",
    group: "By Use-Case",
    data: { model: "V5_5", instrumental: true, style: "festive holiday music, warm and cheerful, sleigh bells, warm orchestration, cozy, instrumental" },
  },
  {
    id: "suno-generate/kids",
    name: "Kids / Children's",
    description: "Playful and simple.",
    group: "By Use-Case",
    data: { model: "V5_5", instrumental: true, style: "children's music, playful and happy, simple cheerful melody, xylophone and ukulele, bouncy, instrumental" },
  },
  {
    id: "suno-generate/meditation-spa",
    name: "Meditation / Spa",
    description: "Healing singing bowls.",
    group: "By Use-Case",
    data: { model: "V5_5", instrumental: true, style: "meditation and spa, serene and healing, singing bowls, soft drones, Adagio, reverb-heavy, instrumental" },
  },
  {
    id: "suno-generate/workout",
    name: "Workout / Gym",
    description: "High-energy motivation.",
    group: "By Use-Case",
    data: { model: "V5_5", instrumental: true, style: "high-energy workout, motivational and driving, pumping electronic beat, big synths, Allegro 140 BPM, instrumental" },
  },
  // ── More By Genre ────────────────────────────────────────────────────────
  {
    id: "suno-generate/trap",
    name: "Trap Beat",
    description: "Booming 808s, dark.",
    group: "By Genre",
    data: { model: "V5_5", instrumental: true, style: "trap beat, dark and hard, booming 808s, crisp rapid hi-hats, moody, instrumental" },
  },
  {
    id: "suno-generate/dnb",
    name: "Drum & Bass",
    description: "Fast breakbeats, deep bass.",
    group: "By Genre",
    data: { model: "V5_5", instrumental: true, style: "drum and bass, fast and energetic, breakbeats, deep rolling bassline, Presto 174 BPM, instrumental" },
  },
  {
    id: "suno-generate/afrobeats",
    name: "Afrobeats",
    description: "Warm syncopated groove.",
    group: "By Genre",
    data: { model: "V5_5", instrumental: true, style: "afrobeats, groovy and warm, syncopated percussion, warm bass, bright melodies, danceable, instrumental" },
  },
  {
    id: "suno-generate/country",
    name: "Country / Americana",
    description: "Acoustic, heartfelt.",
    group: "By Genre",
    data: { model: "V5_5", instrumental: true, style: "country americana, warm and heartfelt, acoustic and slide guitar, storytelling feel, instrumental" },
  },
  {
    id: "suno-generate/phonk",
    name: "Phonk",
    description: "Dark drift-phonk for reels.",
    group: "By Genre",
    data: { model: "V5_5", instrumental: true, style: "drift phonk, dark and aggressive, distorted 808 cowbell, menacing beat, lo-fi grit, instrumental" },
  },
  {
    id: "suno-generate/reggae",
    name: "Reggae / Dub",
    description: "Laid-back island groove.",
    group: "By Genre",
    data: { model: "V5_5", instrumental: true, style: "reggae dub, laid-back and sunny, off-beat skank guitar, deep dub bassline, relaxed island groove, instrumental" },
  },
  // ── More Vocals & Songs ──────────────────────────────────────────────────
  {
    id: "suno-generate/song-rnb",
    name: "R&B / Soul (vocal)",
    description: "Smooth soulful vocals — add lyrics.",
    group: "Vocals & Songs",
    data: { model: "V5_5", instrumental: false, style: "smooth R&B soul, sensual and warm, lush chords, soft drums, soulful vocals, Andante, verse-chorus with ad-libs" },
  },
  {
    id: "suno-generate/song-kpop",
    name: "K-Pop (vocal)",
    description: "Polished hook — add lyrics.",
    group: "Vocals & Songs",
    data: { model: "V5_5", instrumental: false, style: "K-pop, polished and energetic, bright synths, punchy drums, layered vocals, Allegro 120 BPM, verse-pre-chorus-chorus" },
  },
]
