/**
 * The node catalogue the add-node surfaces render.
 *
 * ONE list, deliberately. The popup and the sidebar used to keep private
 * copies and they drifted: same entries, different keywords, and after the
 * picker redesign different `group` values — so the two surfaces grouped the
 * same nodes under different headers. Both import from here now, which makes
 * that class of bug impossible rather than merely fixed.
 *
 * `group` carries the owning family id from `node-families.ts`. Render it
 * through `familyLabel()`; never print the raw value.
 */
import {
  Activity,
  AlignLeft,
  Aperture,
  Armchair,
  ArrowUpDown,
  ArrowUpFromLine,
  AudioLines,
  AudioWaveform,
  BookOpen,
  Box,
  Braces,
  Brush,
  Camera,
  Captions,
  Car,
  Clapperboard,
  Clock,
  CloudFog,
  CopyMinus,
  Cpu,
  Disc3,
  Download,
  Eraser,
  Eye,
  Facebook,
  FastForward,
  FileText,
  Film,
  Frame,
  Gauge,
  Gem,
  GitBranch,
  GitMerge,
  Globe,
  HandMetal,
  HardDrive,
  Hash,
  Hourglass,
  ImageIcon,
  Instagram,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Linkedin,
  List,
  ListFilter,
  ListMusic,
  ListTree,
  LogIn,
  LogOut,
  MapPin,
  Maximize,
  Merge,
  MessageCircle,
  MessageSquare,
  Mic,
  Mountain,
  Music,
  Package,
  PaintBucket,
  Paintbrush,
  Palette,
  PawPrint,
  PersonStanding,
  Piano,
  Puzzle,
  RatioIcon,
  RefreshCw,
  Repeat,
  Rss,
  ScanFace,
  ScanSearch,
  Scissors,
  SearchCheck,
  Send,
  Server,
  Shapes,
  Share2,
  ShieldCheck,
  SlidersHorizontal,
  Smile,
  Sparkles,
  StickyNote,
  SunDim,
  SwatchBook,
  Swords,
  Trophy,
  Twitter,
  Type,
  Upload,
  User,
  UserPlus,
  UserRound,
  Users,
  VenetianMask,
  Video,
  Volume2,
  VolumeX,
  Wand2,
  Waypoints,
  Webhook,
  Workflow,
  Youtube,
  Zap,
  ZoomIn,
} from "lucide-react"
import { hasCredits } from "@/lib/edition"
import { CLOUD_ONLY_NODE_TYPES } from "@/lib/cloud-only-nodes"
import type { NodeOption } from "@/lib/node-compatibility"
import type { SceneNodeType } from "@/types/nodes"

export const NODE_OPTIONS: ReadonlyArray<NodeOption> = [
  // Input
  {
    type: "text-prompt",
    label: "Text",
    icon: <Type className="h-4 w-4" />,
    category: "Input",
    group: "automate-text",
    // Renamed from "Text Prompt" → "Text"; keep "prompt" searchable so users
    // who look for "prompt" still find this node.
    keywords: ["prompt", "text prompt"],
  },
  {
    type: "upload-image",
    label: "Upload Image",
    icon: <Upload className="h-4 w-4" />,
    category: "Input",
    group: "image-add-your-own",
  },
  {
    type: "upload-video",
    label: "Upload Video",
    icon: <Video className="h-4 w-4" />,
    category: "Input",
    group: "video-add-your-own",
  },
  {
    type: "upload-audio",
    label: "Upload Audio",
    icon: <Music className="h-4 w-4" />,
    category: "Input",
    group: "audio-add-your-own",
  },
  // Hidden — uncomment to restore in the Add Node UI:
  // {
  //   type: "rss-feed",
  //   label: "RSS Feed",
  //   icon: <Rss className="h-4 w-4" />,
  //   category: "Input",
  // },
  {
    type: "youtube-video",
    label: "Video URL",
    icon: <Video className="h-4 w-4" />,
    category: "Input",
    group: "automate-get-content",
  },
  {
    type: "reference-audio",
    label: "Reference Audio",
    icon: <Music className="h-4 w-4" />,
    category: "Input",
    group: "audio-add-your-own",
  },
  // Triggers
  {
    type: "webhook-trigger" as const,
    label: "Webhook Trigger",
    icon: <Webhook className="h-4 w-4" />,
    category: "Triggers",
    group: "automate-triggers",
  },
  {
    type: "schedule-trigger" as const,
    label: "Schedule Trigger",
    group: "automate-triggers",
    icon: <Clock className="h-4 w-4" />,
    category: "Triggers",
  },
  {
    type: "telegram-trigger",
    label: "Telegram Trigger",
    icon: <Send className="h-4 w-4" />,
    category: "Triggers",
    group: "automate-triggers",
  },
  {
    type: "telegram-channel-feed",
    label: "Telegram Channel Feed",
    icon: <Rss className="h-4 w-4" />,
    category: "Input",
    group: "automate-get-content",
    keywords: ["telegram", "channel", "feed", "monitor", "follow", "scrape", "rss"],
  },
  // Data
  {
    type: "list",
    label: "List",
    icon: <List className="h-4 w-4" />,
    category: "Data",
    group: "automate-lists",
  },
  {
    type: "web-scrape",
    label: "Web Scrape",
    icon: <Globe className="h-4 w-4" />,
    category: "Data",
    group: "automate-get-content",
  },
  // Hidden — uncomment to restore in the Add Node UI:
  // {
  //   type: "json-process",  // note: re-add the Filter icon import if restored
  //   label: "JSON Process",
  //   icon: <Filter className="h-4 w-4" />,
  //   category: "Data",
  // },
  {
    type: "extract-field",
    label: "Extract Field",
    icon: <Braces className="h-4 w-4" />,
    category: "Data",
    group: "automate-logic",
  },
  {
    type: "filter-list",
    label: "Filter List",
    icon: <ListFilter className="h-4 w-4" />,
    category: "Data",
    group: "automate-lists",
  },
  {
    type: "deduplicate",
    label: "Remove Duplicates",
    icon: <CopyMinus className="h-4 w-4" />,
    category: "Data",
    group: "automate-lists",
  },
  {
    type: "merge-lists",
    label: "Merge Lists",
    icon: <GitMerge className="h-4 w-4" />,
    category: "Data",
    group: "automate-lists",
  },
  {
    type: "sort-list",
    label: "Sort List",
    icon: <ArrowUpDown className="h-4 w-4" />,
    category: "Data",
    group: "automate-lists",
  },
  {
    type: "selector",
    label: "Selector",
    icon: <ListTree className="h-4 w-4" />,
    category: "Data",
    group: "automate-lists",
  },
  // Parameter
  {
    type: "tone",
    label: "Tone",
    icon: <Palette className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "style-guide",
    label: "Style Guide",
    icon: <PaintBucket className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "provider",
    label: "Provider",
    icon: <Server className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "scene-count",
    label: "Scene Count",
    icon: <Hash className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "duration",
    label: "Duration",
    icon: <Clock className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "aspect-ratio",
    label: "Aspect Ratio",
    icon: <RatioIcon className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "motion",
    label: "Motion",
    icon: <SlidersHorizontal className="h-4 w-4" />,
    category: "Parameter",
    group: "models-generation-settings",
  },
  {
    type: "camera-motion",
    label: "Camera Motion",
    icon: <Video className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-motion-time",
    keywords: ["camera", "shot", "movement", "orbit", "pan", "tilt", "dolly", "crane", "zoom"],
  },
  {
    type: "transition",
    label: "Transition",
    icon: <GitBranch className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-effects",
    keywords: ["transition", "cut", "dissolve", "fade", "wipe", "morph", "blend", "cross", "scene change"],
  },
  {
    type: "framing",
    label: "Framing",
    icon: <Frame className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-camera",
    keywords: ["camera", "shot", "composition", "close-up", "wide", "angle", "vantage"],
  },
  {
    type: "lens",
    label: "Lens",
    icon: <Aperture className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-camera",
    keywords: ["camera", "optics", "focal length", "bokeh", "depth of field", "anamorphic", "fisheye"],
  },
  {
    type: "camera-format",
    label: "Camera / Film Stock",
    icon: <Film className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-camera",
    keywords: ["camera", "film", "35mm", "super 8", "vhs", "imax", "stock", "format"],
  },
  {
    type: "lighting",
    label: "Lighting",
    icon: <Lightbulb className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["light", "rembrandt", "chiaroscuro", "golden hour", "key", "rim", "shot"],
  },
  {
    type: "color-look",
    label: "Color / Look",
    icon: <SwatchBook className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["color", "grade", "palette", "lut", "kodak", "fuji", "teal orange", "shot"],
  },
  {
    type: "atmosphere",
    label: "Atmosphere",
    icon: <CloudFog className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["weather", "fog", "rain", "snow", "smoke", "god rays", "particles", "shot"],
  },
  {
    type: "action-fx",
    label: "Action FX",
    icon: <Zap className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-effects",
    keywords: ["explosion", "lightning", "storm", "earthquake", "fire", "laser", "magic", "blast", "fx", "vfx", "action", "shockwave", "force field", "sci-fi"],
  },
  {
    type: "character-fx",
    label: "Character FX",
    icon: <Sparkles className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-effects",
    keywords: ["character", "fx", "effect", "expression", "emotion", "gesture", "blink", "wink", "laugh", "cry", "smile", "frown", "shiver", "tremble", "gasp", "reaction"],
  },
  {
    type: "style",
    label: "Style",
    icon: <Brush className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["anime", "oil painting", "watercolor", "cinematic", "photorealistic", "comic", "pixel art", "pop art", "noir", "illustration", "rendering"],
  },
  {
    type: "setting",
    label: "Setting",
    icon: <Mountain className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["place", "environment", "location", "scene", "forest", "cafe", "alley", "cathedral", "desert", "cyberpunk", "fantasy", "indoor", "urban", "nature"],
  },
  {
    type: "loop-subject",
    label: "Loop Subject",
    icon: <Sparkles className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["loop", "loopable", "seamless", "tunnel", "kaleidoscope", "fractal", "aurora", "particle", "vj", "background", "perfect loop", "veo loop"],
  },
  {
    type: "person",
    label: "Person",
    icon: <UserRound className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-subject",
    keywords: ["subject", "character", "people", "human", "gender", "age", "ethnicity", "hair", "skin", "eyes", "build", "man", "woman", "child", "beard", "mustache"],
  },
  {
    type: "mood",
    label: "Mood",
    icon: <Smile className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["emotion", "expression", "feeling", "happy", "sad", "angry", "serene", "fierce", "brooding", "confident", "melancholy", "mysterious"],
  },
  {
    type: "photographer",
    label: "Photographer / Artist Style",
    icon: <Camera className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["photographer", "artist", "style", "tim walker", "deakins", "lubezki", "fashion", "editorial", "cinematographer", "illustrator", "painter", "ghibli", "rutkowski", "leibovitz", "cartier-bresson"],
  },
  {
    type: "aesthetic",
    label: "Aesthetic / Microtrend",
    icon: <Sparkles className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["aesthetic", "microtrend", "core", "y2k", "cottagecore", "dark academia", "techwear", "gorpcore", "old money", "preppy", "streetwear", "coquette", "indie sleaze", "balletcore", "goblincore", "minimalism", "maximalism", "vibe"],
  },
  {
    type: "era",
    label: "Era / Period",
    icon: <Hourglass className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["era", "period", "decade", "1920s", "1950s", "1970s", "1980s", "1990s", "2000s", "victorian", "medieval", "renaissance", "wild west", "feudal japan", "cyberpunk", "post-apocalyptic", "retrofuturism", "dieselpunk", "atompunk", "vintage", "future"],
  },
  {
    type: "pose",
    label: "Pose",
    icon: <PersonStanding className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-wardrobe-pose",
    keywords: ["pose", "posture", "action", "stance", "standing", "sitting", "running", "walking", "dancing", "jumping", "fighting", "body", "position"],
  },
  {
    type: "styling",
    label: "Styling",
    icon: <Gem className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-wardrobe-pose",
    keywords: ["beauty", "makeup", "glamour", "smoky eye", "lipstick", "eyewear", "sunglasses", "aviators", "headwear", "hat", "beanie", "fedora", "jewelry", "necklace", "earrings", "nails", "manicure", "face paint", "fabric", "silk", "leather", "denim", "velvet", "satin", "lace"],
  },
  {
    type: "material",
    label: "Material",
    icon: <Layers className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["material", "fabric", "metal", "stone", "wood", "glass", "silk", "leather", "chrome", "marble", "gold", "silver", "bronze", "velvet", "porcelain", "crystal", "holographic", "iridescent", "neon", "made of"],
  },
  {
    type: "animal",
    label: "Animal",
    icon: <PawPrint className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-subject",
    keywords: ["animal", "cat", "dog", "bird", "fish", "horse", "lion", "tiger", "bear", "wolf", "fox", "elephant", "pet", "wildlife", "dinosaur", "dragon"],
  },
  {
    type: "vehicle",
    label: "Vehicle",
    icon: <Car className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-subject",
    keywords: ["vehicle", "car", "truck", "motorcycle", "bike", "boat", "plane", "helicopter", "tank", "spaceship", "muscle", "classic", "sports", "transport"],
  },
  {
    type: "weapon",
    label: "Weapon",
    icon: <Swords className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-subject",
    keywords: ["weapon", "sword", "katana", "gun", "rifle", "pistol", "bow", "dagger", "axe", "spear", "mace", "crossbow", "firearm", "blade"],
  },
  {
    type: "furniture",
    label: "Furniture",
    icon: <Armchair className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["furniture", "chair", "sofa", "couch", "table", "desk", "bed", "lamp", "cabinet", "shelf", "wardrobe", "stool"],
  },
  {
    type: "photo-genre",
    label: "Photo Genre",
    icon: <Camera className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["photo", "genre", "intent", "paparazzi", "editorial", "vogue", "lookbook", "selfie", "mirror selfie", "gym selfie", "headshot", "mugshot", "passport", "yearbook", "wedding", "movie poster", "album cover", "advertising", "documentary", "snapshot", "noir"],
  },
  {
    type: "backdrop",
    label: "Backdrop",
    icon: <LayoutDashboard className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["backdrop", "background", "studio", "seamless", "wall", "gradient", "muslin", "velvet", "halo", "bokeh", "vignette", "white seamless", "black seamless", "brick wall", "concrete"],
  },
  {
    type: "held-prop",
    label: "Held Prop",
    icon: <HandMetal className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-scene",
    keywords: ["prop", "hand", "holding", "phone", "cigarette", "coffee", "wine", "microphone", "book", "umbrella", "bouquet", "guitar", "katana", "drink", "smoking", "instrument", "bag"],
  },
  {
    type: "temporal",
    label: "Temporal",
    icon: <Clock className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-motion-time",
    keywords: ["time", "speed", "slow motion", "freeze", "bullet time", "shutter", "shot"],
  },
  {
    type: "exposure-settings",
    label: "Exposure Settings",
    icon: <Aperture className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-camera",
    keywords: ["exposure", "aperture", "f-stop", "shutter", "iso", "depth of field", "bokeh", "grain", "long exposure", "freeze"],
  },
  {
    type: "render-quality",
    label: "Render Quality",
    icon: <Cpu className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-light-look",
    keywords: ["render", "engine", "unreal", "octane", "cycles", "raytracing", "pbr", "8k", "4k", "masterpiece", "raw", "award-winning", "lumen", "global illumination"],
  },
  {
    type: "composition-effects",
    label: "Composition Effects",
    icon: <Wand2 className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-effects",
    keywords: ["composition", "frame", "burst", "shatter", "smoke", "liquid", "pixel", "particles", "glitch", "mosaic", "silhouette", "exploding", "fragment", "glass", "trick"],
  },
  {
    type: "post-process-effects",
    label: "Post-Process Effects",
    icon: <Sparkles className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-effects",
    keywords: ["post", "grade", "vignette", "grain", "halation", "bloom", "chromatic aberration", "light leak", "film burn", "scratched", "diffusion", "contrast", "glow"],
  },
  // Sound
  {
    type: "music-genre",
    label: "Music Genre",
    icon: <Music className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-music-voice",
    keywords: ["music", "genre", "rock", "pop", "electronic"],
  },
  {
    type: "music-mood",
    label: "Music Mood",
    icon: <Activity className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-music-voice",
    keywords: ["music", "mood", "energy", "emotion", "vibe"],
  },
  {
    type: "instrumentation",
    label: "Instrumentation",
    icon: <Piano className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-music-voice",
    keywords: ["instruments", "guitar", "piano", "drums"],
  },
  {
    type: "voice-character",
    label: "Voice Character",
    icon: <User className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-music-voice",
    keywords: ["voice", "age", "gender", "accent", "timbre", "character"],
  },
  {
    type: "voice-delivery",
    label: "Voice Delivery",
    icon: <MessageCircle className="h-4 w-4" />,
    category: "Pickers",
    group: "cc-music-voice",
    keywords: ["voice", "pace", "emotion", "narrator", "delivery"],
  },
  // AI — Script & Text
  {
    type: "generate-script",
    label: "Generate Script",
    icon: <BookOpen className="h-4 w-4" />,
    category: "AI",
    group: "video-story-script",
  },
  {
    type: "llm-chat",
    label: "Generate Text",
    icon: <MessageSquare className="h-4 w-4" />,
    category: "AI",
    group: "automate-text",
  },
  {
    type: "transcribe",
    label: "Transcribe",
    icon: <FileText className="h-4 w-4" />,
    category: "AI",
    group: "audio-transcribe",
  },
  // AI — Image
  {
    type: "generate-image",
    label: "Generate Image",
    icon: <ImageIcon className="h-4 w-4" />,
    category: "AI",
    group: "image-create",
  },
  {
    type: "modify-image",
    label: "Modify Image",
    icon: <Layers className="h-4 w-4" />,
    category: "AI",
    group: "image-edit-retouch",
  },
  {
    type: "upscale-image",
    label: "Upscale Image",
    icon: <ZoomIn className="h-4 w-4" />,
    category: "AI",
    group: "image-edit-retouch",
  },
  {
    type: "remove-background",
    label: "Remove Background",
    icon: <Eraser className="h-4 w-4" />,
    category: "AI",
    group: "image-edit-retouch",
  },
  {
    type: "generate-mask",
    label: "Generate Mask",
    icon: <VenetianMask className="h-4 w-4" />,
    category: "AI",
    group: "image-edit-retouch",
  },
  {
    type: "paint-mask",
    label: "Paint Mask",
    icon: <Paintbrush className="h-4 w-4" />,
    category: "Processing",
    group: "image-edit-retouch",
    keywords: ["mask", "paint", "brush", "inpaint", "matte", "hand", "draw"],
  },
  {
    type: "reference-sheet",
    label: "Reference Sheet",
    icon: <LayoutGrid className="h-4 w-4" />,
    category: "AI",
    group: "image-references",
    keywords: ["sheet", "reference", "turnaround", "character sheet", "model sheet"],
  },
  {
    type: "reference-board",
    label: "Reference Board",
    icon: <LayoutGrid className="h-4 w-4" />,
    category: "AI",
    group: "image-references",
    keywords: ["board", "reference", "palette", "hero", "panels", "reference board"],
  },
  {
    type: "image-to-text",
    label: "Describe Image",
    icon: <Eye className="h-4 w-4" />,
    category: "AI",
    group: "image-understand",
  },
  {
    type: "describe-to-picker",
    label: "Describe to Picker",
    icon: <ScanFace className="h-4 w-4" />,
    category: "AI",
    group: "image-understand",
  },
  // AI — Video
  {
    type: "generate-video",
    label: "Generate Video",
    icon: <Clapperboard className="h-4 w-4" />,
    category: "AI",
    group: "video-create",
    keywords: ["image-to-video", "text-to-video", "i2v", "t2v", "video"],
  },
  {
    type: "generate-video-pro",
    label: "Generate Video Pro",
    icon: <Clapperboard className="h-4 w-4" />,
    category: "AI",
    group: "video-create",
    keywords: ["long-form", "long video", "multi-segment", "stitch", "extended duration", "seedance", "pro"],
  },
  {
    type: "edit-video-pro",
    label: "Edit Video Pro",
    icon: <Scissors className="h-4 w-4" />,
    category: "AI",
    group: "video-continue-restyle",
    keywords: ["retake", "replace span", "edit clip", "seedance", "pro", "reshoot"],
  },
  {
    type: "video-to-video",
    label: "Video to Video",
    icon: <Film className="h-4 w-4" />,
    category: "AI",
    group: "video-continue-restyle",
  },
  {
    type: "switchx",
    label: "Relight & Switch",
    icon: <Wand2 className="h-4 w-4" />,
    category: "AI",
    group: "video-continue-restyle",
    keywords: ["relight", "relighting", "relit", "lighting", "switch", "swap background", "replace background", "change background", "scene swap", "restyle", "recolor", "composite", "compositing", "green screen", "chroma key", "rotoscope", "matte", "alpha", "color match", "harmonize", "vfx", "video to video", "beeble"],
  },
  {
    type: "generative-pipeline",
    label: "Story → Video",
    icon: <Film className="h-4 w-4" />,
    category: "AI",
    group: "video-story-script",
    keywords: ["story", "pipeline", "trailer", "short film", "music video", "reel", "commercial", "cinematic"],
  },
  {
    type: "ai-avatar",
    label: "AI Avatar",
    icon: <UserRound className="h-4 w-4" />,
    category: "AI",
    group: "video-animate-perform",
    keywords: ["heygen", "talking avatar", "avatar", "talking head", "voice", "tts"],
  },
  {
    type: "cinematic-avatar",
    label: "Cinematic Avatar",
    icon: <Clapperboard className="h-4 w-4" />,
    category: "AI",
    group: "video-animate-perform",
    keywords: ["heygen", "cinematic", "avatar", "generative", "prompt", "looks", "seedance"],
  },
  {
    type: "lip-sync",
    label: "Lip Sync",
    icon: <Users className="h-4 w-4" />,
    category: "AI",
    group: "video-animate-perform",
  },
  {
    type: "speech-to-video",
    label: "Speech to Video",
    icon: <AudioLines className="h-4 w-4" />,
    category: "AI",
    group: "video-animate-perform",
  },
  {
    type: "motion-transfer",
    label: "Motion Transfer",
    icon: <Waypoints className="h-4 w-4" />,
    category: "AI",
    group: "video-animate-perform",
  },
  {
    type: "extend-video",
    label: "Extend Video",
    icon: <FastForward className="h-4 w-4" />,
    category: "AI",
    group: "video-continue-restyle",
  },
  {
    type: "video-retake",
    label: "Retake Video",
    icon: <Scissors className="h-4 w-4" />,
    category: "AI",
    group: "video-continue-restyle",
    keywords: ["retake", "replace audio", "replace video", "ltx", "ltx-2.3"],
  },
  {
    type: "face-swap",
    label: "Face Swap",
    icon: <ScanFace className="h-4 w-4" />,
    category: "AI",
    group: "video-animate-perform",
  },
  {
    type: "video-sfx",
    label: "Video SFX",
    icon: <AudioWaveform className="h-4 w-4" />,
    category: "AI",
    group: "video-sound",
    keywords: ["sfx", "foley", "sound effects", "mmaudio", "audio", "sound"],
  },
  // AI — Audio & Speech
  {
    type: "text-to-speech",
    label: "Text to Speech",
    icon: <Mic className="h-4 w-4" />,
    category: "AI",
    group: "audio-speech",
  },
  {
    type: "text-to-audio",
    label: "Text to Audio",
    icon: <Volume2 className="h-4 w-4" />,
    category: "AI",
    group: "audio-sfx",
  },
  {
    type: "audio-isolation",
    label: "Voice Extractor",
    icon: <AudioWaveform className="h-4 w-4" />,
    category: "AI",
    group: "audio-clean-separate",
  },
  {
    type: "audio-separation",
    label: "Audio Separation",
    icon: <Scissors className="h-4 w-4" />,
    category: "AI",
    group: "audio-clean-separate",
  },
  {
    type: "text-to-dialogue",
    label: "Text to Dialogue",
    icon: <Users className="h-4 w-4" />,
    category: "AI",
    group: "audio-speech",
  },
  {
    type: "voice-changer",
    label: "Voice Changer",
    icon: <AudioWaveform className="h-4 w-4" />,
    category: "AI",
    group: "audio-voices",
  },
  {
    type: "voice-changer-pro",
    label: "Voice Changer Pro",
    icon: <AudioWaveform className="h-4 w-4" />,
    category: "AI",
    group: "audio-voices",
  },
  {
    type: "dubbing",
    label: "Dubbing",
    icon: <Languages className="h-4 w-4" />,
    category: "AI",
    group: "audio-voices",
  },
  {
    type: "voice-remix",
    label: "Voice Remix",
    icon: <Mic className="h-4 w-4" />,
    category: "AI",
    group: "audio-voices",
  },
  {
    type: "voice-design",
    label: "Voice Design",
    icon: <Wand2 className="h-4 w-4" />,
    category: "AI",
    group: "audio-voices",
  },
  {
    type: "forced-alignment",
    label: "Forced Alignment",
    icon: <AlignLeft className="h-4 w-4" />,
    category: "AI",
    group: "audio-transcribe",
  },
  {
    type: "generate-music",
    label: "Generate Music",
    icon: <Music className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  // AI — Suno Music
  {
    type: "suno-voice",
    label: "Suno Voice",
    icon: <Mic className="h-4 w-4" />,
    category: "AI",
    group: "cc-music-voice",
  },
  {
    type: "suno-generate",
    label: "Suno Create Music",
    icon: <Music className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-cover",
    label: "Suno Cover",
    icon: <Disc3 className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-extend",
    label: "Suno Extend",
    icon: <FastForward className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-lyrics",
    label: "Suno Lyrics",
    icon: <FileText className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-separate",
    label: "Suno Separate",
    icon: <Scissors className="h-4 w-4" />,
    category: "AI",
    group: "audio-clean-separate",
  },
  {
    type: "suno-music-video",
    label: "Music Video",
    icon: <Film className="h-4 w-4" />,
    category: "AI",
    group: "video-create",
  },
  {
    type: "suno-mashup",
    label: "Suno Mashup",
    icon: <Merge className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-replace-section",
    label: "Suno Replace Section",
    icon: <Scissors className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-style-boost",
    label: "Suno Style Boost",
    icon: <Sparkles className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-add-instrumental",
    label: "Suno Add Instrumental",
    icon: <Music className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-add-vocals",
    label: "Suno Add Vocals",
    icon: <Mic className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-convert-wav",
    label: "Suno Convert WAV",
    icon: <AudioLines className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  {
    type: "suno-upload-extend",
    label: "Suno Upload Extend",
    icon: <FastForward className="h-4 w-4" />,
    category: "AI",
    group: "audio-music",
  },
  // AI — Quality
  {
    type: "qa-check",
    label: "QA Check",
    icon: <ShieldCheck className="h-4 w-4" />,
    category: "AI",
    group: "automate-logic",
    adminOnly: true,
  },
  {
    type: "image-critic",
    label: "Image Critic",
    icon: <Eye className="h-4 w-4" />,
    category: "AI",
    group: "image-understand",
    // adminOnly NOT set — image-critic is user-facing (qa-check is admin-only; we deliberately differ)
  },
  // Processing — Image
  {
    type: "image-collage",
    label: "Image Collage",
    icon: <LayoutGrid className="h-4 w-4" />,
    category: "Processing",
    group: "image-edit-retouch",
    keywords: ["collage", "grid", "montage", "mosaic", "combine images", "contact sheet", "tile"],
  },
  // Processing — Video
  {
    type: "combine-videos",
    label: "Combine Videos",
    icon: <Merge className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "assemble-narrated-video",
    label: "Assemble Narrated Video",
    icon: <Merge className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
    keywords: ["narration", "voiceover", "narrated", "audio-led", "montage", "assemble"],
  },
  {
    type: "resize-video",
    label: "Resize Video",
    icon: <Maximize className="h-4 w-4" />,
    category: "Processing",
    group: "video-format-export",
  },
  {
    type: "social-media-format",
    label: "Social Media Format",
    icon: <Share2 className="h-4 w-4" />,
    category: "Processing",
    group: "video-format-export",
  },
  {
    type: "trim-video",
    label: "Trim Video",
    icon: <Scissors className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "extract-frame",
    label: "Extract Frame",
    icon: <Frame className="h-4 w-4" />,
    category: "Processing",
    group: "image-edit-retouch",
  },
  {
    type: "video-upscale",
    label: "Upscale Video",
    icon: <ArrowUpFromLine className="h-4 w-4" />,
    category: "Processing",
    group: "video-format-export",
  },
  {
    type: "add-captions",
    label: "Add Captions",
    icon: <Captions className="h-4 w-4" />,
    category: "Processing",
    group: "video-titles-graphics",
  },
  {
    type: "video-analysis",
    label: "Video Analysis",
    icon: <ScanSearch className="h-4 w-4" />,
    category: "Processing",
    group: "video-analyze",
    keywords: ["analyze video", "scene breakdown", "shot list", "understand video", "describe video", "storyboard from video"],
  },
  {
    type: "video-audit",
    label: "AI Audit",
    icon: <SearchCheck className="h-4 w-4" />,
    category: "Processing",
    group: "video-analyze",
    keywords: ["audit", "ai audit", "verify analysis", "check analysis", "fact check video", "qa analysis", "review scene breakdown", "correct analysis"],
  },
  // Processing — Video Production
  {
    type: "video-composer",
    label: "Compose Video",
    icon: <Sparkles className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "after-effects",
    label: "After Effects",
    icon: <Wand2 className="h-4 w-4" />,
    category: "Processing",
    group: "video-titles-graphics",
  },
  {
    type: "lottie-overlay",
    label: "Lottie Overlay",
    icon: <Layers className="h-4 w-4" />,
    category: "Processing",
    group: "video-titles-graphics",
  },
  {
    type: "3d-title",
    label: "3D Title",
    icon: <Box className="h-4 w-4" />,
    category: "Processing",
    group: "video-titles-graphics",
  },
  {
    type: "motion-graphics",
    label: "Motion Graphics",
    icon: <Shapes className="h-4 w-4" />,
    category: "Processing",
    group: "video-titles-graphics",
  },
  {
    type: "composite",
    label: "Composite",
    icon: <Layers className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "render-video",
    label: "Render Video",
    icon: <Film className="h-4 w-4" />,
    category: "Processing",
    group: "video-titles-graphics",
  },
  {
    type: "speed-ramp",
    label: "Adjust Speed",
    icon: <Gauge className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "loop-video",
    label: "Loop Video",
    icon: <Repeat className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "fade-video",
    label: "Fade In/Out",
    icon: <SunDim className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "transcode-video",
    label: "Transcode Video",
    icon: <RefreshCw className="h-4 w-4" />,
    category: "Processing",
    group: "video-format-export",
  },
  {
    type: "manual-edit",
    label: "Manual Edit",
    icon: <Scissors className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  // Processing — Audio
  {
    type: "merge-video-audio",
    label: "Merge Video & Audio",
    icon: <Volume2 className="h-4 w-4" />,
    category: "Processing",
    group: "video-sound",
  },
  {
    type: "trim-audio",
    label: "Trim Audio",
    icon: <AudioLines className="h-4 w-4" />,
    category: "Processing",
    group: "audio-edit",
  },
  {
    type: "split-media",
    label: "Split into Chunks",
    icon: <Scissors className="h-4 w-4" />,
    category: "Processing",
    group: "video-cut-assemble",
  },
  {
    type: "extract-audio",
    label: "Extract Audio",
    icon: <AudioLines className="h-4 w-4" />,
    category: "Processing",
    group: "video-sound",
    keywords: ["extract audio", "rip audio", "audio from video", "demux", "detach audio", "get audio", "mp3", "split video audio"],
  },
  {
    type: "remove-audio",
    label: "Remove Audio",
    icon: <VolumeX className="h-4 w-4" />,
    category: "Processing",
    group: "video-sound",
    keywords: ["remove audio", "mute", "strip audio", "silent video", "delete audio", "no sound", "detach audio", "split video audio"],
  },
  {
    type: "mix-audio",
    label: "Mix Audio",
    icon: <Music className="h-4 w-4" />,
    category: "Processing",
    group: "audio-edit",
  },
  {
    type: "combine-audio",
    label: "Combine Audio",
    icon: <ListMusic className="h-4 w-4" />,
    category: "Processing",
    group: "audio-edit",
  },
  {
    type: "adjust-volume",
    label: "Adjust Volume",
    icon: <SlidersHorizontal className="h-4 w-4" />,
    category: "Processing",
    group: "audio-edit",
  },
  {
    type: "audio-fx",
    label: "Audio FX",
    icon: <SlidersHorizontal className="h-4 w-4" />,
    category: "Processing",
    group: "audio-edit",
  },
  // Processing — Text
  {
    type: "combine-text",
    label: "Combine Text",
    icon: <Merge className="h-4 w-4" />,
    category: "Processing",
    group: "automate-text",
  },
  {
    type: "split-text",
    label: "Split Text",
    icon: <Scissors className="h-4 w-4" />,
    category: "Processing",
    group: "automate-text",
  },
  // Assets
  {
    type: "character",
    label: "Character Asset",
    icon: <UserPlus className="h-4 w-4" />,
    category: "Assets",
    group: "assets-characters",
  },
  {
    type: "object",
    label: "Object/Props Asset",
    icon: <Package className="h-4 w-4" />,
    category: "Assets",
    group: "assets-objects",
  },
  {
    type: "creature",
    label: "Animal/Creature Asset",
    icon: <PawPrint className="h-4 w-4" />,
    category: "Assets",
    group: "assets-creatures",
  },
  {
    type: "location",
    label: "Location Asset",
    icon: <MapPin className="h-4 w-4" />,
    category: "Assets",
    group: "assets-places",
  },
  {
    type: "face",
    label: "Create Face",
    icon: <Smile className="h-4 w-4" />,
    category: "Assets",
    group: "assets-characters",
  },
  // Scene (Phase 1B.2 pipeline-managed SceneNode — replaces legacy scene)
  {
    type: "scene",
    label: "Scene",
    icon: <Clapperboard className="h-4 w-4" />,
    category: "AI",
    group: "video-story-script",
    keywords: ["scene", "shot list", "storyboard", "camera", "pipeline"],
  },
  // Output
  {
    type: "save-to-storage",
    label: "Save to Storage",
    icon: <HardDrive className="h-4 w-4" />,
    category: "Output",
    group: "publish-export",
  },
  {
    type: "webhook-output",
    label: "Webhook Output",
    icon: <Webhook className="h-4 w-4" />,
    category: "Output",
    group: "publish-export",
  },
  // Output — Social Media
  {
    type: "instagram-post",
    label: "Instagram Post",
    icon: <Instagram className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "tiktok-post",
    label: "TikTok Post",
    icon: <Video className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "youtube-upload",
    label: "YouTube Upload",
    icon: <Youtube className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "linkedin-post",
    label: "LinkedIn Post",
    icon: <Linkedin className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "x-post",
    label: "X Post",
    icon: <Twitter className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "facebook-post",
    label: "Facebook Post",
    icon: <Facebook className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "telegram-post",
    label: "Telegram Post",
    icon: <Send className="h-4 w-4" />,
    category: "Output",
    group: "publish-platforms",
  },
  {
    type: "publish-social",
    label: "Publish to Social",
    icon: <Share2 className="h-4 w-4" />,
    category: "Output",
    group: "publish-one-click",
  },
  // Workflow
  {
    type: "sub-workflow-input",
    label: "Sub-Workflow Input",
    icon: <LogIn className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-workflows",
  },
  {
    type: "sub-workflow-output",
    label: "Sub-Workflow Output",
    icon: <LogOut className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-workflows",
  },
  {
    type: "sub-workflow",
    label: "Sub-Workflow",
    icon: <Workflow className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-workflows",
  },
  {
    type: "teleport-send",
    label: "Teleport Send",
    icon: <Send className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-canvas",
  },
  {
    type: "teleport-receive",
    label: "Teleport Receive",
    icon: <Download className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-canvas",
  },
  {
    type: "router",
    label: "Router",
    icon: <GitBranch className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-logic",
  },
  {
    type: "group",
    label: "Group",
    icon: <Box className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-canvas",
    keywords: ["group", "container", "wrap"],
  },
  {
    type: "collect",
    label: "Collect",
    icon: <Layers className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-lists",
    keywords: ["collect", "gather", "bucket", "by-type", "split-by-type"],
  },
  {
    type: "reduce",
    label: "Choose Best",
    icon: <Trophy className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-lists",
    keywords: ["choose best", "pick best", "judge", "winner", "compare", "reduce", "fan-in", "merge", "join", "aggregate", "vote", "count"],
  },
  {
    type: "sticky-note",
    label: "Sticky Note",
    icon: <StickyNote className="h-4 w-4" />,
    category: "Workflow",
    group: "automate-canvas",
  },
  {
    type: "component" as SceneNodeType,
    label: "Component",
    icon: <Puzzle className="h-4 w-4" />,
    category: "Component",
    group: "automate-workflows",
  },
  {
    type: "preview",
    label: "Preview",
    icon: <Eye className="h-4 w-4" />,
    category: "Processing",
    group: "automate-canvas",
  },
];

/**
 * Returns `NODE_OPTIONS` filtered for the current edition.
 * Truly Cloud-only nodes (`CLOUD_ONLY_NODE_TYPES`) are excluded when
 * `hasCredits()` is false. The Nodaro-EXCLUSIVE nodes (4b) list on EVERY
 * edition — on self-host they run through the nodaro.ai connection and wear
 * the NODARO mark; unconnected installs see the connect CTA on the card and
 * a friendly 503 on run, never a silent 404.
 * Use this instead of `NODE_OPTIONS` whenever building a user-visible list.
 */
export function getNodeOptions(): ReadonlyArray<NodeOption> {
  return NODE_OPTIONS.filter((o) => !CLOUD_ONLY_NODE_TYPES.has(o.type) || hasCredits());
}
