/**
 * The region editor's geometry copy, held to the cloud plugin's renderer case
 * by case (decided 2026-10-08: the copy stays, and any drift fails CI).
 *
 * `fixtures/plugin-geometry-cases.json` is GENERATED by the plugin from its own
 * `speakerViewCanvas`, `layoutSlotRects` and `coverCropRect` — never edit it
 * by hand. Both directions are guarded:
 *  - this test: the copy in `region-geometry.ts` must reproduce every case;
 *  - the plugin's `speaker-view-geometry-parity` workflow (every push, PR and
 *    nightly) reads this file from `dev` and fails when it is not exactly what
 *    the plugin draws — so a hand edit of the fixture, or a plugin geometry
 *    change, fails there.
 * When the plugin's geometry changes: regenerate this file from the plugin
 * (the command is in its `app-geometry-parity.test.ts`), then change the copy
 * until this test passes. The path is fixed in the plugin; moving the file
 * fails the plugin's workflow.
 */
import { describe, it, expect } from "vitest"
import cases from "./fixtures/plugin-geometry-cases.json"
import { coverCropRect, layoutSlotRects, speakerViewCanvas, type SpeakerViewAspect } from "../region-geometry"

type Quad = [number, number, number, number]
type Pair = [number, number]
interface Fixture {
  canvases: Array<{ aspect: SpeakerViewAspect; quality: "proxy" | "final"; canvas: Pair }>
  slots: Array<{ layout: string; aspect: SpeakerViewAspect; quality: "proxy" | "final"; n: number; rects: Quad[] | "refused" }>
  coverCrops: Array<{ region: Quad; source: Pair; slot: Pair; crop: Quad }>
}
const fixture = cases as unknown as Fixture

/** JSON-round-tripped, as the plugin wrote it: `-0` and float printing never read as drift. */
const asJson = (v: unknown): unknown => JSON.parse(JSON.stringify(v))
const size = (p: Pair) => ({ width: p[0], height: p[1] })

describe("region-geometry.ts reproduces the plugin's geometry (generated cases)", () => {
  it("covers every layout, aspect and quality the renderer draws", () => {
    expect(fixture.canvases).toHaveLength(8)
    expect(new Set(fixture.slots.filter((c) => c.rects !== "refused").map((c) => c.layout))).toEqual(new Set(["single", "side-by-side", "stacked", "grid", "pip"]))
    expect(fixture.coverCrops.length).toBeGreaterThan(400)
  })

  it("the canvas of every aspect × quality", () => {
    for (const c of fixture.canvases) {
      const got = speakerViewCanvas(c.aspect, c.quality)
      expect([got.width, got.height], `${c.aspect} ${c.quality}`).toEqual(c.canvas)
    }
  })

  it("the slot rects of every layout × aspect × quality × count; no slots where the plugin refuses", () => {
    for (const c of fixture.slots) {
      const canvas = fixture.canvases.find((k) => k.aspect === c.aspect && k.quality === c.quality)!.canvas
      const got = layoutSlotRects(c.layout, size(canvas), c.n).map((r) => [r.x, r.y, r.w, r.h])
      expect(asJson(got), JSON.stringify(c)).toEqual(c.rects === "refused" ? [] : c.rects)
    }
  })

  it("the cover crop of every region × source × slot", () => {
    for (const c of fixture.coverCrops) {
      const r = coverCropRect({ x: c.region[0], y: c.region[1], w: c.region[2], h: c.region[3] }, size(c.source), size(c.slot))
      expect(asJson([r.x, r.y, r.w, r.h]), JSON.stringify(c)).toEqual(c.crop)
    }
  })
})
