/**
 * `describeOps` — what a batch WOULD do, in the user's words.
 *
 * The copilot proposes a batch before it applies one, and the ops route echoes
 * the same lines back as receipts. Both read this function, which is the whole
 * design: the sentence a person approves is generated by the code that does the
 * work, so an operation cannot describe itself as one thing and do another.
 *
 * The lines are therefore checked here against three rules from
 * `ops/SECTIONS.md` ("How a receipt reads") rather than against a snapshot:
 *
 *  - one line per op, in order;
 *  - the target named the way the user sees it — a name, or `Shot <n>` — and
 *    **never an id**, because an id in a confirmation prompt is noise the
 *    reader cannot check;
 *  - past tense, one sentence, ending in a period.
 *
 * "Tested per op" is taken literally: the golden op script exercises every
 * operation this build implements, and the coverage test below fails if an
 * operation is ever added without a line of its own.
 */
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"

import { describe, expect, it } from "vitest"

import { describeOps } from "../describe-ops"
import { OP_SCHEMAS } from "../ops/schema"
import type { Production } from "../ops/production"
import { parseProduction } from "../shot-graph"
import type { WorkflowLike } from "../workflow-like"

const FIXTURES = resolve(dirname(fileURLToPath(import.meta.url)), "..", "fixtures")

const golden = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-production.json"), "utf8"),
) as WorkflowLike

const goldenOps = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-ops.json"), "utf8"),
) as ReadonlyArray<{ op: string }>

/** Two shots, one named and one not — the two ways a shot is labelled. */
function base(): Production {
  return { shots: [{ id: "shot-1", name: "Rooftop" }, { id: "shot-2" }] }
}

describe("describeOps", () => {
  it("returns one line per op, in order", () => {
    const lines = describeOps(base(), [
      { op: "rename_shot", id: "shot-2", name: "Coda" },
      { op: "select_shot", shotId: "shot-1" },
    ])
    expect(lines).toHaveLength(2)
    expect(lines[0]).toContain("Coda")
    expect(lines[1]).toContain("Rooftop")
  })

  it("names an unnamed shot by its timeline position, never by its id", () => {
    const [line] = describeOps(base(), [
      { op: "set_scene_prompt", shotId: "shot-2", text: "Rain on the ridge." },
    ])
    expect(line).toContain("Shot 2")
    expect(line).not.toContain("shot-2")
  })

  it("describes without applying — the document is untouched", () => {
    const before = base()
    const snapshot = structuredClone(before)
    describeOps(before, [{ op: "rename_shot", id: "shot-1", name: "Ledge" }])
    expect(before).toEqual(snapshot)
  })

  it("describes an op against the document the ops before it left", () => {
    // The rename has to be visible to the second line, or a batch would
    // describe itself against a document that never existed.
    const lines = describeOps(base(), [
      { op: "rename_shot", id: "shot-2", name: "Coda" },
      { op: "remove_shot", id: "shot-2" },
    ])
    expect(lines[1]).toContain("Coda")
  })

  it("is deterministic — the same batch reads the same way twice", () => {
    const batch = [
      { op: "add_shot", id: "shot-9" },
      { op: "insert_shots", graph: { nodes: [], edges: [], settings: {} } },
    ]
    expect(describeOps(base(), batch)).toEqual(describeOps(base(), batch))
  })

  it("refuses a batch it cannot describe, naming the op's index", () => {
    expect(() =>
      describeOps(base(), [
        { op: "rename_shot", id: "shot-1", name: "Ledge" },
        { op: "rename_shot", id: "shot-404", name: "Nope" },
      ]),
    ).toThrowError(/shot-404/)
  })
})

describe("every operation describes itself", () => {
  const lines = describeOps(parseProduction(golden), goldenOps)

  it("covers every operation this build implements", () => {
    // The three P1.2 placeholders refuse rather than describe, so they are the
    // only names the script may leave out.
    const deferred = ["land_job", "add_pending_still", "remove_pending_still"]
    const implemented = Object.keys(OP_SCHEMAS).filter(
      (name) => !deferred.includes(name),
    )
    const described = new Set(goldenOps.map((op) => op.op))
    expect(implemented.filter((name) => !described.has(name))).toEqual([])
  })

  it("gives every op one non-empty sentence", () => {
    expect(lines).toHaveLength(goldenOps.length)
    for (const line of lines) {
      expect(line.trim()).not.toBe("")
      expect(line).toMatch(/[.!]$/)
      expect(line).not.toContain("\n")
    }
  })

  it("puts no id in the prose", () => {
    const production = parseProduction(golden)
    const ids = [
      ...production.shots.map((shot) => shot.id),
      ...(production.folders ?? []).map((folder) => folder.id),
      ...(production.cuts ?? []).map((cut) => cut.id),
      ...(production.trash ?? []).map((item) => item.id),
    ]
    for (const line of lines) {
      for (const id of ids) expect(line).not.toContain(id)
    }
  })

  it("reads the way the spec's examples read", () => {
    const byOp = new Map(goldenOps.map((op, index) => [op.op, lines[index]]))
    expect(byOp.get("remove_still_result")).toMatch(/^Deleted take \d+ of .+\.$/)
    expect(byOp.get("enroll_cast")).toMatch(/^Bound @.+ \(\w+\)\.$/)
    expect(byOp.get("clear_trash")).toMatch(/^Emptied the bin \(\d+ items? destroyed\)\.$/)
  })
})
